import type { Resource } from '@/types';

// The Class Central sitemap and public pages can be fetched.
// Use their public search URL pattern:
// https://www.classcentral.com/search?q={topic}&free=true&sort=rating-up
// Since they don't have a formal API, we implement this as a curated static list
// that we update periodically.

export const classCentralResources: Resource[] = [
  { id: 'cc-1', title: 'CS50\'s Introduction to Programming with Scratch', url: 'https://cs50.harvard.edu/scratch', source: 'Class Central', format: 'course', field: 'Technology', topics: ['Scratch', 'Programming'], level: 'beginner', language: 'en', isFree: true, qualityScore: 94, votes: 1000, addedBy: 'team', verified: true, description: 'A gentle introduction to programming.', duration: '3 weeks' },
  { id: 'cc-2', title: 'Learning How to Learn', url: 'https://www.coursera.org/learn/learning-how-to-learn', source: 'Class Central', format: 'course', field: 'Humanities', topics: ['Learning', 'Productivity'], level: 'beginner', language: 'en', isFree: true, qualityScore: 98, votes: 5000, addedBy: 'team', verified: true, description: 'Powerful mental tools to help you master tough subjects.', duration: '4 weeks' },
  { id: 'cc-3', title: 'Introduction to Linux', url: 'https://www.edx.org/course/introduction-to-linux', source: 'Class Central', format: 'course', field: 'Technology', topics: ['Linux', 'OS'], level: 'beginner', language: 'en', isFree: true, qualityScore: 95, votes: 2000, addedBy: 'team', verified: true, description: 'Never learned Linux? This is the place to start.', duration: '14 weeks' },
  { id: 'cc-4', title: 'Prompt Engineering for Everyone', url: 'https://www.edx.org/course/prompt-engineering-for-everyone', source: 'Class Central', format: 'course', field: 'Technology', topics: ['AI', 'Prompt Engineering'], level: 'beginner', language: 'en', isFree: true, qualityScore: 93, votes: 1500, addedBy: 'team', verified: true, description: 'Learn how to write effective prompts for AI models.', duration: '4 weeks' },
  { id: 'cc-5', title: 'Introduction to Cybersecurity', url: 'https://skillsforall.com/course/introduction-to-cybersecurity', source: 'Class Central', format: 'course', field: 'Technology', topics: ['Cybersecurity', 'Security'], level: 'beginner', language: 'en', isFree: true, qualityScore: 94, votes: 1800, addedBy: 'team', verified: true, description: 'Cisco\'s introduction to the world of cybersecurity.', duration: '15 hours' },
  { id: 'cc-6', title: 'Python for Everybody', url: 'https://www.coursera.org/specializations/python', source: 'Class Central', format: 'course', field: 'Technology', topics: ['Python', 'Programming'], level: 'beginner', language: 'en', isFree: true, qualityScore: 96, votes: 4000, addedBy: 'team', verified: true, description: 'Learn to Program and Analyze Data with Python.', duration: '8 months' },
  { id: 'cc-7', title: 'Machine Learning Specialization', url: 'https://www.coursera.org/specializations/machine-learning-introduction', source: 'Class Central', format: 'course', field: 'Data Science', topics: ['Machine Learning', 'AI'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 98, votes: 3500, addedBy: 'team', verified: true, description: 'A foundational online program by Andrew Ng.', duration: '3 months' },
  { id: 'cc-8', title: 'IBM Data Science Professional Certificate', url: 'https://www.coursera.org/professional-certificates/ibm-data-science', source: 'Class Central', format: 'course', field: 'Data Science', topics: ['Data Science', 'Python', 'SQL'], level: 'beginner', language: 'en', isFree: true, qualityScore: 95, votes: 2800, addedBy: 'team', verified: true, description: 'Kickstart your career in data science & ML.', duration: '11 months' },
];
