
import type { Course, Opportunity, Guide, Resource } from "./types";

export const courses: Course[] = [
  {
    id: "c1",
    type: "course",
    title: "AI For Everyone",
    provider: "DeepLearning.AI",
    description: "A non-technical course by Andrew Ng that provides a broad understanding of AI, its terminology, and what it can (and cannot) do. Perfect for business leaders and anyone new to the field.",
    url: "https://www.coursera.org/learn/ai-for-everyone",
    category: "Data Science",
    skillLevel: "Beginner",
    duration: "4 Weeks",
  },
  {
    id: "c2",
    type: "course",
    title: "CS50's Introduction to Computer Science",
    provider: "Harvard",
    description: "Harvard University's legendary introduction to the intellectual enterprises of computer science and the art of programming. Covers C, Python, SQL, JavaScript, and more.",
    url: "https://www.edx.org/course/introduction-computer-science-harvardx-cs50x",
    category: "Computer Science",
    skillLevel: "Beginner",
    duration: "12 Weeks",
  },
  {
    id: "c3",
    type: "course",
    title: "IBM Data Science Professional Certificate",
    provider: "IBM",
    description: "Launch your career in data science. Build data science skills, learn Python and SQL, analyze and visualize data, and build machine learning models. No prior experience required.",
    url: "https://www.coursera.org/professional-certificates/ibm-data-science",
    category: "Data Science",
    skillLevel: "Beginner",
    duration: "11 Months",
  },
  {
    id: "c4",
    type: "course",
    title: "The Science of Well-Being",
    provider: "Yale",
    description: "Professor Laurie Santos reveals misconceptions about happiness and inspiring lessons from psychology to help you live a more fulfilling life. A highly popular course on Coursera.",
    url: "https://www.coursera.org/learn/the-science-of-well-being",
    category: "Health",
    skillLevel: "Beginner",
    duration: "10 Weeks",
  },
  {
    id: "c5",
    type: "course",
    title: "JavaScript Algorithms and Data Structures",
    provider: "freeCodeCamp",
    description: "Learn the fundamentals of JavaScript, the language of the web. Dive into data structures like arrays and objects. A core certification for aspiring web developers.",
    url: "https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/",
    category: "Computer Science",
    skillLevel: "Beginner",
    duration: "300 Hours",
  },
  {
    id: "c6",
    type: "course",
    title: "Google UX Design Professional Certificate",
    provider: "Google",
    description: "Get started in the fast-growing field of user experience (UX) design. Learn the basics of UX research, design thinking, and creating high-fidelity prototypes for digital products.",
    url: "https://www.coursera.org/professional-certificates/google-ux-design",
    category: "Art & Design",
    skillLevel: "Beginner",
    duration: "6 Months",
  },
  {
    id: "c7",
    type: "course",
    title: "Machine Learning Specialization",
    provider: "Stanford",
    description: "The successor to Andrew Ng's original Machine Learning course. Learn modern ML concepts from Supervised to Unsupervised Learning, and best practices from the experts.",
    url: "https://www.coursera.org/specializations/machine-learning-introduction",
    category: "Data Science",
    skillLevel: "Intermediate",
    duration: "3 Months",
  },
  {
    id: "c8",
    type: "course",
    title: "Python for Everybody Specialization",
    provider: "University of Michigan",
    description: "This Specialization will introduce fundamental programming concepts including data structures, networked application program interfaces, and databases, using the Python programming language.",
    url: "https://www.coursera.org/specializations/python",
    category: "Computer Science",
    skillLevel: "Beginner",
    duration: "8 Months",
  },
  {
    id: "c9",
    type: "course",
    title: "Graphic Design Specialization",
    provider: "CalArts",
    description: "Learn the fundamental principles of graphic design: image making, typography, composition, and working with color and shape. A foundational course for aspiring designers.",
    url: "https://www.coursera.org/specializations/graphic-design",
    category: "Art & Design",
    skillLevel: "Beginner",
    duration: "6 Months",
  },
  {
    id: "c10",
    type: "course",
    title: "AWS Cloud Practitioner Essentials",
    provider: "Amazon Web Services",
    description: "A fundamental-level course on the AWS Cloud. This is a great starting point for non-technical roles or those new to cloud computing. Prepare for the CLF-C02 exam.",
    url: "https://explore.skillbuilder.aws/learn/course/external/view/elearning/134/aws-cloud-practitioner-essentials",
    category: "Engineering",
    skillLevel: "Beginner",
    duration: "6 Hours",
  },
  {
    id: "c11",
    type: "course",
    title: "Financial Markets",
    provider: "Yale",
    description: "An overview of the ideas, methods, and institutions that permit human society to manage risks and foster enterprise. Emphasis on financially-savvy leadership skills.",
    url: "https://www.coursera.org/learn/financial-markets-global",
    category: "Business",
    skillLevel: "Intermediate",
    duration: "7 Weeks",
  },
  {
    id: "c12",
    type: "course",
    title: "Learning How to Learn",
    provider: "DeepLearning.AI",
    description: "Powerful mental tools to help you master tough subjects. This course gives you easy access to invaluable learning techniques used by experts in art, music, literature, math, science, and sports.",
    url: "https://www.coursera.org/learn/learning-how-to-learn",
    category: "Personal Development",
    skillLevel: "Beginner",
    duration: "4 Weeks",
  },
  {
    id: 'c13',
    type: 'course',
    title: 'Introduction to Psychology',
    provider: 'MIT',
    description:
      'This course is a survey of the scientific study of human nature, including how the mind works, and how the brain supports the mind. From the MIT OpenCourseWare collection.',
    url: 'https://ocw.mit.edu/courses/9-00sc-introduction-to-psychology-fall-2011/',
    category: 'Humanities',
    skillLevel: 'Beginner',
    duration: '15 Weeks',
  },
  {
    id: "c14",
    type: "course",
    title: "The Complete 2024 Web Development Bootcamp",
    provider: "Udemy",
    description: "Become a Full-Stack Web Developer with just one course. Covers HTML, CSS, Javascript, Node, React, MongoDB, Web3 and DApps. Taught by a top-rated instructor.",
    url: "https://www.udemy.com/course/the-complete-web-development-bootcamp/",
    category: "Computer Science",
    skillLevel: "Beginner",
    duration: "65.5 Hours",
  },
  {
    id: "c15",
    type: "course",
    title: "Introduction to Kubernetes",
    provider: "The Linux Foundation",
    description: "This course introduces you to the basic concepts and architecture of Kubernetes, a powerful system for managing containerized applications at scale. Essential for modern DevOps.",
    url: "https://training.linuxfoundation.org/training/introduction-to-kubernetes-lfs158x/",
    category: "Engineering",
    skillLevel: "Intermediate",
    duration: "14 Weeks",
  },
  {
    id: "c16",
    type: "course",
    title: "Modern Art & Ideas",
    provider: "MoMA",
    description: "Designed for anyone interested in learning more about modern and contemporary art. Each week, you will look at art through a different theme like Places & Spaces, and Art & Identity.",
    url: "https://www.coursera.org/learn/modern-art-ideas",
    category: "Art & Design",
    skillLevel: "Beginner",
    duration: "5 Weeks",
  },
  {
    id: "c17",
    type: "course",
    title: "Data Analyst Nanodegree",
    provider: "Udacity",
    description: "Learn to use Python, SQL, and statistics to uncover insights, communicate critical findings, and create data-driven solutions. This Nanodegree program is a great entry point into data analysis.",
    url: "https://www.udacity.com/course/data-analyst-nanodegree--nd002",
    category: "Data Science",
    skillLevel: "Intermediate",
    duration: "4 Months",
  },
  {
    id: "c18",
    type: "course",
    title: "Excel Skills for Business: Essentials",
    provider: "Macquarie University",
    description: "This is the first course in a popular Specialization. You will learn the essentials of Microsoft Excel, including spreadsheet creation, calculations, and data formatting.",
    url: "https://www.coursera.org/learn/excel-skills-business-essentials",
    category: "Business",
    skillLevel: "Beginner",
    duration: "6 Weeks",
  },
  {
    id: "c19",
    type: "course",
    title: "Introduction to Philosophy",
    provider: "University of Edinburgh",
    description: "This course will introduce you to some of the main areas of research in contemporary philosophy. Each module a different philosopher will talk you through important questions and issues.",
    url: "https://www.coursera.org/learn/philosophy",
    category: "Humanities",
    skillLevel: "Beginner",
    duration: "7 Weeks",
  },
  {
    id: "c20",
    type: "course",
    title: "Become a React Developer",
    provider: "LinkedIn Learning",
    description: "Learn how to build modern, interactive web applications with React.js. This learning path covers everything from the basics of React components to state management with Redux and hooks.",
    url: "https://www.linkedin.com/learning/paths/become-a-react-developer",
    category: "Computer Science",
    skillLevel: "Intermediate",
    duration: "25 Hours",
  },
   {
    id: 'c21',
    type: 'course',
    title: 'Natural Language Processing Specialization',
    provider: 'DeepLearning.AI',
    description: 'Break into the NLP space. Master cutting-edge techniques for sentiment analysis, chatbots, and more. Taught by experts from Hugging Face and DeepLearning.AI.',
    url: 'https://www.coursera.org/specializations/natural-language-processing',
    category: 'Data Science',
    skillLevel: 'Advanced',
    duration: '4 Months',
  },
  {
    id: 'c22',
    type: 'course',
    title: 'The Rust Programming Language',
    provider: 'Pluralsight',
    description: 'Learn the fundamentals of Rust, a language known for its performance and safety. This path covers everything from basic syntax to advanced topics like concurrency.',
    url: 'https://www.pluralsight.com/paths/the-rust-programming-language',
    category: 'Computer Science',
    skillLevel: 'Intermediate',
    duration: '21 Hours',
  },
  {
    id: 'c23',
    type: 'course',
    title: 'Google Cloud Digital Leader Training',
    provider: 'Google Cloud',
    description: 'A foundational course for anyone looking to understand cloud technology from a business perspective. Learn the capabilities of Google Cloud and how it can be used to achieve business goals.',
    url: 'https://www.coursera.org/learn/cloud-digital-leader-training-certification',
    category: 'Engineering',
    skillLevel: 'Beginner',
    duration: '9 Hours',
  },
  {
    id: 'c24',
    type: 'course',
    title: 'Introduction to Cybersecurity Tools & Cyber Attacks',
    provider: 'IBM',
    description: 'Gain insights into the important work of cybersecurity professionals. Understand threats, attacks, and the tools used to combat them, from SIEMs to network security.',
    url: 'https://www.coursera.org/learn/introduction-cybersecurity-tools-cyber-attacks',
    category: 'Engineering',
    skillLevel: 'Beginner',
    duration: 'Self-paced',
  },
  {
    id: 'c25',
    type: 'course',
    title: 'Agile with Atlassian Jira',
    provider: 'Atlassian',
    description: 'Learn the key principles of Agile development and how to apply them using Jira Software. This course covers scrum boards, backlogs, and agile reporting.',
    url: 'https://www.coursera.org/learn/agile-atlassian-jira',
    category: 'Business',
    skillLevel: 'Intermediate',
    duration: '11 Hours',
  },
];

export const opportunities: Opportunity[] = [
  {
    id: "o1",
    type: "opportunity",
    title: "Software Engineering Intern",
    provider: "Google",
    description: "Join Google's engineering team to work on challenging projects impacting billions of users, from Google Search to Android and Cloud. Open to students pursuing a degree in computer science or a related field.",
    url: "https://buildyourfuture.withgoogle.com/internships",
    opportunityType: "Internship",
    location: "Remote / Multiple",
  },
  {
    id: "o2",
    type: "opportunity",
    title: "Google Summer of Code",
    provider: "Google",
    description: "A global, online program focused on bringing new contributors into open source software development. GSoC Contributors work with an open source organization on a 12+ week programming project.",
    url: "https://summerofcode.withgoogle.com/",
    opportunityType: "Fellowship",
    location: "Global / Remote",
  },
  {
    id: "o3",
    type: "opportunity",
    title: "Rhodes Scholarship",
    provider: "University of Oxford",
    description: "A prestigious postgraduate award supporting exceptional all-round students from around the world to study at the University of Oxford. Covers all university fees and a personal stipend.",
    url: "https://www.rhodeshouse.ox.ac.uk/scholarships/the-rhodes-scholarship/",
    opportunityType: "Scholarship",
    location: "Global",
  },
  {
    id: "o4",
    type: "opportunity",
    title: "Microsoft Imagine Cup",
    provider: "Microsoft",
    description: "A global student technology competition where teams create innovative solutions using Microsoft technologies to tackle some of the world's biggest social, environmental, and health challenges.",
    url: "https://imaginecup.microsoft.com/",
    opportunityType: "Contest",
    location: "Global",
  },
  {
    id: "o5",
    type: "opportunity",
    title: "Product Design Intern",
    provider: "Meta",
    description: "Internship for students passionate about building and shipping products that people love. Work on products like Facebook, Instagram, and WhatsApp, influencing the user experience for billions.",
    url: "https://www.metacareers.com/students-and-graduates/programs/interns",
    opportunityType: "Internship",
    location: "London, UK / USA",
  },
  {
    id: "o6",
    type: "opportunity",
    title: "Knight-Hennessy Scholarship",
    provider: "Stanford University",
    description: "A graduate-level scholarship for study at Stanford University, preparing a new generation of global leaders with the skills to address complex challenges. Scholars receive funding for any graduate degree at Stanford.",
    url: "https://knight-hennessy.stanford.edu/",
    opportunityType: "Scholarship",
    location: "Global",
  },
  {
    id: "o7",
    type: "opportunity",
    title: "Amazon Future Engineer Scholarship",
    provider: "Amazon",
    description: "A scholarship of up to $40,000 for students from underserved communities who are pursuing a degree in computer science, plus a paid summer internship at Amazon after their first year.",
    url: "https://www.amazonfutureengineer.com/scholarships",
    opportunityType: "Scholarship",
    location: "USA",
  },
  {
    id: "o8",
    type: "opportunity",
    title: "OpenAI Residency",
    provider: "OpenAI",
    description: "A 6-month program for researchers and engineers to develop their skills in artificial intelligence. A pathway to a full-time role at OpenAI, working on cutting-edge AI models.",
    url: "https://openai.com/careers/openai-residency/",
    opportunityType: "Fellowship",
    location: "San Francisco, CA",
  },
  {
    id: 'o9',
    type: 'opportunity',
    title: 'Data Science for Social Good Fellowship',
    provider: 'University of Chicago',
    description:
      'A summer program to train aspiring data scientists to work on machine learning and data science projects with social impact. Fellows work in small teams on projects with non-profits and government agencies.',
    url: 'https://dssg.uchicago.edu/fellowship/',
    opportunityType: 'Fellowship',
    location: 'Chicago, IL',
  },
  {
    id: 'o10',
    type: 'opportunity',
    title: 'Kaggle Competitions',
    provider: 'Kaggle',
    description:
      'Participate in a wide range of data science competitions, from predicting sales to classifying images. Compete for prize money, earn a global ranking, and improve your machine learning skills.',
    url: 'https://www.kaggle.com/competitions',
    opportunityType: 'Contest',
    location: 'Global / Remote',
  },
  {
    id: 'o11',
    type: 'opportunity',
    title: 'Explore Microsoft - Internship Program',
    provider: 'Microsoft',
    description:
      'A 12-week summer internship program specifically designed for students in their first or second year of a bachelor’s degree program. Explore different roles in software engineering, including product management and development.',
    url: 'https://careers.microsoft.com/v2/global/en/us-student-explore.html',
    opportunityType: 'Internship',
    location: 'Redmond, WA',
  },
  {
    id: 'o12',
    type: 'opportunity',
    title: 'Hertz Fellowship',
    provider: 'Fannie and John Hertz Foundation',
    description:
      'Provides a fellowship for up to five years of PhD study in the applied physical and biological sciences, engineering, or mathematics. One of the most prestigious fellowships in the US.',
    url: 'https://www.hertzfoundation.org/apply/fellowship/',
    opportunityType: 'Fellowship',
    location: 'USA',
  },
   {
    id: 'o13',
    type: 'opportunity',
    title: 'Data Engineering Intern',
    provider: 'IBM',
    description:
      'Work on building and maintaining data pipelines, and learn how to manage large-scale data systems. This internship provides hands-on experience with technologies like Spark, Hadoop, and various database systems.',
    url: 'https://www.ibm.com/careers/internships',
    opportunityType: 'Internship',
    location: 'Multiple',
  },
  {
    id: 'o14',
    type: 'opportunity',
    title: 'Thiel Fellowship',
    provider: 'Thiel Foundation',
    description:
      'Gives $100,000 to young people who want to build new things instead of sitting in a classroom. Fellows skip or stop out of college to receive support from the Thiel Foundation’s network of founders, investors, and scientists.',
    url: 'https://thielfellowship.org/',
    opportunityType: 'Fellowship',
    location: 'Global',
  },
  {
    id: 'o15',
    type: 'opportunity',
    title: 'Adobe Design Circle Scholarship',
    provider: 'Adobe',
    description:
      'A scholarship program for students from underrepresented backgrounds who are pursuing a degree in product design, UX/UI, or a related field. Includes financial assistance, mentorship, and an internship opportunity.',
    url: 'https://www.adobe.com/about-adobe/education/design-circle-scholarships.html',
    opportunityType: 'Scholarship',
    location: 'Global',
  },
];

export const guides: Guide[] = [
    {
        id: "g1",
        type: "guide",
        title: "The Holloway Guide to Technical Recruiting and Hiring",
        provider: "Holloway",
        description: "A comprehensive guide covering everything from sourcing candidates to closing offers. Essential reading for engineering managers and startup founders.",
        url: "https://www.holloway.com/g/technical-recruiting-hiring",
        category: "Career Guide",
    },
    {
        id: "g2",
        type: "guide",
        title: "Startup Playbook",
        provider: "Y Combinator",
        description: "Sam Altman's concise guide to starting a startup. Covers the essential four areas: a great idea, a great team, a great product, and great execution.",
        url: "https://playbook.samaltman.com/",
        category: "Startup",
    },
    {
        id: "g3",
        type: "guide",
        title: "First Round Review",
        provider: "First Round",
        description: "In-depth, long-form articles on technology, product management, engineering, and leadership, based on interviews with industry experts.",
        url: "https://review.firstround.com/",
        category: "Industry Insights",
    },
    {
        id: "g4",
        type: "guide",
        title: "Paul Graham's Essays",
        provider: "Paul Graham",
        description: "A collection of influential essays on startups, technology, and thinking, from the co-founder of Y Combinator.",
        url: "http://www.paulgraham.com/articles.html",
        category: "Startup",
    },
    {
        id: "g5",
        type: "guide",
        title: "Stratechery by Ben Thompson",
        provider: "Stratechery",
        description: "Deep analysis of strategy and business in the tech industry. A must-read for understanding the 'why' behind tech news.",
        url: "https://stratechery.com/",
        category: "Industry Insights",
    },
    {
        id: "g6",
        type: "guide",
        title: "Reforge",
        provider: "Reforge",
        description: "A library of essays and frameworks on growth, product management, and marketing from leading practitioners in the tech industry.",
        url: "https://www.reforge.com/brief",
        category: "Growth & Product",
    },
    {
        id: "g7",
        type: "guide",
        title: "Lenny's Newsletter",
        provider: "Lenny's Newsletter",
        description: "A weekly newsletter from Lenny Rachitsky (ex-Airbnb) focusing on product, growth, and career advice for product managers.",
        url: "https://www.lennysnewsletter.com/",
        category: "Growth & Product",
    },
    {
        id: "g8",
        type: "guide",
        title: "The Ultimate Guide to Resumes",
        provider: "Resume Worded",
        description: "An actionable guide with templates and examples to help you write a resume that gets past automated screeners and impresses recruiters.",
        url: "https://resumeworded.com/resume-guide",
        category: "Career Guide",
    },
     {
        id: "g9",
        type: "guide",
        title: "Blind - Anonymous Professional Network",
        provider: "Teamblind",
        description: "An anonymous community app for the tech industry. Get real, unfiltered advice on careers, compensation, and company culture.",
        url: "https://www.teamblind.com/",
        category: "Career Guide",
    },
     {
        id: "g10",
        type: "guide",
        title: "Levels.fyi - Compare Career Levels & Salary",
        provider: "Levels.fyi",
        description: "Crowdsourced data on salary, benefits, and career ladders at top tech companies. Essential for compensation negotiation.",
        url: "https://www.levels.fyi/",
        category: "Career Guide",
    },
    {
        id: "g11",
        type: "guide",
        title: "The Pragmatic Engineer Newsletter",
        provider: "The Pragmatic Engineer",
        description: "Gergely Orosz's newsletter covering the nuts and bolts of software engineering and tech leadership at high-growth companies.",
        url: "https://blog.pragmaticengineer.com/",
        category: "Industry Insights",
    },
    {
        id: "g12",
        type: "guide",
        title: "A16Z's Content Hub",
        provider: "Andreessen Horowitz",
        description: "Podcasts, articles, and newsletters from the venture capital firm Andreessen Horowitz, covering future trends in technology and business.",
        url: "https://a16z.com/content/",
        category: "Industry Insights",
    },
    {
        id: "g13",
        type: "guide",
        title: "Dan Luu's Blog",
        provider: "Dan Luu",
        description: "In-depth, data-driven posts on software engineering, performance, and the tech industry. Known for rigorous analysis and unconventional insights.",
        url: "https://danluu.com/",
        category: "Computer Science",
    },
    {
        id: "g14",
        type: "guide",
        title: "Systems Design Primer",
        provider: "Donne Martin",
        description: "An open-source collection of materials to help you learn how to design large-scale systems, with a focus on interview preparation.",
        url: "https://github.com/donnemartin/system-design-primer",
        category: "Career Guide",
    },
    {
        id: "g15",
        type: "guide",
        title: "Tech Interview Handbook",
        provider: "Yangshun Tay",
        description: "A curated collection of coding interview resources to help you prepare for software engineering interviews at top tech companies.",
        url: "https://www.techinterviewhandbook.org/",
        category: "Career Guide",
    },
];


export const allResources: Resource[] = [...courses, ...opportunities, ...guides];
