import type { Resource } from '@/types';
import { additionalResources } from './seed-resources-extra';

const baseResources: Resource[] = [
  // --- Computer Science ---
  { id: 'r-1', title: 'CS50: Introduction to Computer Science', url: 'https://cs50.harvard.edu/x/', source: 'Harvard', format: 'course', field: 'Technology', topics: ['Programming', 'Algorithms', 'Web Development'], level: 'beginner', language: 'en', isFree: true, qualityScore: 98, votes: 4520, addedBy: 'team', verified: true, description: 'Harvard\'s legendary intro to CS. Covers C, Python, SQL, JavaScript, and the art of programming.', duration: '12 weeks' },
  { id: 'r-2', title: 'freeCodeCamp Full Curriculum', url: 'https://www.freecodecamp.org/', source: 'freeCodeCamp', format: 'interactive', field: 'Technology', topics: ['Web Development', 'JavaScript', 'React', 'Node.js'], level: 'beginner', language: 'en', isFree: true, qualityScore: 96, votes: 5100, addedBy: 'team', verified: true, description: 'Learn to code for free with certifications in responsive design, JavaScript, front-end libraries, and more.', duration: 'Self-paced' },
  { id: 'r-3', title: 'OSSU Computer Science Curriculum', url: 'https://github.com/ossu/computer-science', source: 'GitHub', format: 'course', field: 'Technology', topics: ['CS Fundamentals', 'Algorithms', 'Systems', 'Theory'], level: 'beginner', language: 'en', isFree: true, qualityScore: 95, votes: 3800, addedBy: 'team', verified: true, description: 'A complete self-taught education in Computer Science using free online materials from top universities.', duration: '2+ years' },
  { id: 'r-4', title: 'The Odin Project', url: 'https://www.theodinproject.com/', source: 'Other', format: 'interactive', field: 'Technology', topics: ['Full-Stack', 'Ruby', 'JavaScript', 'React'], level: 'beginner', language: 'en', isFree: true, qualityScore: 94, votes: 2900, addedBy: 'team', verified: true, description: 'A full-stack curriculum with hands-on projects. Learn by building real-world applications.', duration: 'Self-paced' },
  { id: 'r-5', title: 'MIT 6.006 Introduction to Algorithms', url: 'https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/', source: 'MIT OCW', format: 'course', field: 'Technology', topics: ['Algorithms', 'Data Structures', 'Complexity'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 97, votes: 2100, addedBy: 'team', verified: true, description: 'MIT\'s algorithms course covering sorting, searching, graph algorithms, and dynamic programming.', duration: '15 weeks' },

  // --- Data Science ---
  { id: 'r-6', title: 'fast.ai Practical Deep Learning', url: 'https://course.fast.ai/', source: 'fast.ai', format: 'course', field: 'Data Science', topics: ['Deep Learning', 'PyTorch', 'Computer Vision', 'NLP'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 97, votes: 3200, addedBy: 'team', verified: true, description: 'The best free deep learning course. Top-down approach — build models from day one with PyTorch.', duration: '7 weeks' },
  { id: 'r-7', title: 'Kaggle Learn', url: 'https://www.kaggle.com/learn', source: 'Kaggle', format: 'interactive', field: 'Data Science', topics: ['Python', 'Machine Learning', 'Pandas', 'SQL'], level: 'beginner', language: 'en', isFree: true, qualityScore: 93, votes: 2800, addedBy: 'team', verified: true, description: 'Micro-courses on Python, ML, Pandas, feature engineering, and more. Learn by doing on Kaggle.', duration: '2-4 hours each' },
  { id: 'r-8', title: 'Google ML Crash Course', url: 'https://developers.google.com/machine-learning/crash-course', source: 'Google', format: 'course', field: 'Data Science', topics: ['Machine Learning', 'TensorFlow', 'Neural Networks'], level: 'beginner', language: 'en', isFree: true, qualityScore: 92, votes: 2400, addedBy: 'team', verified: true, description: 'Google\'s fast-paced, practical introduction to machine learning with TensorFlow APIs.', duration: '15 hours' },
  { id: 'r-9', title: 'Khan Academy Statistics & Probability', url: 'https://www.khanacademy.org/math/statistics-probability', source: 'Khan Academy', format: 'course', field: 'Data Science', topics: ['Statistics', 'Probability', 'Data Analysis'], level: 'beginner', language: 'en', isFree: true, qualityScore: 95, votes: 3500, addedBy: 'team', verified: true, description: 'Master statistics and probability from scratch with practice exercises and intuitive explanations.', duration: 'Self-paced' },

  // --- Finance ---
  { id: 'r-10', title: 'Khan Academy Finance & Capital Markets', url: 'https://www.khanacademy.org/economics-finance-domain', source: 'Khan Academy', format: 'course', field: 'Finance', topics: ['Economics', 'Finance', 'Accounting'], level: 'beginner', language: 'en', isFree: true, qualityScore: 94, votes: 2600, addedBy: 'team', verified: true, description: 'Comprehensive free finance education covering micro/macroeconomics, capital markets, and accounting.', duration: 'Self-paced' },
  { id: 'r-11', title: 'Yale Financial Markets (Coursera Audit)', url: 'https://www.coursera.org/learn/financial-markets-global', source: 'Coursera', format: 'course', field: 'Finance', topics: ['Financial Markets', 'Risk Management', 'Behavioral Finance'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 96, votes: 1900, addedBy: 'team', verified: true, description: 'Robert Shiller\'s renowned course on financial markets, risk, and the real-world financial system.', duration: '7 weeks' },
  { id: 'r-12', title: 'Zerodha Varsity', url: 'https://zerodha.com/varsity/', source: 'Zerodha Varsity', format: 'text', field: 'Finance', topics: ['Stock Market', 'Trading', 'Options', 'Personal Finance'], level: 'beginner', language: 'en', isFree: true, qualityScore: 93, votes: 3100, addedBy: 'team', verified: true, description: 'India\'s best free resource for learning stock markets, trading, technical analysis, and personal finance.', duration: 'Self-paced' },

  // --- Design ---
  { id: 'r-13', title: 'Google UX Design Certificate (Audit)', url: 'https://www.coursera.org/professional-certificates/google-ux-design', source: 'Coursera', format: 'course', field: 'Design', topics: ['UX Design', 'User Research', 'Prototyping', 'Figma'], level: 'beginner', language: 'en', isFree: true, qualityScore: 94, votes: 2200, addedBy: 'team', verified: true, description: 'Google\'s UX design program. Learn research, wireframing, prototyping, and usability testing.', duration: '6 months' },
  { id: 'r-14', title: 'Figma YouTube Tutorials', url: 'https://www.youtube.com/c/Figmadesign', source: 'YouTube', format: 'video', field: 'Design', topics: ['Figma', 'UI Design', 'Design Systems'], level: 'beginner', language: 'en', isFree: true, qualityScore: 90, votes: 1800, addedBy: 'team', verified: true, description: 'Official Figma tutorials covering everything from basics to advanced prototyping techniques.', duration: 'Varies' },

  // --- Medicine ---
  { id: 'r-15', title: 'Khan Academy Health & Medicine', url: 'https://www.khanacademy.org/science/health-and-medicine', source: 'Khan Academy', format: 'course', field: 'Medicine', topics: ['Anatomy', 'Healthcare', 'Biology'], level: 'beginner', language: 'en', isFree: true, qualityScore: 95, votes: 3200, addedBy: 'team', verified: true, description: 'Comprehensive free health and medicine education covering anatomy, physiology, and healthcare systems.', duration: 'Self-paced' },

  // --- Engineering ---
  { id: 'r-17', title: 'MIT OpenCourseWare Engineering', url: 'https://ocw.mit.edu/search/?t=Engineering', source: 'MIT OCW', format: 'course', field: 'Engineering', topics: ['Mechanical', 'Electrical', 'Civil', 'Engineering'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 96, votes: 2800, addedBy: 'team', verified: true, description: 'Full MIT engineering courses across all disciplines — free lectures, notes, and assignments.', duration: 'Varies' },


  // --- Entrepreneurship ---
  { id: 'r-20', title: 'YC Startup School', url: 'https://www.startupschool.org/', source: 'Other', format: 'course', field: 'Entrepreneurship', topics: ['Startups', 'Product-Market Fit', 'Fundraising'], level: 'beginner', language: 'en', isFree: true, qualityScore: 96, votes: 2700, addedBy: 'team', verified: true, description: 'Y Combinator\'s free online program for aspiring founders. Learn from the best startup accelerator.', duration: '10 weeks' },
  { id: 'r-21', title: 'Paul Graham Essays', url: 'http://www.paulgraham.com/articles.html', source: 'Other', format: 'text', field: 'Entrepreneurship', topics: ['Startups', 'Thinking', 'Technology'], level: 'beginner', language: 'en', isFree: true, qualityScore: 95, votes: 2300, addedBy: 'team', verified: true, description: 'Legendary essays on startups, ideas, and technology from the co-founder of Y Combinator.', duration: 'Self-paced' },

  // --- Humanities ---
  { id: 'r-22', title: 'MIT OCW Literature Courses', url: 'https://ocw.mit.edu/search/?t=Literature', source: 'MIT OCW', format: 'course', field: 'Humanities', topics: ['Literature', 'Writing', 'Critical Thinking'], level: 'beginner', language: 'en', isFree: true, qualityScore: 92, votes: 1200, addedBy: 'team', verified: true, description: 'Free MIT literature and writing courses covering American literature, creative writing, and more.', duration: 'Varies' },
  { id: 'r-23', title: 'Project Gutenberg', url: 'https://www.gutenberg.org/', source: 'Project Gutenberg', format: 'book', field: 'Humanities', topics: ['Classic Literature', 'Philosophy', 'History'], level: 'beginner', language: 'en', isFree: true, qualityScore: 94, votes: 1800, addedBy: 'team', verified: true, description: 'Over 60,000 free eBooks. The world\'s largest collection of public domain literature.', duration: 'Self-paced' },

  // --- Law ---
  { id: 'r-24', title: 'NALSAR Open Courseware', url: 'https://www.nalsar.ac.in/', source: 'Other', format: 'course', field: 'Law', topics: ['Indian Law', 'Constitutional Law', 'Legal Research'], level: 'beginner', language: 'en', isFree: true, qualityScore: 85, votes: 800, addedBy: 'team', verified: true, description: 'Open courseware from one of India\'s top law schools covering constitutional and legal fundamentals.', duration: 'Self-paced' },
];

export const resources: Resource[] = [...baseResources, ...additionalResources];
