import type { Career } from '@/types';

// Modern/emerging careers to extend the existing seed-careers dataset.
export const modernCareers: Career[] = [
  {
    id: 'career-21',
    title: 'Cloud Engineer',
    slug: 'cloud-engineer',
    field: 'Technology',
    subfield: 'Cloud Infrastructure',
    description:
      'Design, deploy, and maintain scalable cloud infrastructure across AWS, Azure, and GCP. Cloud engineers build the backbone of modern apps — handling networking, security, cost optimization, and uptime.',
    shortDescription: 'Architect resilient infrastructure on AWS, Azure, GCP.',
    avgSalaryIndia: '₹10–35 LPA',
    avgSalaryGlobal: '$95K–$190K',
    demandTrend: 'rising',
    relatedCareers: ['career-16', 'career-1'],
    tags: ['cloud', 'aws', 'gcp', 'azure', 'infrastructure', 'networking'],
    icon: 'Code',
    stages: [
      { id: 's1', title: 'Fundamentals', description: 'Master networking, Linux, and IaaS concepts.', duration: '2–3 months', skills: ['Linux', 'Networking', 'Bash', 'TCP/IP'], resources: [], milestones: ['Set up a Linux home lab', 'Pass CompTIA Cloud Essentials'], order: 1 },
      { id: 's2', title: 'Pick a Cloud', description: 'Go deep on one provider — AWS is recommended.', duration: '3–4 months', skills: ['EC2', 'S3', 'IAM', 'VPC'], resources: [], milestones: ['AWS Cloud Practitioner', 'Deploy a 3-tier web app'], order: 2 },
      { id: 's3', title: 'Automation & IaC', description: 'Learn Terraform, Ansible, and CI/CD pipelines.', duration: '2–4 months', skills: ['Terraform', 'Ansible', 'GitHub Actions', 'Docker'], resources: [], milestones: ['Provision infra via Terraform', 'Build a CI/CD pipeline'], order: 3 },
      { id: 's4', title: 'Cert & Career', description: 'Get certified and apply for cloud roles.', duration: '2–3 months', skills: ['AWS SA Associate', 'Cost Optimization', 'Cloud Security'], resources: [], milestones: ['Earn AWS Solutions Architect Associate', 'Portfolio of 3 cloud projects'], order: 4 },
    ],
  },
  {
    id: 'career-22',
    title: 'Blockchain Developer',
    slug: 'blockchain-developer',
    field: 'Technology',
    subfield: 'Web3 & Decentralized Systems',
    description:
      'Build decentralized applications, smart contracts, and on-chain protocols. Blockchain engineers work on DeFi, NFTs, L2 scaling, and infrastructure across Ethereum, Solana, and beyond.',
    shortDescription: 'Build smart contracts and decentralized apps.',
    avgSalaryIndia: '₹10–40 LPA',
    avgSalaryGlobal: '$90K–$220K',
    demandTrend: 'rising',
    relatedCareers: ['career-1', 'career-5'],
    tags: ['blockchain', 'web3', 'solidity', 'ethereum', 'smart contracts', 'crypto'],
    icon: 'Code',
    stages: [
      { id: 's1', title: 'Blockchain Basics', description: 'Understand cryptography, consensus, and how blockchains work.', duration: '1–2 months', skills: ['Cryptography', 'Hash Functions', 'Consensus', 'Ethereum'], resources: [], milestones: ['Read Mastering Ethereum', 'Send your first tx'], order: 1 },
      { id: 's2', title: 'Solidity & Smart Contracts', description: 'Write, test, and deploy smart contracts.', duration: '3–4 months', skills: ['Solidity', 'Hardhat', 'Foundry', 'OpenZeppelin'], resources: [], milestones: ['Deploy an ERC-20 token', 'Build an NFT collection'], order: 2 },
      { id: 's3', title: 'Full-Stack dApps', description: 'Connect smart contracts to web frontends.', duration: '2–3 months', skills: ['Ethers.js', 'wagmi', 'Next.js', 'IPFS'], resources: [], milestones: ['Ship a full dApp', 'Win a hackathon'], order: 3 },
      { id: 's4', title: 'Audit & Scale', description: 'Learn security, audits, and L2 scaling.', duration: '2–3 months', skills: ['Smart Contract Security', 'Optimism', 'Arbitrum', 'zk-Rollups'], resources: [], milestones: ['Complete a security CTF', 'Contribute to OSS protocol'], order: 4 },
    ],
  },
  {
    id: 'career-23',
    title: 'Robotics Engineer',
    slug: 'robotics-engineer',
    field: 'Engineering',
    subfield: 'Robotics & Automation',
    description:
      'Design and program robots that perceive, move, and interact with the physical world. Robotics engineers combine mechanical, electrical, and software skills to build autonomous systems.',
    shortDescription: 'Build machines that perceive and move autonomously.',
    avgSalaryIndia: '₹8–28 LPA',
    avgSalaryGlobal: '$90K–$180K',
    demandTrend: 'rising',
    relatedCareers: ['career-14', 'career-5'],
    tags: ['robotics', 'ros', 'control systems', 'computer vision', 'embedded'],
    icon: 'Wrench',
    stages: [
      { id: 's1', title: 'Foundations', description: 'Strong math, physics, and programming base.', duration: '3–6 months', skills: ['Linear Algebra', 'Calculus', 'Python', 'C++'], resources: [], milestones: ['Build an Arduino project', 'Solve 100 robotics quizzes'], order: 1 },
      { id: 's2', title: 'ROS & Simulation', description: 'Learn the Robot Operating System.', duration: '3–4 months', skills: ['ROS 2', 'Gazebo', 'Linux', 'URDF'], resources: [], milestones: ['Simulate a turtlebot', 'Build a SLAM demo'], order: 2 },
      { id: 's3', title: 'Perception & Control', description: 'Master computer vision and control theory.', duration: '4–6 months', skills: ['OpenCV', 'PCL', 'PID', 'Kalman Filters'], resources: [], milestones: ['Detect objects in real time', 'Tune a quadcopter PID'], order: 3 },
      { id: 's4', title: 'Build & Ship', description: 'Build a real robot end-to-end.', duration: '3–6 months', skills: ['SLAM', 'Path Planning', 'Embedded C', 'Sensor Fusion'], resources: [], milestones: ['Ship an autonomous robot', 'Publish a research demo'], order: 4 },
    ],
  },
  {
    id: 'career-24',
    title: 'Game Developer',
    slug: 'game-developer',
    field: 'Technology',
    subfield: 'Game Development',
    description:
      'Create immersive games across PC, console, and mobile. Game developers combine programming, design, and storytelling to craft experiences that millions of players love.',
    shortDescription: 'Craft worlds and experiences that people play.',
    avgSalaryIndia: '₹5–22 LPA',
    avgSalaryGlobal: '$60K–$160K',
    demandTrend: 'rising',
    relatedCareers: ['career-1', 'career-3'],
    tags: ['game dev', 'unity', 'unreal', 'c#', 'gameplay'],
    icon: 'Rocket',
    stages: [
      { id: 's1', title: 'Pick an Engine', description: 'Start with Unity (C#) or Godot (GDScript).', duration: '1–2 months', skills: ['C#', 'Unity', 'Godot', '2D Math'], resources: [], milestones: ['Make your first 2D game', 'Publish to itch.io'], order: 1 },
      { id: 's2', title: 'Gameplay Programming', description: 'Master physics, state machines, and UI.', duration: '3–4 months', skills: ['Game Physics', 'State Machines', 'UI', 'Audio'], resources: [], milestones: ['Ship a polished 2D platformer'], order: 2 },
      { id: 's3', title: '3D & Shaders', description: 'Move into 3D, shaders, and graphics.', duration: '3–5 months', skills: ['3D Math', 'HLSL/GLSL', 'Lighting', 'Animation'], resources: [], milestones: ['Build a 3D vertical slice', 'Author a shader pack'], order: 3 },
      { id: 's4', title: 'Ship & Sell', description: 'Polish, market, and ship a game.', duration: '6–12 months', skills: ['Marketing', 'Steam', 'Playtesting', 'Monetization'], resources: [], milestones: ['Steam page live', 'First paying players'], order: 4 },
    ],
  },
  {
    id: 'career-25',
    title: 'Research Scientist',
    slug: 'research-scientist',
    field: 'Science',
    subfield: 'Academic & Industry Research',
    description:
      'Push the frontier of human knowledge across AI, biology, physics, climate, and more. Research scientists publish, prototype, and partner with industry to translate ideas into impact.',
    shortDescription: 'Push the frontier of human knowledge.',
    avgSalaryIndia: '₹8–30 LPA',
    avgSalaryGlobal: '$80K–$200K',
    demandTrend: 'rising',
    relatedCareers: ['career-5', 'career-2'],
    tags: ['research', 'phd', 'science', 'ai research', 'biology'],
    icon: 'Atom',
    stages: [
      { id: 's1', title: 'Undergrad Foundation', description: 'Deep mastery of your subject and math.', duration: '3–4 years', skills: ['Subject Mastery', 'Math', 'Statistics', 'Scientific Writing'], resources: [], milestones: ['Top 10% GPA', 'First lab internship'], order: 1 },
      { id: 's2', title: 'Research Experience', description: 'Join a lab, contribute, and publish.', duration: '1–2 years', skills: ['Literature Review', 'Experimental Design', 'LaTeX', 'Coding'], resources: [], milestones: ['First publication / preprint', 'Strong recommendation letters'], order: 2 },
      { id: 's3', title: 'Graduate School', description: 'PhD or research-track Masters.', duration: '4–6 years', skills: ['Original Research', 'Grant Writing', 'Mentoring', 'Peer Review'], resources: [], milestones: ['Multiple top-tier publications', 'Conference talks'], order: 3 },
      { id: 's4', title: 'Career Track', description: 'Postdoc, industry lab, or faculty position.', duration: '1–3 years', skills: ['Independent Research', 'Networking', 'Public Speaking'], resources: [], milestones: ['Land postdoc / research scientist role', 'First grant funded'], order: 4 },
    ],
  },
  {
    id: 'career-26',
    title: 'AI Engineer',
    slug: 'ai-engineer',
    field: 'Technology',
    subfield: 'Applied AI',
    description:
      'Ship production AI systems — LLM apps, vision pipelines, recommendation engines, and agents. AI engineers bridge research and engineering, working with foundation models and modern AI tooling.',
    shortDescription: 'Ship production AI products users love.',
    avgSalaryIndia: '₹15–60 LPA',
    avgSalaryGlobal: '$110K–$280K',
    demandTrend: 'rising',
    relatedCareers: ['career-5', 'career-1'],
    tags: ['ai engineer', 'llm', 'rag', 'agents', 'openai', 'gemini', 'fine-tuning'],
    icon: 'Brain',
    stages: [
      { id: 's1', title: 'AI Foundations', description: 'Python, ML basics, and how LLMs work.', duration: '2–3 months', skills: ['Python', 'PyTorch', 'Transformers', 'Prompt Engineering'], resources: [], milestones: ['Build your first chatbot', 'Read Attention Is All You Need'], order: 1 },
      { id: 's2', title: 'LLM Apps', description: 'Build with OpenAI / Gemini / open models.', duration: '2–4 months', skills: ['RAG', 'Vector DBs', 'LangChain', 'Streaming'], resources: [], milestones: ['Ship a RAG app', 'Deploy a chat product'], order: 2 },
      { id: 's3', title: 'Agents & Tooling', description: 'Build agents, evals, and AI products.', duration: '3–4 months', skills: ['Agents', 'Function Calling', 'Evals', 'Observability'], resources: [], milestones: ['Build an autonomous agent', 'Set up eval pipeline'], order: 3 },
      { id: 's4', title: 'Production AI', description: 'Latency, cost, safety, and scale.', duration: '2–4 months', skills: ['Fine-tuning', 'Quantization', 'MLOps', 'Safety'], resources: [], milestones: ['Ship to production', 'Drive cost down 50%'], order: 4 },
    ],
  },
];
