import type { Resource } from '@/types';

// Additional real, up-to-date free courses from Class Central, Coursera, edX, etc.
export const additionalResources: Resource[] = [
  // --- CS & Programming ---
  { id: 'r-25', title: 'Python for Everybody (Dr. Chuck)', url: 'https://www.py4e.com/', source: 'Coursera', format: 'course', field: 'Technology', topics: ['Python', 'Programming', 'Web Scraping'], level: 'beginner', language: 'en', isFree: true, qualityScore: 96, votes: 4100, addedBy: 'team', verified: true, description: 'The most popular Python course ever. Learn Python from scratch with real projects.', duration: '8 weeks' },
  { id: 'r-26', title: 'Web Development Bootcamp (Angela Yu)', url: 'https://www.appbrewery.co/p/web-development-course-resources', source: 'Other', format: 'course', field: 'Technology', topics: ['HTML', 'CSS', 'JavaScript', 'React', 'Node.js'], level: 'beginner', language: 'en', isFree: true, qualityScore: 95, votes: 3800, addedBy: 'team', verified: true, description: 'Complete web dev resources covering HTML, CSS, JS, React, Node.js and databases.', duration: 'Self-paced' },
  { id: 'r-27', title: 'MIT 6.0001 Intro to CS with Python', url: 'https://ocw.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/', source: 'MIT OCW', format: 'course', field: 'Technology', topics: ['Python', 'CS Fundamentals', 'Problem Solving'], level: 'beginner', language: 'en', isFree: true, qualityScore: 97, votes: 3200, addedBy: 'team', verified: true, description: 'MIT\'s intro CS course using Python. Lectures, assignments, and exams all free.', duration: '14 weeks' },
  { id: 'r-28', title: 'Full Stack Open (Helsinki)', url: 'https://fullstackopen.com/en/', source: 'Other', format: 'course', field: 'Technology', topics: ['React', 'Node.js', 'GraphQL', 'TypeScript'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 96, votes: 2900, addedBy: 'team', verified: true, description: 'University of Helsinki\'s modern full-stack course. React, Node, GraphQL, TypeScript, CI/CD.', duration: '12 weeks' },
  { id: 'r-29', title: 'Nand2Tetris (Build a Computer)', url: 'https://www.nand2tetris.org/', source: 'Coursera', format: 'course', field: 'Technology', topics: ['Computer Architecture', 'Hardware', 'Assembly', 'OS'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 98, votes: 2600, addedBy: 'team', verified: true, description: 'Build a computer from logic gates to an operating system. One of the best CS courses ever made.', duration: '12 weeks' },
  { id: 'r-30', title: 'Eloquent JavaScript (Free Book)', url: 'https://eloquentjavascript.net/', source: 'Other', format: 'book', field: 'Technology', topics: ['JavaScript', 'Programming', 'Web'], level: 'beginner', language: 'en', isFree: true, qualityScore: 94, votes: 2400, addedBy: 'team', verified: true, description: 'The best free JavaScript book. Covers fundamentals, DOM, Node.js, and advanced concepts.', duration: 'Self-paced' },
  { id: 'r-31', title: 'Git & GitHub Crash Course', url: 'https://www.youtube.com/watch?v=RGOj5yH7evk', source: 'YouTube', format: 'video', field: 'Technology', topics: ['Git', 'GitHub', 'Version Control'], level: 'beginner', language: 'en', isFree: true, qualityScore: 91, votes: 3100, addedBy: 'team', verified: true, description: 'freeCodeCamp\'s comprehensive Git tutorial. Learn branching, merging, and collaboration.', duration: '1 hour' },
  { id: 'r-32', title: 'Stanford CS229 Machine Learning', url: 'https://cs229.stanford.edu/', source: 'Stanford', format: 'course', field: 'Data Science', topics: ['Machine Learning', 'Linear Algebra', 'Statistics'], level: 'advanced', language: 'en', isFree: true, qualityScore: 98, votes: 3500, addedBy: 'team', verified: true, description: 'Andrew Ng\'s legendary Stanford ML course. Full lecture videos, notes, and problem sets.', duration: '11 weeks' },
  { id: 'r-33', title: 'Deep Learning Specialization (Audit)', url: 'https://www.coursera.org/specializations/deep-learning', source: 'Coursera', format: 'course', field: 'Data Science', topics: ['Deep Learning', 'Neural Networks', 'CNN', 'RNN'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 97, votes: 4200, addedBy: 'team', verified: true, description: 'Andrew Ng\'s deep learning courses. Free to audit — covers NNs, CNNs, RNNs, and more.', duration: '5 months' },
  { id: 'r-34', title: 'StatQuest YouTube Channel', url: 'https://www.youtube.com/c/joshstarmer', source: 'YouTube', format: 'video', field: 'Data Science', topics: ['Statistics', 'Machine Learning', 'Math'], level: 'beginner', language: 'en', isFree: true, qualityScore: 95, votes: 3800, addedBy: 'team', verified: true, description: 'The best stats channel on YouTube. Complex topics explained with animations and humor.', duration: 'Varies' },
  { id: 'r-35', title: '3Blue1Brown Linear Algebra', url: 'https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab', source: 'YouTube', format: 'video', field: 'Data Science', topics: ['Linear Algebra', 'Math', 'Visualization'], level: 'beginner', language: 'en', isFree: true, qualityScore: 99, votes: 5200, addedBy: 'team', verified: true, description: 'The most beautiful math series ever made. Understand linear algebra visually and intuitively.', duration: '3.5 hours' },
  // --- Finance & Business ---
  { id: 'r-36', title: 'MIT 15.401 Finance Theory', url: 'https://ocw.mit.edu/courses/15-401-finance-theory-i-fall-2008/', source: 'MIT OCW', format: 'course', field: 'Finance', topics: ['Finance', 'Valuation', 'Portfolio Theory'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 94, votes: 1800, addedBy: 'team', verified: true, description: 'MIT\'s finance course covering present value, portfolio theory, CAPM, and options.', duration: '15 weeks' },
  { id: 'r-37', title: 'Investopedia Academy (Free Articles)', url: 'https://www.investopedia.com/', source: 'Other', format: 'text', field: 'Finance', topics: ['Investing', 'Trading', 'Personal Finance'], level: 'beginner', language: 'en', isFree: true, qualityScore: 90, votes: 2800, addedBy: 'team', verified: true, description: 'The world\'s best free financial encyclopedia. Learn investing, trading, and money management.', duration: 'Self-paced' },
  // --- Design ---
  { id: 'r-38', title: 'Laws of UX', url: 'https://lawsofux.com/', source: 'Other', format: 'text', field: 'Design', topics: ['UX Design', 'Psychology', 'Design Principles'], level: 'beginner', language: 'en', isFree: true, qualityScore: 93, votes: 2100, addedBy: 'team', verified: true, description: 'Beautiful collection of UX design principles backed by psychology research.', duration: '1 hour' },
  { id: 'r-39', title: 'Refactoring UI (Free Chapter)', url: 'https://www.refactoringui.com/', source: 'Other', format: 'text', field: 'Design', topics: ['UI Design', 'Visual Design', 'Color'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 92, votes: 1900, addedBy: 'team', verified: true, description: 'Practical UI design tips from the creators of Tailwind CSS. Make your designs look professional.', duration: '2 hours' },
  // --- Science ---
  { id: 'r-40', title: 'MIT 8.01 Classical Mechanics', url: 'https://ocw.mit.edu/courses/8-01sc-classical-mechanics-fall-2016/', source: 'MIT OCW', format: 'course', field: 'Science', topics: ['Physics', 'Mechanics', 'JEE Prep'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 96, votes: 2200, addedBy: 'team', verified: true, description: 'MIT\'s physics course. Excellent for JEE/NEET students wanting deeper understanding.', duration: '15 weeks' },
  { id: 'r-41', title: 'Khan Academy Biology', url: 'https://www.khanacademy.org/science/biology', source: 'Khan Academy', format: 'course', field: 'Science', topics: ['Biology', 'Cell Biology', 'Genetics', 'NEET'], level: 'beginner', language: 'en', isFree: true, qualityScore: 95, votes: 3400, addedBy: 'team', verified: true, description: 'Complete biology curriculum from cells to ecology. Perfect for NEET and board exam prep.', duration: 'Self-paced' },
  { id: 'r-42', title: 'Organic Chemistry Tutor (YouTube)', url: 'https://www.youtube.com/c/TheOrganicChemistryTutor', source: 'YouTube', format: 'video', field: 'Science', topics: ['Chemistry', 'Physics', 'Math', 'JEE'], level: 'beginner', language: 'en', isFree: true, qualityScore: 94, votes: 4100, addedBy: 'team', verified: true, description: 'One of the best free channels for JEE/NEET science. Clear explanations of tough topics.', duration: 'Varies' },
  // --- Marketing ---
  { id: 'r-43', title: 'Google Digital Marketing Certificate', url: 'https://learndigital.withgoogle.com/digitalgarage', source: 'Google', format: 'course', field: 'Marketing', topics: ['Digital Marketing', 'SEO', 'Analytics', 'Ads'], level: 'beginner', language: 'en', isFree: true, qualityScore: 93, votes: 3200, addedBy: 'team', verified: true, description: 'Google\'s free digital marketing certification. Learn SEO, SEM, analytics, and social media.', duration: '40 hours' },
  { id: 'r-44', title: 'HubSpot Academy', url: 'https://academy.hubspot.com/', source: 'Other', format: 'course', field: 'Marketing', topics: ['Inbound Marketing', 'Content Marketing', 'Email'], level: 'beginner', language: 'en', isFree: true, qualityScore: 92, votes: 2400, addedBy: 'team', verified: true, description: 'Free certifications in inbound marketing, content strategy, email marketing, and sales.', duration: 'Varies' },
  // --- NPTEL / India ---
  { id: 'r-45', title: 'NPTEL Online Courses', url: 'https://nptel.ac.in/', source: 'NPTEL', format: 'course', field: 'Engineering', topics: ['Engineering', 'CS', 'Mechanical', 'Electrical'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 93, votes: 3600, addedBy: 'team', verified: true, description: 'IIT/IISc professors teaching engineering courses. Free certificates through SWAYAM.', duration: '8-12 weeks' },
  { id: 'r-46', title: 'SWAYAM Portal', url: 'https://swayam.gov.in/', source: 'Other', format: 'course', field: 'Education', topics: ['All Subjects', 'UG', 'PG', 'Engineering'], level: 'beginner', language: 'en', isFree: true, qualityScore: 90, votes: 2800, addedBy: 'team', verified: true, description: 'Indian government\'s free online learning platform. Courses from top Indian universities.', duration: 'Varies' },
  // --- Cybersecurity ---
  { id: 'r-47', title: 'TryHackMe (Free Rooms)', url: 'https://tryhackme.com/', source: 'Other', format: 'interactive', field: 'Technology', topics: ['Cybersecurity', 'Ethical Hacking', 'Linux'], level: 'beginner', language: 'en', isFree: true, qualityScore: 94, votes: 2900, addedBy: 'team', verified: true, description: 'Learn cybersecurity hands-on. Free beginner paths in networking, Linux, and web hacking.', duration: 'Self-paced' },
  { id: 'r-48', title: 'Cisco Networking Academy', url: 'https://www.netacad.com/', source: 'Other', format: 'course', field: 'Technology', topics: ['Networking', 'Cybersecurity', 'CCNA'], level: 'beginner', language: 'en', isFree: true, qualityScore: 92, votes: 2200, addedBy: 'team', verified: true, description: 'Free networking and cybersecurity courses from Cisco. Industry-recognized certifications.', duration: '70 hours' },
  // --- DevOps & Cloud ---
  { id: 'r-49', title: 'AWS Cloud Practitioner Essentials', url: 'https://explore.skillbuilder.aws/learn/course/134/aws-cloud-practitioner-essentials', source: 'Other', format: 'course', field: 'Technology', topics: ['AWS', 'Cloud Computing', 'DevOps'], level: 'beginner', language: 'en', isFree: true, qualityScore: 93, votes: 2500, addedBy: 'team', verified: true, description: 'Official AWS free course. Learn cloud fundamentals and prepare for certification.', duration: '6 hours' },
  { id: 'r-50', title: 'Docker for Beginners', url: 'https://docker-curriculum.com/', source: 'Other', format: 'text', field: 'Technology', topics: ['Docker', 'Containers', 'DevOps'], level: 'beginner', language: 'en', isFree: true, qualityScore: 91, votes: 2100, addedBy: 'team', verified: true, description: 'Best free Docker tutorial. Learn containers, images, Docker Compose step by step.', duration: '3 hours' },
  // --- Psychology ---
  { id: 'r-51', title: 'Yale Science of Well-Being', url: 'https://www.coursera.org/learn/the-science-of-well-being', source: 'Coursera', format: 'course', field: 'Humanities', topics: ['Psychology', 'Happiness', 'Mental Health'], level: 'beginner', language: 'en', isFree: true, qualityScore: 97, votes: 5500, addedBy: 'team', verified: true, description: 'Yale\'s most popular course ever. Learn the science of happiness — free to audit.', duration: '10 weeks' },
  // --- Law ---
  { id: 'r-52', title: 'Constitution of India (Bare Act)', url: 'https://legislative.gov.in/constitution-of-india/', source: 'Other', format: 'text', field: 'Law', topics: ['Constitutional Law', 'Indian Polity', 'UPSC'], level: 'beginner', language: 'en', isFree: true, qualityScore: 95, votes: 2800, addedBy: 'team', verified: true, description: 'The complete Constitution of India. Essential reading for UPSC, CLAT, and law students.', duration: 'Self-paced' },
  // --- Languages ---
  { id: 'r-53', title: 'MIT 18.06 Linear Algebra (Strang)', url: 'https://ocw.mit.edu/courses/18-06sc-linear-algebra-fall-2011/', source: 'MIT OCW', format: 'course', field: 'Data Science', topics: ['Linear Algebra', 'Mathematics', 'ML Foundation'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 98, votes: 4000, addedBy: 'team', verified: true, description: 'Gilbert Strang\'s legendary linear algebra course. Essential for ML/AI careers.', duration: '15 weeks' },
  { id: 'r-54', title: 'Harvard CS50 Web Programming', url: 'https://cs50.harvard.edu/web/', source: 'Harvard', format: 'course', field: 'Technology', topics: ['Django', 'JavaScript', 'SQL', 'React'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 96, votes: 3100, addedBy: 'team', verified: true, description: 'Harvard\'s web dev course. Django, JS, React, SQL, and software engineering principles.', duration: '12 weeks' },
  { id: 'r-55', title: 'Harvard CS50 AI', url: 'https://cs50.harvard.edu/ai/', source: 'Harvard', format: 'course', field: 'Technology', topics: ['AI', 'Search', 'Knowledge', 'Machine Learning'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 96, votes: 2800, addedBy: 'team', verified: true, description: 'Harvard\'s intro to AI. Search algorithms, knowledge representation, ML, and neural networks.', duration: '7 weeks' },

  // --- New Tech & CS ---
  { id: 'r-101', title: 'The Missing Semester of CS', url: 'https://missing.csail.mit.edu', source: 'MIT', format: 'course', field: 'Technology', topics: ['Tools', 'Shell', 'Git'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 98, votes: 3000, addedBy: 'team', verified: true, description: 'Learn the tools your CS program didn\'t teach you.', duration: 'Self-paced' },
  { id: 'r-102', title: 'roadmap.sh', url: 'https://roadmap.sh', source: 'roadmap.sh', format: 'interactive', field: 'Technology', topics: ['Roadmap', 'Career', 'Guide'], level: 'beginner', language: 'en', isFree: true, qualityScore: 99, votes: 8000, addedBy: 'team', verified: true, description: 'Role-based roadmaps, tracks and study plans to help you choose your tech path.', duration: 'Self-paced' },
  { id: 'r-103', title: 'Exercism', url: 'https://exercism.org', source: 'Exercism', format: 'interactive', field: 'Technology', topics: ['Coding', 'Practice', 'Languages'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 95, votes: 4500, addedBy: 'team', verified: true, description: 'Code practice and mentorship for 60+ languages.', duration: 'Self-paced' },
  { id: 'r-104', title: 'LeetCode (Free)', url: 'https://leetcode.com', source: 'LeetCode', format: 'interactive', field: 'Technology', topics: ['Algorithms', 'Interview', 'Data Structures'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 94, votes: 10000, addedBy: 'team', verified: true, description: 'The best platform to prepare for technical interviews.', duration: 'Self-paced' },
  { id: 'r-105', title: 'HackerRank', url: 'https://hackerrank.com', source: 'HackerRank', format: 'interactive', field: 'Technology', topics: ['Algorithms', 'Practice'], level: 'beginner', language: 'en', isFree: true, qualityScore: 90, votes: 5000, addedBy: 'team', verified: true, description: 'Practice coding, prepare for interviews, and get hired.', duration: 'Self-paced' },
  { id: 'r-106', title: 'MIT 6.824 Distributed Systems', url: 'https://pdos.csail.mit.edu/6.824', source: 'MIT', format: 'course', field: 'Technology', topics: ['Distributed Systems', 'Architecture'], level: 'advanced', language: 'en', isFree: true, qualityScore: 99, votes: 2000, addedBy: 'team', verified: true, description: 'Engineering of distributed computer systems.', duration: 'Self-paced' },
  { id: 'r-107', title: 'SICP (Book)', url: 'https://mitpress.mit.edu/sicp', source: 'MIT Press', format: 'book', field: 'Technology', topics: ['Computer Science', 'Theory'], level: 'advanced', language: 'en', isFree: true, qualityScore: 98, votes: 1500, addedBy: 'team', verified: true, description: 'Structure and Interpretation of Computer Programs.', duration: 'Self-paced' },
  { id: 'r-108', title: 'You Don\'t Know JS', url: 'https://github.com/getify/You-Dont-Know-JS', source: 'GitHub', format: 'book', field: 'Technology', topics: ['JavaScript', 'Web'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 96, votes: 5000, addedBy: 'team', verified: true, description: 'A series of books diving deep into the core mechanisms of the JavaScript language.', duration: 'Self-paced' },
  
  // --- New ML/AI ---
  { id: 'r-109', title: 'Andrej Karpathy Neural Networks Zero to Hero', url: 'https://karpathy.ai/zero-to-hero.html', source: 'Andrej Karpathy', format: 'course', field: 'Data Science', topics: ['Deep Learning', 'Neural Networks', 'AI'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 99, votes: 3500, addedBy: 'team', verified: true, description: 'A course by Andrej Karpathy on building neural networks, from scratch, in code.', duration: 'Self-paced' },
  { id: 'r-110', title: 'Hugging Face NLP Course', url: 'https://huggingface.co/learn/nlp-course', source: 'Hugging Face', format: 'course', field: 'Data Science', topics: ['NLP', 'Transformers', 'AI'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 95, votes: 2000, addedBy: 'team', verified: true, description: 'Learn about natural language processing using the Hugging Face ecosystem.', duration: 'Self-paced' },
  { id: 'r-111', title: 'MLU-Explain', url: 'https://mlu-explain.github.io', source: 'Amazon', format: 'interactive', field: 'Data Science', topics: ['Machine Learning', 'Concepts'], level: 'beginner', language: 'en', isFree: true, qualityScore: 94, votes: 1200, addedBy: 'team', verified: true, description: 'Visual explanations of core machine learning concepts.', duration: 'Self-paced' },
  { id: 'r-112', title: 'Papers With Code', url: 'https://paperswithcode.com', source: 'Papers With Code', format: 'text', field: 'Data Science', topics: ['Research', 'Machine Learning'], level: 'advanced', language: 'en', isFree: true, qualityScore: 96, votes: 3000, addedBy: 'team', verified: true, description: 'The latest in Machine Learning research with open source code.', duration: 'Self-paced' },

  // --- New Data Science ---
  { id: 'r-113', title: 'Python for Data Analysis', url: 'https://wesmckinney.com/book', source: 'Wes McKinney', format: 'book', field: 'Data Science', topics: ['Python', 'Pandas', 'Data'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 95, votes: 1800, addedBy: 'team', verified: true, description: 'Data wrangling with Pandas, NumPy, and IPython.', duration: 'Self-paced' },
  { id: 'r-114', title: 'Data Science Handbook', url: 'https://jakevdp.github.io/PythonDataScienceHandbook', source: 'Jake VanderPlas', format: 'book', field: 'Data Science', topics: ['Python', 'Data Science'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 94, votes: 2200, addedBy: 'team', verified: true, description: 'Python Data Science Handbook.', duration: 'Self-paced' },
  { id: 'r-115', title: 'SQL for Data Science', url: 'https://mode.com/sql-tutorial', source: 'Mode', format: 'course', field: 'Data Science', topics: ['SQL', 'Database'], level: 'beginner', language: 'en', isFree: true, qualityScore: 92, votes: 1500, addedBy: 'team', verified: true, description: 'Learn SQL with Mode\'s comprehensive tutorial.', duration: 'Self-paced' },
  { id: 'r-116', title: 'Seeing Theory', url: 'https://seeing-theory.brown.edu', source: 'Brown Univ', format: 'interactive', field: 'Data Science', topics: ['Statistics', 'Probability'], level: 'beginner', language: 'en', isFree: true, qualityScore: 98, votes: 1700, addedBy: 'team', verified: true, description: 'A visual introduction to probability and statistics.', duration: 'Self-paced' },

  // --- New Web Dev ---
  { id: 'r-117', title: 'MDN Web Docs', url: 'https://developer.mozilla.org', source: 'Mozilla', format: 'text', field: 'Technology', topics: ['Web', 'HTML', 'CSS', 'JS'], level: 'beginner', language: 'en', isFree: true, qualityScore: 99, votes: 12000, addedBy: 'team', verified: true, description: 'The ultimate resource for web developers.', duration: 'Self-paced' },
  { id: 'r-118', title: 'web.dev by Google', url: 'https://web.dev/learn', source: 'Google', format: 'course', field: 'Technology', topics: ['Web', 'Performance', 'CSS'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 96, votes: 2000, addedBy: 'team', verified: true, description: 'Structured learning paths for modern web development.', duration: 'Self-paced' },
  { id: 'r-119', title: 'JavaScript.info', url: 'https://javascript.info', source: 'Other', format: 'course', field: 'Technology', topics: ['JavaScript', 'Web'], level: 'beginner', language: 'en', isFree: true, qualityScore: 97, votes: 3500, addedBy: 'team', verified: true, description: 'The Modern JavaScript Tutorial.', duration: 'Self-paced' },
  { id: 'r-120', title: 'React Docs', url: 'https://react.dev', source: 'React', format: 'text', field: 'Technology', topics: ['React', 'JavaScript'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 98, votes: 5000, addedBy: 'team', verified: true, description: 'The library for web and native user interfaces.', duration: 'Self-paced' },
  { id: 'r-121', title: 'Next.js Learn', url: 'https://nextjs.org/learn', source: 'Vercel', format: 'course', field: 'Technology', topics: ['Next.js', 'React'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 96, votes: 3000, addedBy: 'team', verified: true, description: 'Learn Next.js by building a full-stack web application.', duration: 'Self-paced' },
  { id: 'r-122', title: 'CSS Tricks', url: 'https://css-tricks.com', source: 'CSS Tricks', format: 'text', field: 'Technology', topics: ['CSS', 'Web Design'], level: 'beginner', language: 'en', isFree: true, qualityScore: 95, votes: 4000, addedBy: 'team', verified: true, description: 'Tips, tricks, and techniques on using Cascading Style Sheets.', duration: 'Self-paced' },
  { id: 'r-123', title: 'Frontend Masters (Free)', url: 'https://frontendmasters.com/bootcamp', source: 'Frontend Masters', format: 'course', field: 'Technology', topics: ['Frontend', 'Web'], level: 'beginner', language: 'en', isFree: true, qualityScore: 94, votes: 1500, addedBy: 'team', verified: true, description: 'Free web development bootcamp.', duration: 'Self-paced' },

  // --- New Cybersecurity ---
  { id: 'r-124', title: 'HackTheBox (Free)', url: 'https://hackthebox.com', source: 'HackTheBox', format: 'interactive', field: 'Technology', topics: ['Cybersecurity', 'Hacking'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 96, votes: 2500, addedBy: 'team', verified: true, description: 'A massive hacking playground and infosec community.', duration: 'Self-paced' },
  { id: 'r-125', title: 'PortSwigger Web Security Academy', url: 'https://portswigger.net/web-security', source: 'PortSwigger', format: 'course', field: 'Technology', topics: ['Web Security', 'Hacking'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 98, votes: 2000, addedBy: 'team', verified: true, description: 'Free, online web security training from the creators of Burp Suite.', duration: 'Self-paced' },
  { id: 'r-126', title: 'OWASP Foundation', url: 'https://owasp.org', source: 'OWASP', format: 'text', field: 'Technology', topics: ['Security', 'Best Practices'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 97, votes: 3000, addedBy: 'team', verified: true, description: 'Open Worldwide Application Security Project.', duration: 'Self-paced' },
  { id: 'r-127', title: 'Cybrary (Free)', url: 'https://cybrary.it', source: 'Cybrary', format: 'course', field: 'Technology', topics: ['Cybersecurity', 'IT'], level: 'beginner', language: 'en', isFree: true, qualityScore: 92, votes: 1800, addedBy: 'team', verified: true, description: 'Free IT and Cybersecurity training.', duration: 'Self-paced' },
  { id: 'r-128', title: 'CTF101', url: 'https://ctf101.org', source: 'CTF101', format: 'text', field: 'Technology', topics: ['CTF', 'Hacking'], level: 'beginner', language: 'en', isFree: true, qualityScore: 91, votes: 1000, addedBy: 'team', verified: true, description: 'An introduction to Capture The Flag competitions.', duration: 'Self-paced' },

  // --- New Design ---
  { id: 'r-129', title: 'Figma Official Learn', url: 'https://help.figma.com/hc/en-us/categories/360002051613', source: 'Figma', format: 'course', field: 'Design', topics: ['Figma', 'UI Design'], level: 'beginner', language: 'en', isFree: true, qualityScore: 95, votes: 2500, addedBy: 'team', verified: true, description: 'Learn how to use Figma directly from the creators.', duration: 'Self-paced' },
  { id: 'r-130', title: 'Shift Nudge (Free resources)', url: 'https://shiftnudge.com', source: 'Shift Nudge', format: 'course', field: 'Design', topics: ['UI Design', 'Typography'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 94, votes: 1200, addedBy: 'team', verified: true, description: 'Free resources from the popular UI design course.', duration: 'Self-paced' },
  { id: 'r-131', title: 'Awwwards', url: 'https://awwwards.com', source: 'Awwwards', format: 'text', field: 'Design', topics: ['Inspiration', 'Web Design'], level: 'advanced', language: 'en', isFree: true, qualityScore: 97, votes: 3000, addedBy: 'team', verified: true, description: 'Website awards recognizing the talent and effort of the best web designers.', duration: 'Self-paced' },
  { id: 'r-132', title: 'Nielsen Norman Group', url: 'https://nngroup.com/articles', source: 'NN/g', format: 'text', field: 'Design', topics: ['UX Research', 'Usability'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 98, votes: 4000, addedBy: 'team', verified: true, description: 'World Leaders in Research-Based User Experience.', duration: 'Self-paced' },

  // --- New Finance & Business ---
  { id: 'r-133', title: 'CFA Institute Free Resources', url: 'https://cfainstitute.org/en/membership/professional-development/refresher-readings', source: 'CFA Institute', format: 'text', field: 'Finance', topics: ['Finance', 'Investment'], level: 'advanced', language: 'en', isFree: true, qualityScore: 96, votes: 1000, addedBy: 'team', verified: true, description: 'Refresher readings and free materials from CFA Institute.', duration: 'Self-paced' },
  { id: 'r-134', title: 'Corporate Finance Institute (Free)', url: 'https://corporatefinanceinstitute.com/resources/free', source: 'CFI', format: 'course', field: 'Finance', topics: ['Corporate Finance', 'Accounting'], level: 'beginner', language: 'en', isFree: true, qualityScore: 94, votes: 2000, addedBy: 'team', verified: true, description: 'Free corporate finance courses and resources.', duration: 'Self-paced' },
  { id: 'r-135', title: 'getAbstract (Free Tier)', url: 'https://getabstract.com', source: 'getAbstract', format: 'text', field: 'Business', topics: ['Business', 'Summaries'], level: 'beginner', language: 'en', isFree: true, qualityScore: 91, votes: 800, addedBy: 'team', verified: true, description: 'Compressed knowledge from business books.', duration: 'Self-paced' },
  { id: 'r-136', title: 'MIT Sloan Management Review', url: 'https://sloanreview.mit.edu', source: 'MIT', format: 'text', field: 'Business', topics: ['Management', 'Business'], level: 'advanced', language: 'en', isFree: true, qualityScore: 95, votes: 1500, addedBy: 'team', verified: true, description: 'Insights for business leaders.', duration: 'Self-paced' },
  { id: 'r-137', title: 'Stanford Social Innovation Review', url: 'https://ssir.org', source: 'Stanford', format: 'text', field: 'Business', topics: ['Social Innovation', 'Business'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 94, votes: 1000, addedBy: 'team', verified: true, description: 'Informing and inspiring leaders of social change.', duration: 'Self-paced' },
  { id: 'r-138', title: 'No CS Degree', url: 'https://www.nocsdegree.com', source: 'No CS Degree', format: 'text', field: 'Business', topics: ['Career', 'Interviews'], level: 'beginner', language: 'en', isFree: true, qualityScore: 90, votes: 1200, addedBy: 'team', verified: true, description: 'Interviews with self-taught developers and bootcamp grads.', duration: 'Self-paced' },

  // --- New Math ---
  { id: 'r-139', title: 'MIT 18.01 Single Variable Calculus', url: 'https://ocw.mit.edu/courses/18-01sc-single-variable-calculus-fall-2010', source: 'MIT OCW', format: 'course', field: 'Technology', topics: ['Calculus', 'Math'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 97, votes: 2500, addedBy: 'team', verified: true, description: 'MIT\'s foundational calculus course.', duration: 'Self-paced' },
  { id: 'r-140', title: 'Paul\'s Online Math Notes', url: 'https://tutorial.math.lamar.edu', source: 'Lamar University', format: 'text', field: 'Technology', topics: ['Math', 'Calculus', 'Algebra'], level: 'beginner', language: 'en', isFree: true, qualityScore: 98, votes: 4000, addedBy: 'team', verified: true, description: 'Comprehensive, free math notes and tutorials.', duration: 'Self-paced' },
  { id: 'r-141', title: 'Art of Problem Solving', url: 'https://artofproblemsolving.com/alcumus', source: 'AoPS', format: 'interactive', field: 'Technology', topics: ['Math', 'Problem Solving'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 96, votes: 2000, addedBy: 'team', verified: true, description: 'Online learning system for gifted math students.', duration: 'Self-paced' },
  { id: 'r-142', title: 'Brilliant.org (Free)', url: 'https://brilliant.org', source: 'Brilliant', format: 'interactive', field: 'Technology', topics: ['Math', 'Science', 'CS'], level: 'beginner', language: 'en', isFree: true, qualityScore: 95, votes: 3000, addedBy: 'team', verified: true, description: 'Interactive learning for math and science.', duration: 'Self-paced' },

  // --- New Productivity ---
  { id: 'r-143', title: 'Paul Graham\'s Writing Essays', url: 'https://paulgraham.com/writing44.html', source: 'Paul Graham', format: 'text', field: 'Humanities', topics: ['Writing', 'Communication'], level: 'beginner', language: 'en', isFree: true, qualityScore: 96, votes: 1500, addedBy: 'team', verified: true, description: 'Essays on how to write well.', duration: 'Self-paced' },
  { id: 'r-144', title: 'Shape Up by Basecamp', url: 'https://basecamp.com/shapeup', source: 'Basecamp', format: 'book', field: 'Business', topics: ['Productivity', 'Product Management'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 95, votes: 2200, addedBy: 'team', verified: true, description: 'Stop Running in Circles and Ship Work that Matters.', duration: 'Self-paced' },
  { id: 'r-145', title: 'Notion Templates', url: 'https://notion.so/templates', source: 'Notion', format: 'interactive', field: 'Productivity', topics: ['Organization', 'Tools'], level: 'beginner', language: 'en', isFree: true, qualityScore: 93, votes: 4000, addedBy: 'team', verified: true, description: 'Free templates for personal and professional organization.', duration: 'Self-paced' },

  // --- Coverage Audit Gap Fillers ---
  { id: 'r-146', title: 'SQLBolt', url: 'https://sqlbolt.com/', source: 'SQLBolt', format: 'interactive', field: 'Technology', topics: ['SQL', 'Database', 'Data Analyst'], level: 'beginner', language: 'en', isFree: true, qualityScore: 98, votes: 5500, addedBy: 'team', verified: true, description: 'Learn SQL with simple, interactive exercises. The absolute best way to learn SQL from scratch.', duration: 'Self-paced' },
  { id: 'r-147', title: 'Pro Git Book', url: 'https://git-scm.com/book/en/v2', source: 'Git', format: 'book', field: 'Technology', topics: ['Git', 'Version Control', 'DevOps'], level: 'beginner', language: 'en', isFree: true, qualityScore: 97, votes: 4200, addedBy: 'team', verified: true, description: 'The official, comprehensive book on Git. Everything you need to know about version control.', duration: 'Self-paced' },
  { id: 'r-148', title: 'Linux Journey', url: 'https://linuxjourney.com/', source: 'Other', format: 'interactive', field: 'Technology', topics: ['Linux', 'DevOps', 'Command Line'], level: 'beginner', language: 'en', isFree: true, qualityScore: 96, votes: 3800, addedBy: 'team', verified: true, description: 'Learn the ways of Linux. Interactive text tutorials covering command line, text manipulation, and networking.', duration: 'Self-paced' },
  { id: 'r-149', title: 'Node.js Official Documentation', url: 'https://nodejs.org/en/docs/', source: 'Node.js', format: 'text', field: 'Technology', topics: ['Node.js', 'Backend', 'JavaScript'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 95, votes: 3100, addedBy: 'team', verified: true, description: 'The official Node.js documentation and learning guides. The authoritative source for backend JS.', duration: 'Self-paced' },
  { id: 'r-150', title: 'Flutter Official Documentation', url: 'https://docs.flutter.dev/', source: 'Google', format: 'text', field: 'Technology', topics: ['Flutter', 'Mobile Development', 'Dart'], level: 'beginner', language: 'en', isFree: true, qualityScore: 96, votes: 2900, addedBy: 'team', verified: true, description: 'Build apps for any screen. The official docs are packed with codelabs, recipes, and videos.', duration: 'Self-paced' },
  { id: 'r-151', title: 'Android Basics in Kotlin', url: 'https://developer.android.com/courses/android-basics-kotlin/course', source: 'Google', format: 'course', field: 'Technology', topics: ['Android', 'Mobile Development', 'Kotlin'], level: 'beginner', language: 'en', isFree: true, qualityScore: 95, votes: 3400, addedBy: 'team', verified: true, description: 'Google\'s official Android development course for complete beginners using Kotlin.', duration: 'Self-paced' },
  { id: 'r-152', title: 'Google Data Analytics Certificate (Audit)', url: 'https://www.coursera.org/professional-certificates/google-data-analytics', source: 'Coursera', format: 'course', field: 'Data Science', topics: ['Data Analyst', 'SQL', 'R', 'Tableau'], level: 'beginner', language: 'en', isFree: true, qualityScore: 96, votes: 5200, addedBy: 'team', verified: true, description: 'Google\'s massive Data Analytics program. Learn data cleaning, SQL, R programming, and data visualization.', duration: '6 months' },
  { id: 'r-153', title: 'Product School Free Resources', url: 'https://productschool.com/free-resources', source: 'Product School', format: 'text', field: 'Business', topics: ['Product Manager', 'Product Management'], level: 'beginner', language: 'en', isFree: true, qualityScore: 93, votes: 2100, addedBy: 'team', verified: true, description: 'Free books, templates, and podcasts from the world\'s largest Product Management community.', duration: 'Self-paced' },

  // --- P1 Launch Gaps: Practice & Projects ---
  { id: 'r-154', title: 'Learn Git Branching', url: 'https://learngitbranching.js.org/', source: 'Other', format: 'interactive', field: 'Technology', topics: ['Git', 'Version Control', 'Practice'], level: 'beginner', language: 'en', isFree: true, qualityScore: 99, votes: 8900, addedBy: 'team', verified: true, description: 'The most visual and interactive way to learn Git on the web. Practice branching, merging, and rebasing safely.', duration: 'Self-paced' },
  { id: 'r-155', title: 'CodingBat Java Practice', url: 'https://codingbat.com/java', source: 'CodingBat', format: 'interactive', field: 'Technology', topics: ['Java', 'Programming', 'Practice'], level: 'beginner', language: 'en', isFree: true, qualityScore: 95, votes: 4100, addedBy: 'team', verified: true, description: 'Live coding problems to build coding skill in Java. Created by Nick Parlante (Stanford). The ultimate Java practice tool.', duration: 'Self-paced' },
  { id: 'r-156', title: '8 Week SQL Challenge', url: 'https://8weeksqlchallenge.com/', source: 'Data With Danny', format: 'interactive', field: 'Data Science', topics: ['SQL', 'Data Science', 'Projects'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 97, votes: 3500, addedBy: 'team', verified: true, description: '8 real-world SQL case studies and projects to build your portfolio and practice complex queries.', duration: 'Self-paced' },
  { id: 'r-157', title: 'Exercism Python Track', url: 'https://exercism.org/tracks/python', source: 'Exercism', format: 'interactive', field: 'Data Science', topics: ['Python', 'Practice', 'Mentorship'], level: 'beginner', language: 'en', isFree: true, qualityScore: 96, votes: 6200, addedBy: 'team', verified: true, description: '130+ Python coding exercises with automated analysis and free human mentoring.', duration: 'Self-paced' },
  { id: 'r-158', title: 'Build Your Own Botnet/Database/OS (Python)', url: 'https://github.com/codecrafters-io/build-your-own-x#build-your-own-bot', source: 'GitHub', format: 'interactive', field: 'Technology', topics: ['Python', 'Projects', 'Systems'], level: 'advanced', language: 'en', isFree: true, qualityScore: 98, votes: 12000, addedBy: 'team', verified: true, description: 'Advanced Python projects. Build redis, a web server, or a database from scratch in Python.', duration: 'Self-paced' },

  // --- Final Coverage Sprint: Docs, Projects, Cloud, DevOps ---
  { id: 'r-159', title: 'Official Java Documentation', url: 'https://docs.oracle.com/en/java/', source: 'Oracle', format: 'text', field: 'Technology', topics: ['Java', 'Reference'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 100, votes: 1500, addedBy: 'team', verified: true, description: 'The absolute source of truth for Java. Official documentation, API references, and tutorials.', duration: 'Self-paced' },
  { id: 'r-160', title: 'Java Project Ideas Collection', url: 'https://github.com/karan/Projects', source: 'GitHub', format: 'text', field: 'Technology', topics: ['Java', 'Projects'], level: 'beginner', language: 'en', isFree: true, qualityScore: 92, votes: 45000, addedBy: 'team', verified: true, description: 'A massive list of practical projects that anyone can solve in any programming language, including Java.', duration: 'Self-paced' },
  { id: 'r-161', title: 'PostgreSQL Official Documentation', url: 'https://www.postgresql.org/docs/', source: 'PostgreSQL', format: 'text', field: 'Data Science', topics: ['SQL', 'Database', 'Reference'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 100, votes: 2000, addedBy: 'team', verified: true, description: 'The official docs for the world\'s most advanced open source relational database.', duration: 'Self-paced' },
  { id: 'r-162', title: 'Docker Official Documentation', url: 'https://docs.docker.com/', source: 'Docker', format: 'text', field: 'Technology', topics: ['DevOps', 'Docker', 'Reference'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 100, votes: 3100, addedBy: 'team', verified: true, description: 'Official manuals and documentation for building, shipping, and running containers.', duration: 'Self-paced' },
  { id: 'r-163', title: 'Kubernetes Basics Interactive Tutorial', url: 'https://kubernetes.io/docs/tutorials/kubernetes-basics/', source: 'Kubernetes', format: 'interactive', field: 'Technology', topics: ['DevOps', 'Kubernetes', 'Practice'], level: 'beginner', language: 'en', isFree: true, qualityScore: 98, votes: 4200, addedBy: 'team', verified: true, description: 'Learn Kubernetes basics directly in your browser with the official interactive tutorials.', duration: 'Self-paced' },
  { id: 'r-164', title: 'AWS Hands-on Labs', url: 'https://aws.amazon.com/training/hands-on/', source: 'Amazon', format: 'interactive', field: 'Technology', topics: ['Cloud', 'AWS', 'Practice'], level: 'beginner', language: 'en', isFree: true, qualityScore: 95, votes: 5500, addedBy: 'team', verified: true, description: 'Step-by-step tutorials to launch your first application on AWS. Free tier practice.', duration: 'Self-paced' },
  { id: 'r-165', title: 'DevOps Exercises & Interview Questions', url: 'https://github.com/bregman-arie/devops-exercises', source: 'GitHub', format: 'text', field: 'Technology', topics: ['DevOps', 'Cloud', 'Projects', 'Practice'], level: 'advanced', language: 'en', isFree: true, qualityScore: 96, votes: 65000, addedBy: 'team', verified: true, description: 'Massive open-source repository of DevOps exercises, interview questions, and project scenarios.', duration: 'Self-paced' },
  { id: 'r-166', title: 'Flutter Cookbook (Practice & Patterns)', url: 'https://docs.flutter.dev/cookbook', source: 'Google', format: 'interactive', field: 'Technology', topics: ['Flutter', 'Mobile Development', 'Practice'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 99, votes: 2300, addedBy: 'team', verified: true, description: 'Recipes that demonstrate how to solve common problems while writing Flutter apps.', duration: 'Self-paced' },
  { id: 'r-167', title: 'Android Codelabs (Practice)', url: 'https://developer.android.com/courses/android-basics-compose/course', source: 'Google', format: 'interactive', field: 'Technology', topics: ['Android', 'Mobile Development', 'Practice'], level: 'beginner', language: 'en', isFree: true, qualityScore: 97, votes: 4100, addedBy: 'team', verified: true, description: 'Google\'s official interactive coding challenges to build Android apps using Jetpack Compose.', duration: 'Self-paced' },
];

