import type { Scholarship } from '@/types';

export const scholarships: Scholarship[] = [
  {
    id: 'sch-1',
    name: 'Prime Minister\'s Scholarship Scheme (PMSS)',
    provider: 'Ministry of Defence, India',
    country: 'India',
    type: 'government',
    amount: '₹2,500–3,000/month',
    deadline: 'October 2025',
    eligibility: ['Wards of ex-servicemen', 'UG/Professional courses', 'Minimum 60% in qualifying exam'],
    applyUrl: 'https://scholarships.gov.in/',
    fields: ['All Fields'],
    isActive: true,
    description: 'Scholarship for dependent wards and widows of ex-servicemen for professional and technical education.',
  },
  {
    id: 'sch-2',
    name: 'INSPIRE Scholarship',
    provider: 'Department of Science & Technology, India',
    country: 'India',
    type: 'merit',
    amount: '₹80,000/year',
    deadline: 'November 2025',
    eligibility: ['Top 1% in Class 12 board exams', 'Pursuing BSc/BS/Int. MSc in Natural Sciences'],
    applyUrl: 'https://online-inspire.gov.in/',
    fields: ['Science'],
    isActive: true,
    description: 'Scholarship for Higher Education (SHE) to attract meritorious students to pursue science courses.',
  },
  {
    id: 'sch-3',
    name: 'National Scholarship Portal (NSP) — Post-Matric',
    provider: 'Government of India',
    country: 'India',
    type: 'need',
    amount: 'Varies by category',
    deadline: 'December 2025',
    eligibility: ['SC/ST/OBC/Minority students', 'Family income criteria', 'Post-matric education'],
    applyUrl: 'https://scholarships.gov.in/',
    fields: ['All Fields'],
    isActive: true,
    description: 'Central government scholarships for post-matric students from SC, ST, OBC, and minority communities.',
  },
  {
    id: 'sch-4',
    name: 'Fulbright-Nehru Fellowship',
    provider: 'USIEF',
    country: 'Global',
    type: 'merit',
    amount: 'Full funding (tuition + living)',
    deadline: 'June 2025',
    eligibility: ['Indian citizens', 'Master\'s or PhD in US', 'Strong academic record'],
    applyUrl: 'https://www.usief.org.in/',
    fields: ['All Fields'],
    isActive: true,
    description: 'Prestigious fellowship for Indian students to pursue master\'s or doctoral studies in the United States.',
  },
  {
    id: 'sch-5',
    name: 'Rhodes Scholarship',
    provider: 'Rhodes Trust',
    country: 'Global',
    type: 'merit',
    amount: 'Full funding at Oxford',
    deadline: 'July 2025',
    eligibility: ['Age 19–25', 'Completed bachelor\'s degree', 'Leadership + academic excellence'],
    applyUrl: 'https://www.rhodeshouse.ox.ac.uk/',
    fields: ['All Fields'],
    isActive: true,
    description: 'The world\'s oldest and most prestigious international scholarship, offering postgraduate study at Oxford.',
  },
  {
    id: 'sch-6',
    name: 'Chevening Scholarship',
    provider: 'UK Government',
    country: 'Global',
    type: 'merit',
    amount: 'Full funding (1-year Master\'s in UK)',
    deadline: 'November 2025',
    eligibility: ['2+ years work experience', 'Return to home country', 'Leadership potential'],
    applyUrl: 'https://www.chevening.org/',
    fields: ['All Fields'],
    isActive: true,
    description: 'UK government scholarship for future leaders to study a one-year master\'s degree in the United Kingdom.',
  },
  {
    id: 'sch-7',
    name: 'Commonwealth Scholarship',
    provider: 'Commonwealth Scholarship Commission',
    country: 'Global',
    type: 'merit',
    amount: 'Full funding (Master\'s/PhD in UK)',
    deadline: 'December 2025',
    eligibility: ['Commonwealth country citizen', 'Strong academic record', 'Development impact'],
    applyUrl: 'https://cscuk.fcdo.gov.uk/',
    fields: ['All Fields'],
    isActive: true,
    description: 'Scholarships for students from Commonwealth countries to study at UK universities.',
  },
  {
    id: 'sch-8',
    name: 'DAAD Scholarship',
    provider: 'German Academic Exchange Service',
    country: 'Global',
    type: 'merit',
    amount: '€861–1,200/month + travel',
    deadline: 'October 2025',
    eligibility: ['Completed bachelor\'s', 'Relevant work experience for some programs'],
    applyUrl: 'https://www.daad.de/en/',
    fields: ['All Fields'],
    isActive: true,
    description: 'Germany\'s largest funding organization for international academic exchange and study programs.',
  },
  {
    id: 'sch-9',
    name: 'Erasmus Mundus Joint Masters',
    provider: 'European Union',
    country: 'Global',
    type: 'merit',
    amount: 'Full tuition + €1,400/month',
    deadline: 'January 2026',
    eligibility: ['Bachelor\'s degree', 'International students welcome', 'Program-specific criteria'],
    applyUrl: 'https://erasmus-plus.ec.europa.eu/',
    fields: ['All Fields'],
    isActive: true,
    description: 'EU-funded scholarships for international joint master\'s programmes across multiple European universities.',
  },
  {
    id: 'sch-10',
    name: 'Kishore Vaigyanik Protsahan Yojana (KVPY)',
    provider: 'DST, India',
    country: 'India',
    type: 'merit',
    amount: '₹5,000–7,000/month + contingency',
    deadline: 'August 2025',
    eligibility: ['Class 11 to 1st year BSc', 'Interest in basic sciences', 'Indian citizens'],
    applyUrl: 'https://kvpy.iisc.ac.in/',
    fields: ['Science'],
    isActive: true,
    description: 'Fellowship to encourage students to take up research careers in basic sciences. Funded by DST.',
  },
  {
    id: 'sch-11',
    name: 'Aditya Birla Scholarship',
    provider: 'Aditya Birla Group',
    country: 'India',
    type: 'merit',
    amount: '₹1,65,000/year for 3 years',
    deadline: 'August 2025',
    eligibility: ['Students at IITs, IIMs, BITS, XLRI, Law schools', 'Top academic performance'],
    applyUrl: 'https://www.adityabirlascholars.net/',
    fields: ['Technology', 'Finance', 'Law'],
    isActive: true,
    description: 'Merit-based scholarship for students at premier Indian institutions including IITs, IIMs, and top law schools.',
  },
  {
    id: 'sch-12',
    name: 'Google Generation Scholarship',
    provider: 'Google',
    country: 'Global',
    type: 'field-specific',
    amount: '$10,000 (or equivalent)',
    deadline: 'December 2025',
    eligibility: ['Underrepresented group in tech', 'Pursuing CS/related degree', 'Strong academics'],
    applyUrl: 'https://buildyourfuture.withgoogle.com/scholarships',
    fields: ['Technology', 'Data Science'],
    isActive: true,
    description: 'Google scholarship for students from underrepresented groups pursuing degrees in computer science or related fields.',
  },
];
