import type { Resource } from '@/types';

export const resources: Resource[] = [
  // --- PYTHON ---
  {
    id: 'p1',
    title: 'Python for Everybody',
    url: 'https://www.freecodecamp.org/learn/scientific-computing-with-python/',
    source: 'freeCodeCamp',
    format: 'COURSE',
    field: 'Technology',
    topics: ['Python', 'Backend', 'Data Science'],
    level: 'beginner',
    language: 'en',
    isFree: true,
    qualityScore: 98,
    votes: 5000,
    addedBy: 'team',
    verified: true,
    description: 'The absolute best starting point for Python.',
    duration: 'Self-paced',
    whyRecommended: 'The gold standard introductory course. Teaches programming logic without getting bogged down in syntax.',
    whyChosenOverAlternatives: [
      'Chosen over generic video lists due to structured lesson sequence',
      'Provides practical coding assignments right inside the browser',
      '100% free with no commercial upsell or hidden paywalls'
    ],
    resourceTypeBadge: 'Community Curriculum',
    limitations: 'Does not cover advanced algorithms or design patterns, focusing strictly on basic syntax.',
    alternativeResource: {
      title: 'MIT 6.0001 Intro to CS with Python',
      url: 'https://ocw.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/',
      reason: 'For learners wanting a more mathematically rigorous computer science approach.'
    },
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true,
      notes: 'Verified active. Redirects to freeCodeCamp scientific computing playlist.',
      linkChecked: '2026-06-18',
      humanReviewed: '2026-06-18',
      reviewDue: '2026-12-18'
    }
  },
  {
    id: 'p2',
    title: 'Python Official Documentation',
    url: 'https://docs.python.org/3/',
    source: 'Official Docs',
    format: 'DOCUMENTATION',
    field: 'Technology',
    topics: ['Python'],
    level: 'beginner',
    language: 'en',
    isFree: true,
    qualityScore: 95,
    votes: 2000,
    addedBy: 'team',
    verified: true,
    description: 'The official Python docs. Essential reading for syntax and standard library.',
    duration: 'Reference',
    whyRecommended: 'Official language reference. Crucial for understanding pythonic conventions and built-in modules.',
    whyChosenOverAlternatives: [
      'Direct primary source straight from the core development team',
      'Most up-to-date syntax reference available anywhere online',
      'Completely free of advertising or promotional content'
    ],
    resourceTypeBadge: 'Official Documentation',
    limitations: 'Extremely dry and technical; not written as a tutorial for absolute beginners.',
    alternativeResource: {
      title: 'Python for Everybody',
      url: 'https://www.freecodecamp.org/learn/scientific-computing-with-python/',
      reason: 'Provides a video-guided sandbox learning style instead of plain specifications.'
    },
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true,
      notes: 'Monitored continuously. Always active.',
      linkChecked: '2026-06-18',
      humanReviewed: '2026-06-18',
      reviewDue: '2026-12-18'
    }
  },
  {
    id: 'p3',
    title: 'Exercism Python Track',
    url: 'https://exercism.org/tracks/python',
    source: 'Other',
    format: 'PRACTICE',
    field: 'Technology',
    topics: ['Python', 'Practice'],
    level: 'beginner',
    language: 'en',
    isFree: true,
    qualityScore: 99,
    votes: 3000,
    addedBy: 'team',
    verified: true,
    description: 'Interactive Python coding exercises with mentor feedback.',
    duration: 'Self-paced',
    whyRecommended: 'Hands-on practice. Helps solidify syntax and features human code reviews for every submit.',
    whyChosenOverAlternatives: [
      'Includes human mentor code feedback at no cost',
      'Focuses on test-driven development style workflows',
      'Zero advertising and entirely open-source platform'
    ],
    resourceTypeBadge: 'Interactive Practice',
    limitations: 'Requires local environment setup or terminal familiarity to download tasks, which can be an onboarding hurdle.',
    alternativeResource: {
      title: 'SQLBolt',
      url: 'https://sqlbolt.com/',
      reason: 'For in-browser interactive practice if local development setups are failing.'
    },
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true,
      notes: 'Active. Mentoring system is completely free.',
      linkChecked: '2026-06-18',
      humanReviewed: '2026-06-18',
      reviewDue: '2026-12-18'
    }
  },
  {
    id: 'p4',
    title: 'Build a Discord Bot in Python',
    url: 'https://www.freecodecamp.org/news/create-a-discord-bot-with-python/',
    source: 'freeCodeCamp',
    format: 'PROJECT',
    field: 'Technology',
    topics: ['Python', 'Projects'],
    level: 'intermediate',
    language: 'en',
    isFree: true,
    qualityScore: 92,
    votes: 1500,
    addedBy: 'team',
    verified: true,
    description: 'Build a working Discord bot using Python and host it.',
    duration: '5 hours',
    whyRecommended: 'Practical utility project. Teaches asynchronous APIs and deployment.',
    resourceTypeBadge: 'Project Based',
    limitations: 'Requires Discord developer account and handling api key tokens safely.',
    alternativeResource: {
      title: 'Build Your Own X',
      url: 'https://github.com/codecrafters-io/build-your-own-x',
      reason: 'For command line tool development instead of third-party platform apps.'
    },
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true,
      notes: 'Articles checked; code remains compatible with discord.py library standards.'
    }
  },

  // --- JAVA ---
  {
    id: 'j1',
    title: 'Java Programming Masterclass',
    url: 'https://mooc.fi/en/',
    source: 'Other',
    format: 'COURSE',
    field: 'Technology',
    topics: ['Java', 'Backend'],
    level: 'beginner',
    language: 'en',
    isFree: true,
    qualityScore: 97,
    votes: 4000,
    addedBy: 'team',
    verified: true,
    description: 'University of Helsinki\'s legendary free Java MOOC.',
    duration: 'Self-paced',
    whyRecommended: 'Legendary University MOOC. Outpaces paid bootcamps in rigorous testing and OOP design principles.',
    resourceTypeBadge: 'University Curriculum',
    limitations: 'Text and coding assignment heavy. Requires installing a NetBeans editor plugin to submit exercises.',
    alternativeResource: {
      title: 'CodingBat Java Practice',
      url: 'https://codingbat.com/java',
      reason: 'If you want immediate browser practice without installing local development applications.'
    },
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true,
      notes: 'Active. Runs continuously under University of Helsinki Computer Science.'
    }
  },
  {
    id: 'j2',
    title: 'Java Official Docs',
    url: 'https://docs.oracle.com/en/java/',
    source: 'Official Docs',
    format: 'DOCUMENTATION',
    field: 'Technology',
    topics: ['Java'],
    level: 'beginner',
    language: 'en',
    isFree: true,
    qualityScore: 90,
    votes: 1000,
    addedBy: 'team',
    verified: true,
    description: 'Official Java documentation by Oracle.',
    duration: 'Reference',
    whyRecommended: 'Official language reference by Oracle. Crucial for enterprise specifications.',
    resourceTypeBadge: 'Official Documentation',
    limitations: 'Highly verbose documentation. Hard to navigate for non-enterprise developers.',
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true,
      notes: 'Active. Checked Oracle reference indexes.'
    }
  },
  {
    id: 'j3',
    title: 'Exercism Java Track',
    url: 'https://exercism.org/tracks/java',
    source: 'Other',
    format: 'PRACTICE',
    field: 'Technology',
    topics: ['Java', 'Practice'],
    level: 'beginner',
    language: 'en',
    isFree: true,
    qualityScore: 95,
    votes: 2500,
    addedBy: 'team',
    verified: true,
    description: 'Interactive Java exercises.',
    duration: 'Self-paced',
    whyRecommended: 'Great interactive feedback loops for test-driven Java learning.',
    resourceTypeBadge: 'Interactive Practice',
    limitations: 'Requires setting up local Java compiler environment (JDK) first.',
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true
    }
  },
  {
    id: 'j4',
    title: 'Spring Boot Project Tutorial',
    url: 'https://spring.io/guides/gs/rest-service/',
    source: 'Official Docs',
    format: 'PROJECT',
    field: 'Technology',
    topics: ['Java', 'Projects', 'Backend'],
    level: 'intermediate',
    language: 'en',
    isFree: true,
    qualityScore: 94,
    votes: 1200,
    addedBy: 'team',
    verified: true,
    description: 'Build a RESTful Web Service with Spring Boot.',
    duration: '4 hours',
    whyRecommended: 'The official introduction to building Rest endpoints with Spring Boot frameworks.',
    resourceTypeBadge: 'Project Based',
    limitations: 'Assumes strong pre-existing understanding of Java OOP classes.',
    alternativeResource: {
      title: 'Full Stack Open (Helsinki)',
      url: 'https://fullstackopen.com/en/',
      reason: 'If you want to study Node.js REST design instead of Java Spring Boot.'
    },
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true
    }
  },

  // --- JAVASCRIPT & FRONTEND ---
  {
    id: 'js1',
    title: 'freeCodeCamp JavaScript Certification',
    url: 'https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/',
    source: 'freeCodeCamp',
    format: 'COURSE',
    field: 'Technology',
    topics: ['JavaScript', 'Frontend', 'Backend'],
    level: 'beginner',
    language: 'en',
    isFree: true,
    qualityScore: 99,
    votes: 6000,
    addedBy: 'team',
    verified: true,
    description: 'Comprehensive JS curriculum.',
    duration: 'Self-paced',
    whyRecommended: 'Best structured curriculum for algorithms and data structures. Hand-coded testing.',
    resourceTypeBadge: 'Community Recommended',
    limitations: 'Can feel repetitive with browser sandbox tasks. Lacks local editor configurations training.',
    alternativeResource: {
      title: 'Eloquent JavaScript (Free Book)',
      url: 'https://eloquentjavascript.net/',
      reason: 'For learners who prefer reading conceptual literature over coding challenges.'
    },
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true
    }
  },
  {
    id: 'js2',
    title: 'MDN Web Docs - JavaScript',
    url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
    source: 'Official Docs',
    format: 'DOCUMENTATION',
    field: 'Technology',
    topics: ['JavaScript', 'Frontend'],
    level: 'beginner',
    language: 'en',
    isFree: true,
    qualityScore: 100,
    votes: 8000,
    addedBy: 'team',
    verified: true,
    description: 'The gold standard documentation for web developers.',
    duration: 'Reference',
    whyRecommended: 'The definitive documentation. Most trusted reference used by professional developers.',
    resourceTypeBadge: 'Official Documentation',
    limitations: 'Pure documentation rather than a guided sequence. Can feel dry.',
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true
    }
  },
  {
    id: 'js3',
    title: 'Exercism JavaScript Track',
    url: 'https://exercism.org/tracks/javascript',
    source: 'Other',
    format: 'PRACTICE',
    field: 'Technology',
    topics: ['JavaScript', 'Practice'],
    level: 'beginner',
    language: 'en',
    isFree: true,
    qualityScore: 96,
    votes: 3500,
    addedBy: 'team',
    verified: true,
    description: 'Interactive JS exercises.',
    duration: 'Self-paced',
    whyRecommended: 'Great feedback loops. Teaches programming patterns with strict automated testing.',
    resourceTypeBadge: 'Interactive Practice',
    limitations: 'Requires command-line setups for local code execution.',
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true
    }
  },
  {
    id: 'js4',
    title: 'Frontend Mentor',
    url: 'https://www.frontendmentor.io/',
    source: 'Other',
    format: 'PROJECT',
    field: 'Technology',
    topics: ['JavaScript', 'Frontend', 'Projects'],
    level: 'intermediate',
    language: 'en',
    isFree: true,
    qualityScore: 98,
    votes: 4500,
    addedBy: 'team',
    verified: true,
    description: 'Build real-world HTML, CSS, and JS projects.',
    duration: 'Self-paced',
    whyRecommended: 'Bridges the gap between basic tutorials and building custom projects.',
    resourceTypeBadge: 'Project Based',
    limitations: 'Figma mockups are behind a paid wall (you receive JPEG designs in the free tier).',
    alternativeResource: {
      title: 'Build Your Own X',
      url: 'https://github.com/codecrafters-io/build-your-own-x',
      reason: 'If you prefer building logical backend assets rather than CSS alignment tasks.'
    },
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true
    }
  },

  // --- REACT ---
  {
    id: 'r1',
    title: 'The Beginner\'s Guide to React',
    url: 'https://egghead.io/courses/the-beginner-s-guide-to-react',
    source: 'Other',
    format: 'COURSE',
    field: 'Technology',
    topics: ['React', 'Frontend'],
    level: 'beginner',
    language: 'en',
    isFree: true,
    qualityScore: 95,
    votes: 3000,
    addedBy: 'team',
    verified: true,
    description: 'Excellent free React course by Kent C. Dodds.',
    duration: '3 hours',
    whyRecommended: 'Teaches building React from raw script tags to build files, laying down strong fundamental logic.',
    resourceTypeBadge: 'Video Course',
    limitations: 'Does not cover React Server Components (RSC) or advanced Next.js patterns.',
    alternativeResource: {
      title: 'React.dev Official Docs',
      url: 'https://react.dev/learn',
      reason: 'To study modern interactive React code syntax directly in the browser.'
    },
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true
    }
  },
  {
    id: 'r2',
    title: 'React.dev Official Docs',
    url: 'https://react.dev/learn',
    source: 'Official Docs',
    format: 'DOCUMENTATION',
    field: 'Technology',
    topics: ['React', 'Frontend'],
    level: 'beginner',
    language: 'en',
    isFree: true,
    qualityScore: 99,
    votes: 7000,
    addedBy: 'team',
    verified: true,
    description: 'The official React documentation.',
    duration: 'Reference',
    whyRecommended: 'Superb interactive playground. The modern documentation is widely considered the best framework guide.',
    resourceTypeBadge: 'Official Documentation',
    limitations: 'Can feel overwhelming to beginners who lack deep JavaScript basic competency.',
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true
    }
  },
  {
    id: 'r3',
    title: 'React Tutorial: Tic-Tac-Toe',
    url: 'https://react.dev/learn/tutorial-tic-tac-toe',
    source: 'Official Docs',
    format: 'PRACTICE',
    field: 'Technology',
    topics: ['React', 'Practice'],
    level: 'beginner',
    language: 'en',
    isFree: true,
    qualityScore: 94,
    votes: 2000,
    addedBy: 'team',
    verified: true,
    description: 'Interactive React tutorial building a game.',
    duration: '2 hours',
    whyRecommended: 'Standard entry project. Solidifies understanding of state mutation rules and props passing.',
    resourceTypeBadge: 'Interactive Practice',
    limitations: 'Very simple coding target. Does not deal with remote API query handling.',
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true
    }
  },
  {
    id: 'r4',
    title: 'Build and Deploy a React App',
    url: 'https://vite.dev/guide/',
    source: 'freeCodeCamp',
    format: 'PROJECT',
    field: 'Technology',
    topics: ['React', 'Projects'],
    level: 'intermediate',
    language: 'en',
    isFree: true,
    qualityScore: 93,
    votes: 1800,
    addedBy: 'team',
    verified: true,
    description: 'End-to-end tutorial on building and deploying React.',
    duration: '4 hours',
    whyRecommended: 'Teaches Vite configurations and hosting deployments on remote CDNs (Netlify/Vercel).',
    resourceTypeBadge: 'Project Based',
    limitations: 'Fast-paced tutorial that doesn\'t explain core React state rules in-depth.',
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true
    }
  },

  // --- NODE.JS & BACKEND ---
  {
    id: 'n1',
    title: 'Node.js Full Course',
    url: 'https://www.freecodecamp.org/learn/back-end-development-and-apis/',
    source: 'freeCodeCamp',
    format: 'COURSE',
    field: 'Technology',
    topics: ['Node', 'Backend', 'JavaScript'],
    level: 'beginner',
    language: 'en',
    isFree: true,
    qualityScore: 96,
    votes: 4000,
    addedBy: 'team',
    verified: true,
    description: 'Learn Node.js, Express, and MongoDB.',
    duration: 'Self-paced',
    whyRecommended: 'Covers REST API creations, package managers, and database models in JavaScript.',
    resourceTypeBadge: 'Community Recommended',
    limitations: 'Covers MongoDB instead of relational SQL databases (PostgreSQL/MySQL).',
    alternativeResource: {
      title: 'Full Stack Open (Helsinki)',
      url: 'https://fullstackopen.com/en/',
      reason: 'Includes relational SQL and complex container deployment tasks.'
    },
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true
    }
  },
  {
    id: 'n2',
    title: 'Node.js Official Docs',
    url: 'https://nodejs.org/en/docs/',
    source: 'Official Docs',
    format: 'DOCUMENTATION',
    field: 'Technology',
    topics: ['Node', 'Backend'],
    level: 'beginner',
    language: 'en',
    isFree: true,
    qualityScore: 92,
    votes: 2000,
    addedBy: 'team',
    verified: true,
    description: 'The official Node.js documentation.',
    duration: 'Reference',
    whyRecommended: 'The absolute source of truth for standard library APIs and file system integrations.',
    resourceTypeBadge: 'Official Documentation',
    limitations: 'Pure library spec reference rather than tutorial flow guide.',
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true
    }
  },
  {
    id: 'n3',
    title: 'Nodeschool.io',
    url: 'https://nodeschool.io/',
    source: 'Other',
    format: 'PRACTICE',
    field: 'Technology',
    topics: ['Node', 'Practice'],
    level: 'beginner',
    language: 'en',
    isFree: true,
    qualityScore: 93,
    votes: 1500,
    addedBy: 'team',
    verified: true,
    description: 'Interactive command-line workshops for Node.js.',
    duration: 'Self-paced',
    whyRecommended: 'Allows students to practice asynchronous tasks directly inside local shells.',
    resourceTypeBadge: 'Interactive Practice',
    limitations: 'Requires local node/terminal configuration before commencing exercises.',
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true
    }
  },
  {
    id: 'n4',
    title: 'Build a CRUD API with Node',
    url: 'https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs',
    source: 'Other',
    format: 'PROJECT',
    field: 'Technology',
    topics: ['Node', 'Backend', 'Projects'],
    level: 'intermediate',
    language: 'en',
    isFree: true,
    qualityScore: 95,
    votes: 2500,
    addedBy: 'team',
    verified: true,
    description: 'The Odin Project Node.js project.',
    duration: '10 hours',
    whyRecommended: 'Excellent portfolio check. Guides students to build a full inventory server.',
    resourceTypeBadge: 'Project Based',
    limitations: 'High study investment requirements; expect multiple days to finish code.',
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true
    }
  },

  // --- SQL ---
  {
    id: 's1',
    title: 'Stanford Databases Course',
    url: 'https://online.stanford.edu/courses/soe-ydatabases-databases',
    source: 'Stanford',
    format: 'COURSE',
    field: 'Technology',
    topics: ['SQL', 'Databases', 'Backend'],
    level: 'beginner',
    language: 'en',
    isFree: true,
    qualityScore: 97,
    votes: 3000,
    addedBy: 'team',
    verified: true,
    description: 'Highly rated free Stanford course on databases.',
    duration: 'Self-paced',
    whyRecommended: 'Stanford university curriculum. Explains normalization and query compilation algorithms.',
    resourceTypeBadge: 'University Curriculum',
    limitations: 'Lacks hands-on dynamic interface sandbox elements.',
    alternativeResource: {
      title: 'SQLBolt',
      url: 'https://sqlbolt.com/',
      reason: 'For immediate, browser-based SQL syntax exercises.'
    },
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true
    }
  },
  {
    id: 's2',
    title: 'PostgreSQL Official Docs',
    url: 'https://www.postgresql.org/docs/',
    source: 'Official Docs',
    format: 'DOCUMENTATION',
    field: 'Technology',
    topics: ['SQL', 'Databases'],
    level: 'intermediate',
    language: 'en',
    isFree: true,
    qualityScore: 95,
    votes: 2000,
    addedBy: 'team',
    verified: true,
    description: 'Official Postgres documentation.',
    duration: 'Reference',
    whyRecommended: 'Official documentation covering transactional integrity and constraint models.',
    resourceTypeBadge: 'Official Documentation',
    limitations: 'Written for production database administrators, not beginners.',
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true
    }
  },
  {
    id: 's3',
    title: 'SQLBolt',
    url: 'https://sqlbolt.com/',
    source: 'Other',
    format: 'PRACTICE',
    field: 'Technology',
    topics: ['SQL', 'Practice'],
    level: 'beginner',
    language: 'en',
    isFree: true,
    qualityScore: 99,
    votes: 5000,
    addedBy: 'team',
    verified: true,
    description: 'The best interactive site to learn SQL queries.',
    duration: '4 hours',
    whyRecommended: 'Immediate in-browser feedback. The absolute best way to learn standard query logic.',
    resourceTypeBadge: 'Interactive Practice',
    limitations: 'Focuses only on querying (SELECT) rather than schema optimizations.',
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true
    }
  },
  {
    id: 's4',
    title: 'Database Design Project',
    url: 'https://www.freecodecamp.org/learn/relational-database/',
    source: 'freeCodeCamp',
    format: 'PROJECT',
    field: 'Technology',
    topics: ['SQL', 'Projects'],
    level: 'intermediate',
    language: 'en',
    isFree: true,
    qualityScore: 94,
    votes: 2200,
    addedBy: 'team',
    verified: true,
    description: 'Build interactive databases in the browser.',
    duration: 'Self-paced',
    whyRecommended: 'Teaches table relation architecture and database schemas.',
    resourceTypeBadge: 'Project Based',
    limitations: 'Runs in virtual shells that can sometimes crash or load slowly.',
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true
    }
  },

  // --- GIT & GITHUB ---
  {
    id: 'g1',
    title: 'Git & GitHub Crash Course',
    url: 'https://www.youtube.com/watch?v=RGOj5yH7evk',
    source: 'freeCodeCamp',
    format: 'COURSE',
    field: 'Technology',
    topics: ['Git', 'GitHub'],
    level: 'beginner',
    language: 'en',
    isFree: true,
    qualityScore: 96,
    votes: 4000,
    addedBy: 'team',
    verified: true,
    description: 'Complete crash course on version control.',
    duration: '1 hour',
    whyRecommended: 'Explains staging areas, commits, push, pull and basic conflict resolution visual-style.',
    resourceTypeBadge: 'Video Course',
    limitations: 'Lacks advanced Git techniques like rebase or squash.',
    alternativeResource: {
      title: 'Learn Git Branching',
      url: 'https://learngitbranching.js.org/',
      reason: 'For visual, interactive branching drills.'
    },
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true
    }
  },
  {
    id: 'g2',
    title: 'Git Official Docs',
    url: 'https://git-scm.com/doc',
    source: 'Official Docs',
    format: 'DOCUMENTATION',
    field: 'Technology',
    topics: ['Git'],
    level: 'beginner',
    language: 'en',
    isFree: true,
    qualityScore: 95,
    votes: 2000,
    addedBy: 'team',
    verified: true,
    description: 'Pro Git book and official documentation.',
    duration: 'Reference',
    whyRecommended: 'Official language reference. Includes the free "Pro Git" digital book.',
    resourceTypeBadge: 'Official Documentation',
    limitations: 'Pro Git is extremely detailed; reading the whole book is not needed for beginners.',
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true
    }
  },
  {
    id: 'g3',
    title: 'Learn Git Branching',
    url: 'https://learngitbranching.js.org/',
    source: 'Other',
    format: 'PRACTICE',
    field: 'Technology',
    topics: ['Git', 'Practice'],
    level: 'beginner',
    language: 'en',
    isFree: true,
    qualityScore: 100,
    votes: 8000,
    addedBy: 'team',
    verified: true,
    description: 'The most visual and interactive way to learn Git.',
    duration: '3 hours',
    whyRecommended: 'The absolute standard for mastering Git branching visual-style.',
    resourceTypeBadge: 'Interactive Practice',
    limitations: 'Simulated playground; command sequences can occasionally differ from local terminal states.',
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true
    }
  },
  {
    id: 'g4',
    title: 'Open Source Contribution Guide',
    url: 'https://github.com/firstcontributions/first-contributions',
    source: 'GitHub',
    format: 'PROJECT',
    field: 'Technology',
    topics: ['GitHub', 'Projects'],
    level: 'beginner',
    language: 'en',
    isFree: true,
    qualityScore: 98,
    votes: 6000,
    addedBy: 'team',
    verified: true,
    description: 'Make your first open source contribution on GitHub.',
    duration: '1 hour',
    whyRecommended: 'Guides students through clone, branch, commit, and pull requests on a real repo.',
    resourceTypeBadge: 'Project Based',
    limitations: 'Simplistic workflow designed to show mechanics; does not teach code changes validation.',
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true
    }
  },

  // --- LINUX ---
  {
    id: 'l1',
    title: 'Introduction to Linux',
    url: 'https://training.linuxfoundation.org/training/introduction-to-linux/',
    source: 'Linux Foundation',
    format: 'COURSE',
    field: 'Technology',
    topics: ['Linux', 'DevOps'],
    level: 'beginner',
    language: 'en',
    isFree: true,
    qualityScore: 95,
    votes: 2000,
    addedBy: 'team',
    verified: true,
    description: 'Official intro course from the Linux Foundation.',
    duration: 'Self-paced',
    whyRecommended: 'The official course outline from the creators of the Linux Foundation specifications.',
    resourceTypeBadge: 'University Curriculum',
    limitations: 'Dry academic slides style format.',
    alternativeResource: {
      title: 'OverTheWire Bandit',
      url: 'https://overthewire.org/wargames/bandit/',
      reason: 'For visual, hacking game style shell learning.'
    },
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true
    }
  },
  {
    id: 'l2',
    title: 'Linux Man Pages',
    url: 'https://man7.org/linux/man-pages/',
    source: 'Official Docs',
    format: 'DOCUMENTATION',
    field: 'Technology',
    topics: ['Linux'],
    level: 'intermediate',
    language: 'en',
    isFree: true,
    qualityScore: 90,
    votes: 1000,
    addedBy: 'team',
    verified: true,
    description: 'The official Linux manual pages.',
    duration: 'Reference',
    whyRecommended: 'The definitive standard manual reference pages for all POSIX system utilities.',
    resourceTypeBadge: 'Official Documentation',
    limitations: 'Lacks beginner onboarding context or explanations of command combinations.',
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true
    }
  },
  {
    id: 'l3',
    title: 'OverTheWire Bandit',
    url: 'https://overthewire.org/wargames/bandit/',
    source: 'Other',
    format: 'PRACTICE',
    field: 'Technology',
    topics: ['Linux', 'Cybersecurity', 'Practice'],
    level: 'beginner',
    language: 'en',
    isFree: true,
    qualityScore: 98,
    votes: 4000,
    addedBy: 'team',
    verified: true,
    description: 'Interactive wargame teaching Linux command line basics.',
    duration: 'Self-paced',
    whyRecommended: 'Gamified security challenges teaching pipe, grep, SSH, and file configuration commands.',
    resourceTypeBadge: 'Interactive Practice',
    limitations: 'Very difficult for complete beginners; requires reading forums for hints.',
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true
    }
  },
  {
    id: 'l4',
    title: 'Build a Bash Script',
    url: 'https://www.freecodecamp.org/news/bash-scripting-tutorial-linux-shell-script-and-command-line-for-beginners/',
    source: 'freeCodeCamp',
    format: 'PROJECT',
    field: 'Technology',
    topics: ['Linux', 'Projects'],
    level: 'beginner',
    language: 'en',
    isFree: true,
    qualityScore: 92,
    votes: 1500,
    addedBy: 'team',
    verified: true,
    description: 'Write automation scripts in bash.',
    duration: '2 hours',
    whyRecommended: 'Teaches cron, scheduling, variable bindings, and automating server commands.',
    resourceTypeBadge: 'Project Based',
    limitations: 'Assumes basic Linux terminal command fluency.',
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true
    }
  },

  // --- DOCKER & KUBERNETES & CLOUD ---
  {
    id: 'dk1',
    title: 'Docker Tutorial for Beginners',
    url: 'https://www.youtube.com/watch?v=pTFZFxd4hOI',
    source: 'freeCodeCamp',
    format: 'COURSE',
    field: 'Technology',
    topics: ['Docker', 'DevOps', 'Kubernetes', 'Cloud', 'AWS'],
    level: 'beginner',
    language: 'en',
    isFree: true,
    qualityScore: 96,
    votes: 3500,
    addedBy: 'team',
    verified: true,
    description: 'Learn Docker containerization basics.',
    duration: '2 hours',
    whyRecommended: 'Best visual crash course covering container files, layers, and network binding.',
    resourceTypeBadge: 'Video Course',
    limitations: 'Basic overview; does not detail production Kubernetes deployments.',
    alternativeResource: {
      title: 'Docker Official Docs',
      url: 'https://docs.docker.com/',
      reason: 'For deep system configurations and network architecture specification.'
    },
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true
    }
  },
  {
    id: 'dk2',
    title: 'Docker Official Docs',
    url: 'https://docs.docker.com/',
    source: 'Official Docs',
    format: 'DOCUMENTATION',
    field: 'Technology',
    topics: ['Docker', 'Kubernetes', 'Cloud', 'AWS'],
    level: 'intermediate',
    language: 'en',
    isFree: true,
    qualityScore: 95,
    votes: 2000,
    addedBy: 'team',
    verified: true,
    description: 'Official Docker documentation.',
    duration: 'Reference',
    whyRecommended: 'The official source for Dockerfile configurations and Docker Compose specifications.',
    resourceTypeBadge: 'Official Documentation',
    limitations: 'Dry reference documentation without a unified tutorial sequence.',
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true
    }
  },
  {
    id: 'dk3',
    title: 'Play with Docker',
    url: 'https://labs.play-with-docker.com/',
    source: 'Other',
    format: 'PRACTICE',
    field: 'Technology',
    topics: ['Docker', 'Kubernetes', 'Practice', 'Cloud', 'AWS'],
    level: 'beginner',
    language: 'en',
    isFree: true,
    qualityScore: 97,
    votes: 2500,
    addedBy: 'team',
    verified: true,
    description: 'Interactive Docker playground in the browser.',
    duration: 'Self-paced',
    whyRecommended: 'Free browser-based Docker terminal sandbox. Ideal for students lacking local hardware.',
    resourceTypeBadge: 'Interactive Practice',
    limitations: 'Requires logging in with Docker Hub credentials; session lasts 4 hours.',
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true
    }
  },
  {
    id: 'dk4',
    title: 'Deploy to AWS Project',
    url: 'https://aws.amazon.com/getting-started/hands-on/build-react-app-amplify-graphql/',
    source: 'AWS',
    format: 'PROJECT',
    field: 'Technology',
    topics: ['AWS', 'Docker', 'Kubernetes', 'Cloud', 'Projects'],
    level: 'intermediate',
    language: 'en',
    isFree: true,
    qualityScore: 94,
    votes: 1800,
    addedBy: 'team',
    verified: true,
    description: 'Deploy a full-stack app on AWS.',
    duration: '4 hours',
    whyRecommended: 'Official hands-on AWS lab guides for deploying serverless web apps.',
    resourceTypeBadge: 'Project Based',
    limitations: 'AWS Free Tier requires inputting a credit card during signup.',
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true
    }
  },

  // --- AI & DATA SCIENCE ---
  {
    id: 'ai1',
    title: 'fast.ai Practical Deep Learning',
    url: 'https://course.fast.ai/',
    source: 'fast.ai',
    format: 'COURSE',
    field: 'Data Science',
    topics: ['AI', 'Data Science', 'Machine Learning'],
    level: 'intermediate',
    language: 'en',
    isFree: true,
    qualityScore: 99,
    votes: 5000,
    addedBy: 'team',
    verified: true,
    description: 'The best top-down deep learning course available.',
    duration: '7 weeks',
    whyRecommended: 'Superb top-down approach. Students train neural networks in week 1 before studying equations.',
    resourceTypeBadge: 'Community Gold Standards',
    limitations: 'Requires GPU compute access (Google Colab/Kaggle) to run local training labs.',
    alternativeResource: {
      title: 'Stanford CS229 Machine Learning',
      url: 'https://cs229.stanford.edu/',
      reason: 'For students who prefer a bottom-up, math-first theoretical foundation.'
    },
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true
    }
  },
  {
    id: 'ai2',
    title: 'PyTorch Official Docs',
    url: 'https://pytorch.org/docs/stable/index.html',
    source: 'Official Docs',
    format: 'DOCUMENTATION',
    field: 'Data Science',
    topics: ['AI', 'Data Science', 'Machine Learning'],
    level: 'intermediate',
    language: 'en',
    isFree: true,
    qualityScore: 95,
    votes: 3000,
    addedBy: 'team',
    verified: true,
    description: 'Official documentation for PyTorch.',
    duration: 'Reference',
    whyRecommended: 'Official API reference. Critical for validating tensor transformations and network layers.',
    resourceTypeBadge: 'Official Documentation',
    limitations: 'Written strictly as class references; not an introductory deep learning syllabus.',
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true
    }
  },
  {
    id: 'ai3',
    title: 'Kaggle Learn',
    url: 'https://www.kaggle.com/learn/intro-to-machine-learning',
    source: 'Kaggle',
    format: 'PRACTICE',
    field: 'Data Science',
    topics: ['AI', 'Data Science', 'Machine Learning', 'Data Analyst', 'Practice'],
    level: 'beginner',
    language: 'en',
    isFree: true,
    qualityScore: 97,
    votes: 4000,
    addedBy: 'team',
    verified: true,
    description: 'Interactive ML and Data Science exercises.',
    duration: 'Self-paced',
    whyRecommended: 'In-browser notebooks with free GPU access, teaching data cleaning and predictive modeling.',
    resourceTypeBadge: 'Interactive Practice',
    limitations: 'Simplistic coding puzzles that hide realistic raw data messy cleaning challenges.',
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true
    }
  },
  {
    id: 'ai4',
    title: 'Build a Machine Learning API',
    url: 'https://fastapi.tiangolo.com/tutorial/',
    source: 'Official Docs',
    format: 'PROJECT',
    field: 'Data Science',
    topics: ['AI', 'Data Science', 'Machine Learning', 'Projects'],
    level: 'intermediate',
    language: 'en',
    isFree: true,
    qualityScore: 96,
    votes: 2000,
    addedBy: 'team',
    verified: true,
    description: 'Use FastAPI to serve an ML model.',
    duration: '5 hours',
    whyRecommended: 'Teaches web endpoint creation to serve saved prediction models.',
    resourceTypeBadge: 'Project Based',
    limitations: 'Focuses on API structure rather than model training logic.',
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true
    }
  },

  // --- CYBERSECURITY ---
  {
    id: 'cy1',
    title: 'Google Cybersecurity Certificate',
    url: 'https://www.youtube.com/watch?v=2KZZtS9M2C8',
    source: 'YouTube',
    format: 'COURSE',
    field: 'Technology',
    topics: ['Cybersecurity'],
    level: 'beginner',
    language: 'en',
    isFree: true,
    qualityScore: 93,
    votes: 1500,
    addedBy: 'team',
    verified: true,
    description: 'Free YouTube equivalent of the core concepts.',
    duration: '8 hours',
    whyRecommended: 'Explains threat intelligence, network logging, and basic security operations.',
    resourceTypeBadge: 'Video Course',
    limitations: 'Basic overview; does not contain hands-on network penetration testing drills.',
    alternativeResource: {
      title: 'TryHackMe Basics',
      url: 'https://tryhackme.com/',
      reason: 'For interactive, hand-on hacking challenge labs.'
    },
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true
    }
  },
  {
    id: 'cy2',
    title: 'OWASP Top 10 Docs',
    url: 'https://owasp.org/www-project-top-ten/',
    source: 'Official Docs',
    format: 'DOCUMENTATION',
    field: 'Technology',
    topics: ['Cybersecurity'],
    level: 'intermediate',
    language: 'en',
    isFree: true,
    qualityScore: 98,
    votes: 3000,
    addedBy: 'team',
    verified: true,
    description: 'The official standard for web application security.',
    duration: 'Reference',
    whyRecommended: 'The gold standard reference checklist for web vulnerability classification.',
    resourceTypeBadge: 'Official Documentation',
    limitations: 'Does not explain code implementations, only vulnerability mechanics.',
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true
    }
  },
  {
    id: 'cy3',
    title: 'TryHackMe Basics',
    url: 'https://tryhackme.com/',
    source: 'Other',
    format: 'PRACTICE',
    field: 'Technology',
    topics: ['Cybersecurity', 'Practice'],
    level: 'beginner',
    language: 'en',
    isFree: true,
    qualityScore: 97,
    votes: 4000,
    addedBy: 'team',
    verified: true,
    description: 'Interactive cybersecurity training labs.',
    duration: 'Self-paced',
    whyRecommended: 'Hands-on browser-based Linux environments to hack and secure machines.',
    resourceTypeBadge: 'Interactive Practice',
    limitations: 'Advanced rooms are behind a monthly subscription model.',
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true
    }
  },
  {
    id: 'cy4',
    title: 'Security Audit Project',
    url: 'https://owasp.org/www-project-juice-shop/',
    source: 'GitHub',
    format: 'PROJECT',
    field: 'Technology',
    topics: ['Cybersecurity', 'Projects'],
    level: 'intermediate',
    language: 'en',
    isFree: true,
    qualityScore: 95,
    votes: 2000,
    addedBy: 'team',
    verified: true,
    description: 'Hack the OWASP Juice Shop vulnerable app.',
    duration: '10 hours',
    whyRecommended: 'Excellent sandbox app. Guides students through exploiting OWASP Top 10 vulnerabilities.',
    resourceTypeBadge: 'Project Based',
    limitations: 'Requires running Docker locally to deploy safely.',
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true
    }
  },

  // --- MOBILE DEVELOPMENT ---
  {
    id: 'fa1',
    title: 'Flutter & Dart Complete Course',
    url: 'https://www.youtube.com/watch?v=VPvVD8t02U8',
    source: 'freeCodeCamp',
    format: 'COURSE',
    field: 'Technology',
    topics: ['Flutter', 'Android'],
    level: 'beginner',
    language: 'en',
    isFree: true,
    qualityScore: 95,
    votes: 2500,
    addedBy: 'team',
    verified: true,
    description: 'Build cross-platform apps with Flutter.',
    duration: '37 hours',
    whyRecommended: 'Comprehensive video course explaining widgets, local serialization, and app deployment.',
    resourceTypeBadge: 'Video Course',
    limitations: 'Very long (37 hours) video sequence; requires dedication to complete.',
    alternativeResource: {
      title: 'Flutter Official Docs',
      url: 'https://docs.flutter.dev/',
      reason: 'For quick cookbook solutions instead of a long video walkthrough.'
    },
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true
    }
  },

  // --- OPEN SOURCE COLLECTIONS ---
  {
    id: 'gh_books',
    title: 'Free Programming Books',
    url: 'https://github.com/EbookFoundation/free-programming-books',
    source: 'GitHub',
    format: 'DOCUMENTATION',
    field: 'Technology',
    topics: ['Python', 'Java', 'JavaScript', 'SQL', 'Git', 'Linux'],
    level: 'beginner',
    language: 'en',
    isFree: true,
    qualityScore: 100,
    votes: 9000,
    addedBy: 'team',
    verified: true,
    description: 'The largest repository of curated free programming books and courses in the world.',
    duration: 'Reference',
    whyRecommended: 'Definitive world-class repository containing thousands of open-source programming books.',
    resourceTypeBadge: 'Open Source',
    limitations: 'Contains thousands of links; can trigger choice paralysis for beginners.',
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true
    }
  },
  {
    id: 'gh_ossu',
    title: 'OSSU Computer Science',
    url: 'https://github.com/ossu/computer-science',
    source: 'GitHub',
    format: 'COURSE',
    field: 'Technology',
    topics: ['Python', 'Java', 'JavaScript', 'SQL', 'Git', 'Linux', 'Practice'],
    level: 'beginner',
    language: 'en',
    isFree: true,
    qualityScore: 99,
    votes: 8000,
    addedBy: 'team',
    verified: true,
    description: 'Path to a free self-taught education in Computer Science using online materials.',
    duration: 'Self-paced',
    whyRecommended: 'Complete, structured CS curriculum modeled after MIT/Stanford syllabus requirements.',
    resourceTypeBadge: 'University Curriculum',
    limitations: 'Takes 1-2 years of intensive research and math study to fully complete.',
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true
    }
  },
  {
    id: 'gh_build_own_x',
    title: 'Build Your Own X',
    url: 'https://github.com/codecrafters-io/build-your-own-x',
    source: 'GitHub',
    format: 'PROJECT',
    field: 'Technology',
    topics: ['Projects', 'Python', 'JavaScript', 'Java', 'SQL', 'Git', 'Docker'],
    level: 'intermediate',
    language: 'en',
    isFree: true,
    qualityScore: 100,
    votes: 9500,
    addedBy: 'team',
    verified: true,
    description: 'Learn software engineering by building your own Git, Docker, Database, or BitTorrent client from scratch.',
    duration: 'Self-paced',
    whyRecommended: 'The gold standard project repository for proving computer science competency to recruiters.',
    resourceTypeBadge: 'Project Based',
    limitations: 'Extremely advanced. Requires pre-existing solid programming fundamentals.',
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true
    }
  },

  // --- UX/UI DESIGN ---
  {
    id: 'ux_figma',
    title: 'Figma Official Getting Started',
    url: 'https://help.figma.com/hc/en-us/categories/360002051613-Learn-Figma',
    source: 'Official Docs',
    format: 'DOCUMENTATION',
    field: 'Design',
    topics: ['Figma', 'UI Design', 'Prototyping', 'Design'],
    level: 'beginner',
    language: 'en',
    isFree: true,
    qualityScore: 98,
    votes: 4000,
    addedBy: 'team',
    verified: true,
    description: 'Learn how to navigate and design in Figma, the industry standard UI/UX design tool.',
    duration: 'Reference',
    whyRecommended: 'Official tool documentation. Crucial for mastering auto-layout, components, and variables.',
    resourceTypeBadge: 'Official Documentation',
    limitations: 'Focuses on the tool interface rather than core graphic layout theory.',
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true
    }
  },
  {
    id: 'ux_nngroup',
    title: 'Nielsen Norman Group UX Basics',
    url: 'https://www.nngroup.com/articles/ten-usability-heuristics/',
    source: 'Other',
    format: 'DOCUMENTATION',
    field: 'Design',
    topics: ['UX Design', 'User Research', 'Design Thinking', 'Usability Testing', 'Design'],
    level: 'beginner',
    language: 'en',
    isFree: true,
    qualityScore: 100,
    votes: 8500,
    addedBy: 'team',
    verified: true,
    description: 'The absolute authority on UX guidelines, heuristics, and research methodology.',
    duration: 'Reference',
    whyRecommended: 'The gold standard of user experience research. Establishes core usability guidelines.',
    resourceTypeBadge: 'Reference Guide',
    limitations: 'Heavy cognitive design articles rather than visual design tips.',
    alternativeResource: {
      title: 'Laws of UX',
      url: 'https://lawsofux.com/',
      reason: 'For visual, card-styled summaries of cognitive design rules.'
    },
    verification: {
      lastReviewed: 'June 2026',
      reviewedBy: 'ScholarSync Core Team',
      isFree: true,
      isActive: true
    }
  }
];
