import type { Resource } from '@/types';

// Additional real, up-to-date free courses from Class Central, Coursera, edX, etc.
export const additionalResources: Resource[] = [
  // --- CS & Programming ---
  { id: 'r-25', title: 'Python for Everybody (Dr. Chuck)', url: 'https://www.py4e.com/', source: 'Coursera', format: 'course', field: 'Technology', topics: ['Python', 'Programming', 'Web Scraping'], level: 'beginner', language: 'en', isFree: true, qualityScore: 96, votes: 4100, addedBy: 'team', verified: true, description: 'The most popular Python course ever. Learn Python from scratch with real projects.', duration: '8 weeks' },
  { id: 'r-26', title: 'Web Development Bootcamp (Angela Yu)', url: 'https://www.appbrewery.co/p/web-development-course-resources', source: 'Other', format: 'course', field: 'Technology', topics: ['HTML', 'CSS', 'JavaScript', 'React', 'Node.js'], level: 'beginner', language: 'en', isFree: true, qualityScore: 95, votes: 3800, addedBy: 'team', verified: true, description: 'Complete web dev resources covering HTML, CSS, JS, React, Node.js and databases.', duration: 'Self-paced' },
  { id: 'r-27', title: 'MIT 6.0001 Intro to CS with Python', url: 'https://ocw.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/', source: 'MIT OCW', format: 'course', field: 'Technology', topics: ['Python', 'CS Fundamentals', 'Problem Solving'], level: 'beginner', language: 'en', isFree: true, qualityScore: 97, votes: 3200, addedBy: 'team', verified: true, description: 'MIT\'s intro CS course using Python. Lectures, assignments, and exams all free.', duration: '14 weeks' },
  { id: 'r-28', title: 'Full Stack Open (Helsinki)', url: 'https://fullstackopen.com/en/', source: 'Other', format: 'course', field: 'Technology', topics: ['React', 'Node.js', 'GraphQL', 'TypeScript'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 96, votes: 2900, addedBy: 'team', verified: true, description: 'University of Helsinki\'s modern full-stack course. React, Node, GraphQL, TypeScript, CI/CD.', duration: '12 weeks' },
  { id: 'r-29', title: 'Nand2Tetris (Build a Computer)', url: 'https://www.nand2tetris.org/', source: 'Coursera', format: 'course', field: 'Technology', topics: ['Computer Architecture', 'Hardware', 'Assembly', 'OS'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 98, votes: 2600, addedBy: 'team', verified: true, description: 'Build a computer from logic gates to an operating system. One of the best CS courses ever made.', duration: '12 weeks' },
  { id: 'r-30', title: 'Eloquent JavaScript (Free Book)', url: 'https://eloquentjavascript.net/', source: 'Other', format: 'book', field: 'Technology', topics: ['JavaScript', 'Programming', 'Web'], level: 'beginner', language: 'en', isFree: true, qualityScore: 94, votes: 2400, addedBy: 'team', verified: true, description: 'The best free JavaScript book. Covers fundamentals, DOM, Node.js, and advanced concepts.', duration: 'Self-paced' },
  { id: 'r-31', title: 'Git & GitHub Crash Course', url: 'https://www.youtube.com/watch?v=RGOj5yH7evk', source: 'YouTube', format: 'video', field: 'Technology', topics: ['Git', 'GitHub', 'Version Control'], level: 'beginner', language: 'en', isFree: true, qualityScore: 91, votes: 3100, addedBy: 'team', verified: true, description: 'freeCodeCamp\'s comprehensive Git tutorial. Learn branching, merging, and collaboration.', duration: '1 hour' },
  { id: 'r-32', title: 'Stanford CS229 Machine Learning', url: 'https://cs229.stanford.edu/', source: 'Stanford', format: 'course', field: 'Data Science', topics: ['Machine Learning', 'Linear Algebra', 'Statistics'], level: 'advanced', language: 'en', isFree: true, qualityScore: 98, votes: 3500, addedBy: 'team', verified: true, description: 'Andrew Ng\'s legendary Stanford ML course. Full lecture videos, notes, and problem sets.', duration: '11 weeks' },
  { id: 'r-33', title: 'Deep Learning Specialization (Audit)', url: 'https://www.coursera.org/specializations/deep-learning', source: 'Coursera', format: 'course', field: 'Data Science', topics: ['Deep Learning', 'Neural Networks', 'CNN', 'RNN'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 97, votes: 4200, addedBy: 'team', verified: true, description: 'Andrew Ng\'s deep learning courses. Free to audit — covers NNs, CNNs, RNNs, and more.', duration: '5 months' },
  { id: 'r-34', title: 'StatQuest YouTube Channel', url: 'https://www.youtube.com/c/joshstarmer', source: 'YouTube', format: 'video', field: 'Data Science', topics: ['Statistics', 'Machine Learning', 'Math'], level: 'beginner', language: 'en', isFree: true, qualityScore: 95, votes: 3800, addedBy: 'team', verified: true, description: 'The best stats channel on YouTube. Complex topics explained with animations and humor.', duration: 'Varies' },
  { id: 'r-35', title: '3Blue1Brown Linear Algebra', url: 'https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab', source: 'YouTube', format: 'video', field: 'Data Science', topics: ['Linear Algebra', 'Math', 'Visualization'], level: 'beginner', language: 'en', isFree: true, qualityScore: 99, votes: 5200, addedBy: 'team', verified: true, description: 'The most beautiful math series ever made. Understand linear algebra visually and intuitively.', duration: '3.5 hours' },
  // --- Finance & Business ---
  { id: 'r-36', title: 'MIT 15.401 Finance Theory', url: 'https://ocw.mit.edu/courses/15-401-finance-theory-i-fall-2008/', source: 'MIT OCW', format: 'course', field: 'Finance', topics: ['Finance', 'Valuation', 'Portfolio Theory'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 94, votes: 1800, addedBy: 'team', verified: true, description: 'MIT\'s finance course covering present value, portfolio theory, CAPM, and options.', duration: '15 weeks' },
  { id: 'r-37', title: 'Investopedia Academy (Free Articles)', url: 'https://www.investopedia.com/', source: 'Other', format: 'text', field: 'Finance', topics: ['Investing', 'Trading', 'Personal Finance'], level: 'beginner', language: 'en', isFree: true, qualityScore: 90, votes: 2800, addedBy: 'team', verified: true, description: 'The world\'s best free financial encyclopedia. Learn investing, trading, and money management.', duration: 'Self-paced' },
  // --- Design ---
  { id: 'r-38', title: 'Laws of UX', url: 'https://lawsofux.com/', source: 'Other', format: 'text', field: 'Design', topics: ['UX Design', 'Psychology', 'Design Principles'], level: 'beginner', language: 'en', isFree: true, qualityScore: 93, votes: 2100, addedBy: 'team', verified: true, description: 'Beautiful collection of UX design principles backed by psychology research.', duration: '1 hour' },
  { id: 'r-39', title: 'Refactoring UI (Free Chapter)', url: 'https://www.refactoringui.com/', source: 'Other', format: 'text', field: 'Design', topics: ['UI Design', 'Visual Design', 'Color'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 92, votes: 1900, addedBy: 'team', verified: true, description: 'Practical UI design tips from the creators of Tailwind CSS. Make your designs look professional.', duration: '2 hours' },
  // --- Science ---
  { id: 'r-40', title: 'MIT 8.01 Classical Mechanics', url: 'https://ocw.mit.edu/courses/8-01sc-classical-mechanics-fall-2016/', source: 'MIT OCW', format: 'course', field: 'Science', topics: ['Physics', 'Mechanics', 'JEE Prep'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 96, votes: 2200, addedBy: 'team', verified: true, description: 'MIT\'s physics course. Excellent for JEE/NEET students wanting deeper understanding.', duration: '15 weeks' },
  { id: 'r-41', title: 'Khan Academy Biology', url: 'https://www.khanacademy.org/science/biology', source: 'Khan Academy', format: 'course', field: 'Science', topics: ['Biology', 'Cell Biology', 'Genetics', 'NEET'], level: 'beginner', language: 'en', isFree: true, qualityScore: 95, votes: 3400, addedBy: 'team', verified: true, description: 'Complete biology curriculum from cells to ecology. Perfect for NEET and board exam prep.', duration: 'Self-paced' },
  { id: 'r-42', title: 'Organic Chemistry Tutor (YouTube)', url: 'https://www.youtube.com/c/TheOrganicChemistryTutor', source: 'YouTube', format: 'video', field: 'Science', topics: ['Chemistry', 'Physics', 'Math', 'JEE'], level: 'beginner', language: 'en', isFree: true, qualityScore: 94, votes: 4100, addedBy: 'team', verified: true, description: 'One of the best free channels for JEE/NEET science. Clear explanations of tough topics.', duration: 'Varies' },
  // --- Marketing ---
  { id: 'r-43', title: 'Google Digital Marketing Certificate', url: 'https://learndigital.withgoogle.com/digitalgarage', source: 'Google', format: 'course', field: 'Marketing', topics: ['Digital Marketing', 'SEO', 'Analytics', 'Ads'], level: 'beginner', language: 'en', isFree: true, qualityScore: 93, votes: 3200, addedBy: 'team', verified: true, description: 'Google\'s free digital marketing certification. Learn SEO, SEM, analytics, and social media.', duration: '40 hours' },
  { id: 'r-44', title: 'HubSpot Academy', url: 'https://academy.hubspot.com/', source: 'Other', format: 'course', field: 'Marketing', topics: ['Inbound Marketing', 'Content Marketing', 'Email'], level: 'beginner', language: 'en', isFree: true, qualityScore: 92, votes: 2400, addedBy: 'team', verified: true, description: 'Free certifications in inbound marketing, content strategy, email marketing, and sales.', duration: 'Varies' },
  // --- NPTEL / India ---
  { id: 'r-45', title: 'NPTEL Online Courses', url: 'https://nptel.ac.in/', source: 'NPTEL', format: 'course', field: 'Engineering', topics: ['Engineering', 'CS', 'Mechanical', 'Electrical'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 93, votes: 3600, addedBy: 'team', verified: true, description: 'IIT/IISc professors teaching engineering courses. Free certificates through SWAYAM.', duration: '8-12 weeks' },
  { id: 'r-46', title: 'SWAYAM Portal', url: 'https://swayam.gov.in/', source: 'Other', format: 'course', field: 'Education', topics: ['All Subjects', 'UG', 'PG', 'Engineering'], level: 'beginner', language: 'en', isFree: true, qualityScore: 90, votes: 2800, addedBy: 'team', verified: true, description: 'Indian government\'s free online learning platform. Courses from top Indian universities.', duration: 'Varies' },
  // --- Cybersecurity ---
  { id: 'r-47', title: 'TryHackMe (Free Rooms)', url: 'https://tryhackme.com/', source: 'Other', format: 'interactive', field: 'Technology', topics: ['Cybersecurity', 'Ethical Hacking', 'Linux'], level: 'beginner', language: 'en', isFree: true, qualityScore: 94, votes: 2900, addedBy: 'team', verified: true, description: 'Learn cybersecurity hands-on. Free beginner paths in networking, Linux, and web hacking.', duration: 'Self-paced' },
  { id: 'r-48', title: 'Cisco Networking Academy', url: 'https://www.netacad.com/', source: 'Other', format: 'course', field: 'Technology', topics: ['Networking', 'Cybersecurity', 'CCNA'], level: 'beginner', language: 'en', isFree: true, qualityScore: 92, votes: 2200, addedBy: 'team', verified: true, description: 'Free networking and cybersecurity courses from Cisco. Industry-recognized certifications.', duration: '70 hours' },
  // --- DevOps & Cloud ---
  { id: 'r-49', title: 'AWS Cloud Practitioner Essentials', url: 'https://explore.skillbuilder.aws/learn/course/134/aws-cloud-practitioner-essentials', source: 'Other', format: 'course', field: 'Technology', topics: ['AWS', 'Cloud Computing', 'DevOps'], level: 'beginner', language: 'en', isFree: true, qualityScore: 93, votes: 2500, addedBy: 'team', verified: true, description: 'Official AWS free course. Learn cloud fundamentals and prepare for certification.', duration: '6 hours' },
  { id: 'r-50', title: 'Docker for Beginners', url: 'https://docker-curriculum.com/', source: 'Other', format: 'text', field: 'Technology', topics: ['Docker', 'Containers', 'DevOps'], level: 'beginner', language: 'en', isFree: true, qualityScore: 91, votes: 2100, addedBy: 'team', verified: true, description: 'Best free Docker tutorial. Learn containers, images, Docker Compose step by step.', duration: '3 hours' },
  // --- Psychology ---
  { id: 'r-51', title: 'Yale Science of Well-Being', url: 'https://www.coursera.org/learn/the-science-of-well-being', source: 'Coursera', format: 'course', field: 'Humanities', topics: ['Psychology', 'Happiness', 'Mental Health'], level: 'beginner', language: 'en', isFree: true, qualityScore: 97, votes: 5500, addedBy: 'team', verified: true, description: 'Yale\'s most popular course ever. Learn the science of happiness — free to audit.', duration: '10 weeks' },
  // --- Law ---
  { id: 'r-52', title: 'Constitution of India (Bare Act)', url: 'https://legislative.gov.in/constitution-of-india/', source: 'Other', format: 'text', field: 'Law', topics: ['Constitutional Law', 'Indian Polity', 'UPSC'], level: 'beginner', language: 'en', isFree: true, qualityScore: 95, votes: 2800, addedBy: 'team', verified: true, description: 'The complete Constitution of India. Essential reading for UPSC, CLAT, and law students.', duration: 'Self-paced' },
  // --- Languages ---
  { id: 'r-53', title: 'MIT 18.06 Linear Algebra (Strang)', url: 'https://ocw.mit.edu/courses/18-06sc-linear-algebra-fall-2011/', source: 'MIT OCW', format: 'course', field: 'Data Science', topics: ['Linear Algebra', 'Mathematics', 'ML Foundation'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 98, votes: 4000, addedBy: 'team', verified: true, description: 'Gilbert Strang\'s legendary linear algebra course. Essential for ML/AI careers.', duration: '15 weeks' },
  { id: 'r-54', title: 'Harvard CS50 Web Programming', url: 'https://cs50.harvard.edu/web/', source: 'Harvard', format: 'course', field: 'Technology', topics: ['Django', 'JavaScript', 'SQL', 'React'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 96, votes: 3100, addedBy: 'team', verified: true, description: 'Harvard\'s web dev course. Django, JS, React, SQL, and software engineering principles.', duration: '12 weeks' },
  { id: 'r-55', title: 'Harvard CS50 AI', url: 'https://cs50.harvard.edu/ai/', source: 'Harvard', format: 'course', field: 'Technology', topics: ['AI', 'Search', 'Knowledge', 'Machine Learning'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 96, votes: 2800, addedBy: 'team', verified: true, description: 'Harvard\'s intro to AI. Search algorithms, knowledge representation, ML, and neural networks.', duration: '7 weeks' },
];
