import type { Career } from '@/types';

export const careers: Career[] = [
  {
    id: 'career-1',
    title: 'Software Engineer',
    slug: 'software-engineer',
    field: 'Technology',
    subfield: 'Software Development',
    description: 'Design, develop, and maintain software systems. Software engineers build everything from mobile apps to operating systems, working across the full stack of modern technology.',
    shortDescription: 'Build software that powers the modern world.',
    avgSalaryIndia: '₹8–30 LPA',
    avgSalaryGlobal: '$70K–$180K',
    demandTrend: 'rising',
    relatedCareers: ['career-3', 'career-5', 'career-16', 'career-21'],
    tags: ['coding', 'programming', 'web', 'mobile', 'systems'],
    icon: 'Code',
    roadmapShUrl: 'https://roadmap.sh/full-stack',
    stages: [
      { id: 's1', title: 'Foundations', description: 'Learn programming basics, data structures, and algorithms.', duration: '3–6 months', skills: ['Python', 'JavaScript', 'Data Structures', 'Algorithms'], resources: [], milestones: ['Build a calculator app', 'Solve 50 LeetCode problems'], order: 1 },
      { id: 's2', title: 'Core Skills', description: 'Master web development, databases, and version control.', duration: '4–6 months', skills: ['HTML/CSS', 'React', 'Node.js', 'SQL', 'Git'], resources: [], milestones: ['Build a full-stack CRUD app', 'Deploy to cloud'], order: 2 },
      { id: 's3', title: 'Specialization', description: 'Choose a focus: frontend, backend, mobile, or DevOps.', duration: '3–6 months', skills: ['System Design', 'Testing', 'CI/CD', 'Cloud Services'], resources: [], milestones: ['Contribute to open source', 'Build a portfolio project'], order: 3 },
      { id: 's4', title: 'Career Entry', description: 'Prepare for interviews and land your first role.', duration: '2–3 months', skills: ['DSA Practice', 'System Design', 'Behavioral Interviews'], resources: [], milestones: ['Complete mock interviews', 'Get first offer'], order: 4 },
    ],
  },
  {
    id: 'career-2',
    title: 'Data Scientist',
    slug: 'data-scientist',
    field: 'Data Science',
    subfield: 'Analytics & ML',
    description: 'Extract insights from data using statistics, machine learning, and domain expertise. Data scientists solve complex business problems by analyzing patterns in large datasets.',
    shortDescription: 'Turn data into actionable insights and predictions.',
    avgSalaryIndia: '₹10–35 LPA',
    avgSalaryGlobal: '$80K–$170K',
    demandTrend: 'rising',
    relatedCareers: ['career-1', 'career-5', 'career-22'],
    tags: ['data', 'machine learning', 'statistics', 'python', 'analytics'],
    icon: 'BarChart3',
    roadmapShUrl: 'https://roadmap.sh/ai-data-scientist',
    stages: [
      { id: 's1', title: 'Math & Stats', description: 'Build a strong foundation in statistics, linear algebra, and probability.', duration: '2–4 months', skills: ['Statistics', 'Linear Algebra', 'Probability', 'Python'], resources: [], milestones: ['Complete Khan Academy Stats', 'MIT OCW Linear Algebra'], order: 1 },
      { id: 's2', title: 'Data Wrangling', description: 'Learn to collect, clean, and transform data.', duration: '2–3 months', skills: ['Pandas', 'NumPy', 'SQL', 'Data Visualization'], resources: [], milestones: ['Analyze a real dataset', 'Build 3 visualizations'], order: 2 },
      { id: 's3', title: 'Machine Learning', description: 'Master supervised and unsupervised learning algorithms.', duration: '3–5 months', skills: ['Scikit-learn', 'TensorFlow', 'Feature Engineering', 'Model Evaluation'], resources: [], milestones: ['Complete fast.ai course', 'Win a Kaggle competition'], order: 3 },
      { id: 's4', title: 'Applied DS', description: 'Work on real projects and prepare for industry roles.', duration: '2–4 months', skills: ['NLP', 'Deep Learning', 'MLOps', 'Communication'], resources: [], milestones: ['Publish a project on GitHub', 'Present findings'], order: 4 },
    ],
  },
  {
    id: 'career-3',
    title: 'UX Designer',
    slug: 'ux-designer',
    field: 'Design',
    subfield: 'User Experience',
    description: 'Create intuitive, accessible, and delightful digital experiences. UX designers research user needs, prototype solutions, and work closely with engineering teams.',
    shortDescription: 'Design digital products people love to use.',
    avgSalaryIndia: '₹6–25 LPA',
    avgSalaryGlobal: '$65K–$150K',
    demandTrend: 'rising',
    relatedCareers: ['career-1', 'career-8', 'career-23'],
    tags: ['design', 'user research', 'figma', 'prototyping', 'ui'],
    icon: 'Palette',
    roadmapShUrl: 'https://roadmap.sh/ux-design',
    stages: [
      { id: 's1', title: 'Design Thinking', description: 'Learn the fundamentals of human-centered design and design thinking.', duration: '1–2 months', skills: ['Design Thinking', 'Empathy Mapping', 'User Research'], resources: [], milestones: ['Complete Google UX Design Course'], order: 1 },
      { id: 's2', title: 'Tools & Craft', description: 'Master design tools and visual design principles.', duration: '2–4 months', skills: ['Figma', 'Typography', 'Color Theory', 'Wireframing'], resources: [], milestones: ['Design 3 app concepts', 'Build a design system'], order: 2 },
      { id: 's3', title: 'Research & Testing', description: 'Learn user research methods and usability testing.', duration: '2–3 months', skills: ['Usability Testing', 'A/B Testing', 'Analytics', 'Accessibility'], resources: [], milestones: ['Conduct 5 user interviews', 'Run a usability test'], order: 3 },
      { id: 's4', title: 'Portfolio', description: 'Build a compelling portfolio and prepare for interviews.', duration: '1–2 months', skills: ['Case Studies', 'Presentation', 'Portfolio Design'], resources: [], milestones: ['Complete 3 case studies', 'Get design critique'], order: 4 },
    ],
  },
  {
    id: 'career-5',
    title: 'AI/ML Engineer',
    slug: 'ai-ml-engineer',
    field: 'Technology',
    subfield: 'Artificial Intelligence',
    description: 'Build and deploy machine learning models and AI systems at scale. Work on everything from recommendation engines to autonomous systems and large language models.',
    shortDescription: 'Build intelligent systems that learn and adapt.',
    avgSalaryIndia: '₹12–50 LPA',
    avgSalaryGlobal: '$100K–$250K',
    demandTrend: 'rising',
    relatedCareers: ['career-1', 'career-2', 'career-24'],
    tags: ['ai', 'machine learning', 'deep learning', 'python', 'neural networks'],
    icon: 'Brain',
    roadmapShUrl: 'https://roadmap.sh/ai-engineer',
    stages: [
      { id: 's1', title: 'Prerequisites', description: 'Master Python, linear algebra, calculus, and probability.', duration: '3–4 months', skills: ['Python', 'Linear Algebra', 'Calculus', 'Probability'], resources: [], milestones: ['Complete MIT 18.06', 'Python proficiency'], order: 1 },
      { id: 's2', title: 'ML Foundations', description: 'Learn core ML algorithms and frameworks.', duration: '3–5 months', skills: ['Scikit-learn', 'Supervised Learning', 'Unsupervised Learning', 'Model Evaluation'], resources: [], milestones: ['Andrew Ng ML Course', 'Kaggle competitions'], order: 2 },
      { id: 's3', title: 'Deep Learning', description: 'Master neural networks, CNNs, RNNs, and transformers.', duration: '3–5 months', skills: ['PyTorch', 'TensorFlow', 'NLP', 'Computer Vision', 'Transformers'], resources: [], milestones: ['fast.ai courses', 'Build an LLM project'], order: 3 },
      { id: 's4', title: 'Production ML', description: 'Learn to deploy and maintain ML systems in production.', duration: '2–4 months', skills: ['MLOps', 'Docker', 'Cloud ML', 'Model Monitoring'], resources: [], milestones: ['Deploy an ML API', 'End-to-end project'], order: 4 },
    ],
  },
  {
    id: 'career-11',
    title: 'Cybersecurity Analyst',
    slug: 'cybersecurity-analyst',
    field: 'Technology',
    subfield: 'Information Security',
    description: 'Protect organizations from cyber threats by monitoring systems, investigating breaches, and implementing security measures.',
    shortDescription: 'Defend systems and data from cyber threats.',
    avgSalaryIndia: '₹6–25 LPA',
    avgSalaryGlobal: '$70K–$160K',
    demandTrend: 'rising',
    relatedCareers: ['career-1', 'career-16'],
    tags: ['security', 'hacking', 'SOC', 'penetration testing'],
    icon: 'Shield',
    roadmapShUrl: 'https://roadmap.sh/cyber-security',
    stages: [
      { id: 's1', title: 'Networking', description: 'Learn TCP/IP, DNS, and Linux.', duration: '2 months', skills: ['Networking', 'Linux'], resources: [], milestones: ['Set up a secure lab'], order: 1 },
      { id: 's2', title: 'Security Basics', description: 'Learn threats and defense.', duration: '3 months', skills: ['Security+', 'SIEM'], resources: [], milestones: ['Security+ cert'], order: 2 },
    ],
  },
  {
    id: 'career-16',
    title: 'DevOps Engineer',
    slug: 'devops-engineer',
    field: 'Technology',
    subfield: 'DevOps & Cloud',
    description: 'Bridge the gap between development and operations. Automate everything.',
    shortDescription: 'Automate, deploy, and scale infrastructure.',
    avgSalaryIndia: '₹8–30 LPA',
    avgSalaryGlobal: '$80K–$170K',
    demandTrend: 'rising',
    relatedCareers: ['career-1', 'career-21'],
    tags: ['devops', 'cloud', 'aws'],
    icon: 'Cloud',
    roadmapShUrl: 'https://roadmap.sh/devops',
    stages: [
      { id: 's1', title: 'Linux', description: 'Master the command line.', duration: '2 months', skills: ['Linux', 'Bash'], resources: [], milestones: ['Linux cert'], order: 1 },
    ],
  },
  {
    id: 'career-21',
    title: 'Cloud Architect',
    slug: 'cloud-architect',
    field: 'Technology',
    subfield: 'Cloud Infrastructure',
    description: 'Design and manage complex cloud architectures on AWS, Azure, or GCP.',
    shortDescription: 'Design scalable cloud ecosystems.',
    avgSalaryIndia: '₹15–45 LPA',
    avgSalaryGlobal: '$120K–$220K',
    demandTrend: 'rising',
    relatedCareers: ['career-16'],
    tags: ['aws', 'azure', 'cloud', 'architecture'],
    icon: 'Cloud',
    roadmapShUrl: 'https://roadmap.sh/aws',
    stages: [
      { id: 's1', title: 'Cloud Basics', description: 'Learn IaaS, PaaS, and SaaS.', duration: '2 months', skills: ['AWS Basics'], resources: [], milestones: ['Practitioner Cert'], order: 1 },
    ],
  },
  {
    id: 'career-22',
    title: 'Data Engineer',
    slug: 'data-engineer',
    field: 'Data Science',
    subfield: 'Infrastructure',
    description: 'Build the pipelines that collect and process massive datasets.',
    shortDescription: 'Build high-performance data pipelines.',
    avgSalaryIndia: '₹10–35 LPA',
    avgSalaryGlobal: '$90K–$180K',
    demandTrend: 'rising',
    relatedCareers: ['career-2'],
    tags: ['etl', 'spark', 'sql', 'big data'],
    icon: 'BarChart3',
    roadmapShUrl: 'https://roadmap.sh/data-engineer',
    stages: [
      { id: 's1', title: 'SQL & Python', description: 'Foundation of data moving.', duration: '3 months', skills: ['SQL', 'Python'], resources: [], milestones: ['Build an ETL pipeline'], order: 1 },
    ],
  },
  {
    id: 'career-23',
    title: 'Product Designer',
    slug: 'product-designer',
    field: 'Design',
    subfield: 'UI/UX',
    description: 'A holistic role combining UX, UI, and business strategy.',
    shortDescription: 'Own the end-to-end design process.',
    avgSalaryIndia: '₹8–30 LPA',
    avgSalaryGlobal: '$80K–$160K',
    demandTrend: 'rising',
    relatedCareers: ['career-3'],
    tags: ['design', 'product', 'figma'],
    icon: 'Palette',
    roadmapShUrl: 'https://roadmap.sh/ux-design',
    stages: [
      { id: 's1', title: 'Visual Design', description: 'Master layout and color.', duration: '3 months', skills: ['UI Design'], resources: [], milestones: ['Portfolio launch'], order: 1 },
    ],
  },
  {
    id: 'career-24',
    title: 'Blockchain Developer',
    slug: 'blockchain-developer',
    field: 'Technology',
    subfield: 'Web3',
    description: 'Build decentralized applications and smart contracts.',
    shortDescription: 'Build the future of decentralized finance.',
    avgSalaryIndia: '₹12–40 LPA',
    avgSalaryGlobal: '$100K–$220K',
    demandTrend: 'rising',
    relatedCareers: ['career-1'],
    tags: ['solidity', 'web3', 'ethereum'],
    icon: 'Code',
    roadmapShUrl: 'https://roadmap.sh/blockchain',
    stages: [
      { id: 's1', title: 'Smart Contracts', description: 'Learn Solidity.', duration: '4 months', skills: ['Solidity'], resources: [], milestones: ['Deploy a token'], order: 1 },
    ],
  },
  {
    id: 'career-25',
    title: 'Backend Engineer',
    slug: 'backend-engineer',
    field: 'Technology',
    subfield: 'Development',
    description: 'Focus on the server-side logic and database architecture.',
    shortDescription: 'Engine the brains behind the software.',
    avgSalaryIndia: '₹10–35 LPA',
    avgSalaryGlobal: '$90K–$180K',
    demandTrend: 'rising',
    relatedCareers: ['career-1'],
    tags: ['node', 'go', 'system design'],
    icon: 'Monitor',
    roadmapShUrl: 'https://roadmap.sh/backend',
    stages: [
      { id: 's1', title: 'Architecture', description: 'Learn API design.', duration: '3 months', skills: ['Node.js'], resources: [], milestones: ['Build a robust API'], order: 1 },
    ],
  },
  {
    id: 'career-26',
    title: 'Frontend Engineer',
    slug: 'frontend-engineer',
    field: 'Technology',
    subfield: 'Development',
    description: 'Craft the visual and interactive parts of websites.',
    shortDescription: 'Build stunning user interfaces.',
    avgSalaryIndia: '₹8–28 LPA',
    avgSalaryGlobal: '$80K–$160K',
    demandTrend: 'rising',
    relatedCareers: ['career-1'],
    tags: ['react', 'nextjs', 'css'],
    icon: 'Palette',
    roadmapShUrl: 'https://roadmap.sh/frontend',
    stages: [
      { id: 's1', title: 'React Mastery', description: 'Master modern React.', duration: '3 months', skills: ['React'], resources: [], milestones: ['Build a dashboard'], order: 1 },
    ],
  },
  {
    id: 'career-27',
    title: 'Mobile Developer (Flutter)',
    slug: 'mobile-developer-flutter',
    field: 'Technology',
    subfield: 'Mobile',
    description: 'Build cross-platform mobile apps for iOS and Android.',
    shortDescription: 'Craft beautiful mobile experiences.',
    avgSalaryIndia: '₹6–22 LPA',
    avgSalaryGlobal: '$70K–$150K',
    demandTrend: 'rising',
    relatedCareers: ['career-1'],
    tags: ['dart', 'flutter', 'mobile'],
    icon: 'Monitor',
    roadmapShUrl: 'https://roadmap.sh/flutter',
    stages: [
      { id: 's1', title: 'Dart Foundations', description: 'Learn Dart language.', duration: '2 months', skills: ['Dart'], resources: [], milestones: ['Hello World app'], order: 1 },
    ],
  },
  {
    id: 'career-28',
    title: 'Game Developer (Unity)',
    slug: 'game-developer-unity',
    field: 'Technology',
    subfield: 'Game Dev',
    description: 'Build 2D and 3D games for PC, console, and mobile.',
    shortDescription: 'Create immersive virtual worlds.',
    avgSalaryIndia: '₹5–20 LPA',
    avgSalaryGlobal: '$60K–$140K',
    demandTrend: 'rising',
    relatedCareers: ['career-1'],
    tags: ['c#', 'unity', '3d'],
    icon: 'Rocket',
    roadmapShUrl: 'https://roadmap.sh/game-developer',
    stages: [
      { id: 's1', title: 'C# for Unity', description: 'Learn game scripting.', duration: '3 months', skills: ['C#'], resources: [], milestones: ['Build a platformer'], order: 1 },
    ],
  },
  {
    id: 'career-29',
    title: 'SRE (Site Reliability Engineer)',
    slug: 'sre',
    field: 'Technology',
    subfield: 'Operations',
    description: 'Use software engineering to solve infrastructure and operations problems.',
    shortDescription: 'Build highly available distributed systems.',
    avgSalaryIndia: '₹12–40 LPA',
    avgSalaryGlobal: '$110K–$230K',
    demandTrend: 'rising',
    relatedCareers: ['career-16'],
    tags: ['sre', 'automation', 'scaling'],
    icon: 'Shield',
    roadmapShUrl: 'https://roadmap.sh/devops',
    stages: [
      { id: 's1', title: 'Observability', description: 'Learn monitoring.', duration: '3 months', skills: ['Prometheus'], resources: [], milestones: ['Alerting strategy'], order: 1 },
    ],
  },
  {
    id: 'career-30',
    title: 'Full Stack Engineer',
    slug: 'full-stack-engineer',
    field: 'Technology',
    subfield: 'Development',
    description: 'Handle both frontend and backend development.',
    shortDescription: 'The complete architect of the web.',
    avgSalaryIndia: '₹10–35 LPA',
    avgSalaryGlobal: '$90K–$190K',
    demandTrend: 'rising',
    relatedCareers: ['career-25', 'career-26'],
    tags: ['fullstack', 'javascript', 'postgresql'],
    icon: 'Code',
    roadmapShUrl: 'https://roadmap.sh/full-stack',
    stages: [
      { id: 's1', title: 'End-to-End', description: 'Integrate front and back.', duration: '6 months', skills: ['Full Stack'], resources: [], milestones: ['Launch a SaaS'], order: 1 },
    ],
  },
  {
    id: 'career-31',
    title: 'Solution Architect',
    slug: 'solution-architect',
    field: 'Technology',
    subfield: 'Enterprise',
    description: 'Bridge the gap between business problems and technical solutions.',
    shortDescription: 'Design complex enterprise solutions.',
    avgSalaryIndia: '₹18–55 LPA',
    avgSalaryGlobal: '$130K–$240K',
    demandTrend: 'rising',
    relatedCareers: ['career-21'],
    tags: ['enterprise', 'strategy', 'cloud'],
    icon: 'Landmark',
    roadmapShUrl: 'https://roadmap.sh/software-architect',
    stages: [
      { id: 's1', title: 'Design Patterns', description: 'Master architecture patterns.', duration: '4 months', skills: ['Architecture'], resources: [], milestones: ['Large scale design'], order: 1 },
    ],
  },
  {
    id: 'career-32',
    title: 'QA Engineer',
    slug: 'qa-engineer',
    field: 'Technology',
    subfield: 'Quality',
    description: 'Ensure software quality through manual and automated testing.',
    shortDescription: 'Break software before users do.',
    avgSalaryIndia: '₹5–18 LPA',
    avgSalaryGlobal: '$60K–$130K',
    demandTrend: 'stable',
    relatedCareers: ['career-1'],
    tags: ['selenium', 'cypress', 'testing'],
    icon: 'Shield',
    roadmapShUrl: 'https://roadmap.sh/qa',
    stages: [
      { id: 's1', title: 'Automation', description: 'Learn scripting tests.', duration: '3 months', skills: ['Cypress'], resources: [], milestones: ['Automated test suite'], order: 1 },
    ],
  },
  {
    id: 'career-33',
    title: 'Technical Writer',
    slug: 'technical-writer',
    field: 'Media',
    subfield: 'Documentation',
    description: 'Create documentation, tutorials, and guides for developers.',
    shortDescription: 'Explain complex tech clearly.',
    avgSalaryIndia: '₹6–22 LPA',
    avgSalaryGlobal: '$65K–$140K',
    demandTrend: 'rising',
    relatedCareers: ['career-15'],
    tags: ['writing', 'docs', 'markdown'],
    icon: 'BookOpen',
    roadmapShUrl: 'https://roadmap.sh/technical-writer',
    stages: [
      { id: 's1', title: 'Markdown & Docs', description: 'Learn docs as code.', duration: '2 months', skills: ['Markdown'], resources: [], milestones: ['Publish a guide'], order: 1 },
    ],
  },
  {
    id: 'career-34',
    title: 'SEO Specialist',
    slug: 'seo-specialist',
    field: 'Marketing',
    subfield: 'Growth',
    description: 'Optimize websites to rank higher on search engines.',
    shortDescription: 'Dominate search results.',
    avgSalaryIndia: '₹4–15 LPA',
    avgSalaryGlobal: '$50K–$110K',
    demandTrend: 'rising',
    relatedCareers: ['career-12'],
    tags: ['seo', 'analytics', 'content'],
    icon: 'Megaphone',
    roadmapShUrl: 'https://roadmap.sh/seo',
    stages: [
      { id: 's1', title: 'On-Page SEO', description: 'Master content optimization.', duration: '2 months', skills: ['SEO'], resources: [], milestones: ['First page ranking'], order: 1 },
    ],
  },
  {
    id: 'career-35',
    title: 'Customer Success Manager',
    slug: 'customer-success-manager',
    field: 'Business',
    subfield: 'Relationship',
    description: 'Ensure customers achieve their desired outcomes using your product.',
    shortDescription: 'Drive retention and value.',
    avgSalaryIndia: '₹6–24 LPA',
    avgSalaryGlobal: '$60K–$130K',
    demandTrend: 'rising',
    relatedCareers: ['career-8'],
    tags: ['retention', 'crm', 'saas'],
    icon: 'Target',
    stages: [
      { id: 's1', title: 'Onboarding', description: 'Master the first 30 days.', duration: '2 months', skills: ['CRM'], resources: [], milestones: ['Customer success plan'], order: 1 },
    ],
  },
  {
    id: 'career-36',
    title: 'Sales Engineer',
    slug: 'sales-engineer',
    field: 'Technology',
    subfield: 'Sales',
    description: 'Combine technical expertise with sales skills to demo complex software.',
    shortDescription: 'The technical face of sales.',
    avgSalaryIndia: '₹12–40 LPA',
    avgSalaryGlobal: '$100K–$200K',
    demandTrend: 'rising',
    relatedCareers: ['career-1'],
    tags: ['sales', 'demo', 'tech'],
    icon: 'Target',
    stages: [
      { id: 's1', title: 'Demo Craft', description: 'Learn to present tech.', duration: '3 months', skills: ['Public Speaking'], resources: [], milestones: ['Winning demo'], order: 1 },
    ],
  },
  {
    id: 'career-37',
    title: 'HR Manager',
    slug: 'hr-manager',
    field: 'Business',
    subfield: 'People',
    description: 'Manage talent acquisition, employee relations, and company culture.',
    shortDescription: 'Build the heartbeat of the company.',
    avgSalaryIndia: '₹6–28 LPA',
    avgSalaryGlobal: '$55K–$140K',
    demandTrend: 'stable',
    relatedCareers: [],
    tags: ['hiring', 'culture', 'policy'],
    icon: 'Heart',
    stages: [
      { id: 's1', title: 'Recruiting', description: 'Learn to spot talent.', duration: '3 months', skills: ['Hiring'], resources: [], milestones: ['First successful hire'], order: 1 },
    ],
  },
  {
    id: 'career-38',
    title: 'Video Editor',
    slug: 'video-editor',
    field: 'Media',
    subfield: 'Post-Production',
    description: 'Tell stories through visual media using Premiere, Final Cut, or DaVinci.',
    shortDescription: 'Shape the narrative visually.',
    avgSalaryIndia: '₹4–20 LPA',
    avgSalaryGlobal: '$45K–$110K',
    demandTrend: 'rising',
    relatedCareers: ['career-15'],
    tags: ['editing', 'video', 'premiere'],
    icon: 'Monitor',
    stages: [
      { id: 's1', title: 'Cutting Basics', description: 'Master timing and flow.', duration: '3 months', skills: ['Video Editing'], resources: [], milestones: ['Showreel launch'], order: 1 },
    ],
  },
  {
    id: 'career-39',
    title: 'Investment Banker',
    slug: 'investment-banker',
    field: 'Finance',
    subfield: 'Corporate Finance',
    description: 'Help companies raise capital and execute mergers and acquisitions.',
    shortDescription: 'Execute high-stakes finance deals.',
    avgSalaryIndia: '₹15–70 LPA',
    avgSalaryGlobal: '$150K–$400K+',
    demandTrend: 'stable',
    relatedCareers: ['career-4'],
    tags: ['m&a', 'finance', 'ipo'],
    icon: 'TrendingUp',
    stages: [
      { id: 's1', title: 'Modeling', description: 'Build complex valuations.', duration: '6 months', skills: ['LBO Modeling'], resources: [], milestones: ['Deal book creation'], order: 1 },
    ],
  },
  {
    id: 'career-40',
    title: 'System Administrator',
    slug: 'system-administrator',
    field: 'Technology',
    subfield: 'IT Ops',
    description: 'Manage and maintain the physical and virtual server infrastructure.',
    shortDescription: 'Keep the lights on for IT.',
    avgSalaryIndia: '₹5–18 LPA',
    avgSalaryGlobal: '$60K–$130K',
    demandTrend: 'stable',
    relatedCareers: ['career-16'],
    tags: ['linux', 'windows', 'servers'],
    icon: 'Monitor',
    roadmapShUrl: 'https://roadmap.sh/linux',
    stages: [
      { id: 's1', title: 'Server Setup', description: 'Master OS installation.', duration: '3 months', skills: ['Linux'], resources: [], milestones: ['Sysadmin cert'], order: 1 },
    ],
  },
  {
    id: 'career-41',
    title: 'Database Administrator (DBA)',
    slug: 'dba',
    field: 'Technology',
    subfield: 'Data',
    description: 'Manage, maintain, and optimize database systems like PostgreSQL or Oracle.',
    shortDescription: 'The guardian of the data.',
    avgSalaryIndia: '₹8–28 LPA',
    avgSalaryGlobal: '$80K–$160K',
    demandTrend: 'stable',
    relatedCareers: ['career-22'],
    tags: ['sql', 'postgres', 'optimization'],
    icon: 'BarChart3',
    roadmapShUrl: 'https://roadmap.sh/postgresql-dba',
    stages: [
      { id: 's1', title: 'Performance', description: 'Learn indexing and tuning.', duration: '4 months', skills: ['SQL'], resources: [], milestones: ['Optimization report'], order: 1 },
    ],
  },
  {
    id: 'career-42',
    title: 'Motion Designer',
    slug: 'motion-designer',
    field: 'Design',
    subfield: 'Animation',
    description: 'Bring static designs to life through animation and motion graphics.',
    shortDescription: 'Animate the digital experience.',
    avgSalaryIndia: '₹6–24 LPA',
    avgSalaryGlobal: '$60K–$130K',
    demandTrend: 'rising',
    relatedCareers: ['career-3', 'career-38'],
    tags: ['after effects', 'animation', 'lottie'],
    icon: 'Star',
    stages: [
      { id: 's1', title: 'After Effects', description: 'Learn the primary tool.', duration: '4 months', skills: ['Animation'], resources: [], milestones: ['Motion reel'], order: 1 },
    ],
  },
  {
    id: 'career-43',
    title: 'Cybersecurity Manager',
    slug: 'cybersecurity-manager',
    field: 'Technology',
    subfield: 'Security',
    description: 'Lead the security team and define organizational security policy.',
    shortDescription: 'Strategize the defense of the firm.',
    avgSalaryIndia: '₹20–60 LPA',
    avgSalaryGlobal: '$140K–$260K',
    demandTrend: 'rising',
    relatedCareers: ['career-11'],
    tags: ['governance', 'risk', 'compliance'],
    icon: 'Shield',
    stages: [
      { id: 's1', title: 'Compliance', description: 'Learn ISO and SOC2.', duration: '6 months', skills: ['Compliance'], resources: [], milestones: ['CISM Cert'], order: 1 },
    ],
  },
  {
    id: 'career-44',
    title: 'Business Analyst',
    slug: 'business-analyst',
    field: 'Business',
    subfield: 'Analysis',
    description: 'Analyze business processes and requirements to improve efficiency.',
    shortDescription: 'Optimize the way business works.',
    avgSalaryIndia: '₹6–22 LPA',
    avgSalaryGlobal: '$65K–$130K',
    demandTrend: 'stable',
    relatedCareers: ['career-4'],
    tags: ['agile', 'requirements', 'data'],
    icon: 'Landmark',
    stages: [
      { id: 's1', title: 'Req Gathering', description: 'Learn to talk to users.', duration: '3 months', skills: ['Agile'], resources: [], milestones: ['First BRD'], order: 1 },
    ],
  },
  {
    id: 'career-45',
    title: 'Scrum Master',
    slug: 'scrum-master',
    field: 'Technology',
    subfield: 'Management',
    description: 'Facilitate agile teams and ensure Scrum practices are followed.',
    shortDescription: 'Enable high-performing teams.',
    avgSalaryIndia: '₹10–35 LPA',
    avgSalaryGlobal: '$80K–$150K',
    demandTrend: 'stable',
    relatedCareers: ['career-8'],
    tags: ['agile', 'scrum', 'leadership'],
    icon: 'CheckCircle2',
    stages: [
      { id: 's1', title: 'Facilitation', description: 'Master the ceremonies.', duration: '2 months', skills: ['Scrum'], resources: [], milestones: ['PSM I Cert'], order: 1 },
    ],
  },
  {
    id: 'career-46',
    title: 'Growth Hacker',
    slug: 'growth-hacker',
    field: 'Marketing',
    subfield: 'Growth',
    description: 'Use experimentation and analytics to drive rapid business growth.',
    shortDescription: 'Engineer viral growth.',
    avgSalaryIndia: '₹10–35 LPA',
    avgSalaryGlobal: '$90K–$180K',
    demandTrend: 'rising',
    relatedCareers: ['career-12'],
    tags: ['conversion', 'virality', 'data'],
    icon: 'Target',
    stages: [
      { id: 's1', title: 'Funnel Logic', description: 'Master the pirate metrics.', duration: '3 months', skills: ['A/B Testing'], resources: [], milestones: ['Growth experiment'], order: 1 },
    ],
  },
  {
    id: 'career-47',
    title: 'Embedded Systems Engineer',
    slug: 'embedded-systems-engineer',
    field: 'Engineering',
    subfield: 'Hardware',
    description: 'Design and program software for hardware devices like IoT or robotics.',
    shortDescription: 'Program the physical world.',
    avgSalaryIndia: '₹6–25 LPA',
    avgSalaryGlobal: '$80K–$160K',
    demandTrend: 'rising',
    relatedCareers: ['career-1'],
    tags: ['c', 'firmware', 'iot'],
    icon: 'Monitor',
    stages: [
      { id: 's1', title: 'C for Hardware', description: 'Master low-level code.', duration: '4 months', skills: ['C'], resources: [], milestones: ['First IoT project'], order: 1 },
    ],
  },
  {
    id: 'career-48',
    title: 'Mechanical Designer',
    slug: 'mechanical-designer',
    field: 'Engineering',
    subfield: 'CAD',
    description: 'Create detailed technical drawings and models of mechanical parts.',
    shortDescription: 'Draft the machines of tomorrow.',
    avgSalaryIndia: '₹4–15 LPA',
    avgSalaryGlobal: '$50K–$110K',
    demandTrend: 'stable',
    relatedCareers: ['career-14'],
    tags: ['solidworks', 'cad', 'drafting'],
    icon: 'Wrench',
    stages: [
      { id: 's1', title: 'CAD Mastery', description: 'Master SolidWorks.', duration: '4 months', skills: ['CAD'], resources: [], milestones: ['Technical drawing suite'], order: 1 },
    ],
  },
  {
    id: 'career-49',
    title: 'Supply Chain Manager',
    slug: 'supply-chain-manager',
    field: 'Business',
    subfield: 'Logistics',
    description: 'Coordinate the movement of goods from suppliers to customers.',
    shortDescription: 'Engine the flow of global commerce.',
    avgSalaryIndia: '₹6–30 LPA',
    avgSalaryGlobal: '$60K–$140K',
    demandTrend: 'stable',
    relatedCareers: [],
    tags: ['logistics', 'operations', 'erp'],
    icon: 'Landmark',
    stages: [
      { id: 's1', title: 'Logistics', description: 'Learn freight and storage.', duration: '3 months', skills: ['Logistics'], resources: [], milestones: ['Supply chain audit'], order: 1 },
    ],
  },
  {
    id: 'career-50',
    title: 'UI Developer',
    slug: 'ui-developer',
    field: 'Technology',
    subfield: 'Frontend',
    description: 'A developer focused on high-fidelity visual implementation and animation.',
    shortDescription: 'The pixel-perfect engineer.',
    avgSalaryIndia: '₹6–22 LPA',
    avgSalaryGlobal: '$70K–$150K',
    demandTrend: 'rising',
    relatedCareers: ['career-26'],
    tags: ['css', 'animation', 'framer motion'],
    icon: 'Star',
    stages: [
      { id: 's1', title: 'Visual Code', description: 'Master CSS and SVG.', duration: '3 months', skills: ['CSS'], resources: [], milestones: ['Motion portfolio'], order: 1 },
    ],
  },
];
