import type { Career } from '@/types';

export const careers: Career[] = [
  {
    id: 'career-1',
    title: 'Frontend Developer',
    slug: 'frontend-developer',
    field: 'Technology',
    subfield: 'Web Development',
    description: 'Build the user-facing side of websites and web applications. Frontend developers work with HTML, CSS, JavaScript, and modern frameworks like React.',
    shortDescription: 'Build the visual components of websites and apps.',
    avgSalaryIndia: 'Entry: ₹4–7 LPA | Mid: ₹8–15 LPA | Sr: ₹16–25+ LPA',
    avgSalaryGlobal: 'Entry: $50K–$75K | Mid: $80K–$120K | Sr: $130K–$160K+',
    demandTrend: 'rising',
    relatedCareers: ['career-4'],
    tags: ['coding', 'web', 'frontend', 'react', 'javascript', 'html', 'css', 'typescript', 'nextjs'],
    aliases: ['react developer', 'nextjs developer', 'web developer', 'ui developer', 'javascript developer', 'frontend engineer', 'solidjs', 'wordpress developer', 'shopify developer'],
    icon: 'Monitor',
    roadmapShUrl: 'https://roadmap.sh/frontend',
    stages: [
      { id: 'f1', title: 'Internet & HTML', description: 'Learn how the web works and basic markup.', duration: '2 weeks', skills: ['HTML', 'HTTP'], resources: [], milestones: ['Build a basic HTML site'], order: 1 },
      { id: 'f2', title: 'Styling (CSS)', description: 'Learn to style web pages and layout systems.', duration: '1 month', skills: ['CSS', 'Flexbox', 'Grid'], resources: [], milestones: ['Clone a landing page'], order: 2 },
      { id: 'f3', title: 'JavaScript Basics', description: 'Make websites interactive with JS.', duration: '2 months', skills: ['JavaScript', 'DOM Manipulation'], resources: [], milestones: ['Build an interactive calculator'], order: 3 },
      { id: 'f4', title: 'React Ecosystem', description: 'Build component-driven user interfaces.', duration: '2 months', skills: ['React', 'State Management'], resources: [], milestones: ['Build a dynamic Dashboard'], order: 4 },
      { id: 'f5', title: 'Portfolio & Job Readiness', description: 'Prepare for applications and interviews.', duration: '1 month', skills: ['Resume Writing', 'Interview Prep'], resources: [], milestones: ['Deploy 3 Portfolio Projects', 'Publish Portfolio Website'], order: 5 },
    ],
    recommendedResourceIds: [],
    recommendedJobs: []
  },
  {
    id: 'career-2',
    title: 'Backend Developer',
    slug: 'backend-developer',
    field: 'Technology',
    subfield: 'Web Development',
    description: 'Build the server-side logic, databases, and APIs that power web applications. Backend developers focus on architecture, performance, and security.',
    shortDescription: 'Build the APIs and databases powering the web.',
    avgSalaryIndia: 'Entry: ₹5–8 LPA | Mid: ₹9–18 LPA | Sr: ₹19–30+ LPA',
    avgSalaryGlobal: 'Entry: $60K–$85K | Mid: $90K–$130K | Sr: $140K–$170K+',
    demandTrend: 'rising',
    relatedCareers: ['career-4', 'career-10'],
    tags: ['coding', 'web', 'backend', 'node', 'nodejs', 'sql', 'python', 'api'],
    aliases: ['node developer', 'python developer', 'django developer', 'api developer', 'backend engineer', 'server engineer', 'golang developer', 'c++ developer'],
    icon: 'Code',
    roadmapShUrl: 'https://roadmap.sh/backend',
    stages: [
      { id: 'b1', title: 'Programming Fundamentals', description: 'Learn a backend language like Node.js or Python.', duration: '2 months', skills: ['JavaScript', 'Python'], resources: [], milestones: ['Build a CLI application'], order: 1 },
      { id: 'b2', title: 'Databases & SQL', description: 'Learn to store and query data.', duration: '1 month', skills: ['SQL', 'PostgreSQL'], resources: [], milestones: ['Design a relational schema'], order: 2 },
      { id: 'b3', title: 'APIs & Servers', description: 'Learn to build REST APIs and servers.', duration: '2 months', skills: ['Express', 'REST', 'HTTP'], resources: [], milestones: ['Build a RESTful API'], order: 3 },
      { id: 'b4', title: 'Security & Deployment', description: 'Secure your APIs and deploy them.', duration: '1 month', skills: ['Authentication', 'Docker', 'AWS'], resources: [], milestones: ['Deploy API to the cloud'], order: 4 },
      { id: 'b5', title: 'Portfolio & Job Readiness', description: 'Prepare for applications and interviews.', duration: '1 month', skills: ['Resume Writing', 'Interview Prep'], resources: [], milestones: ['Deploy 3 Backend Projects', 'Publish Portfolio Website'], order: 5 },
    ],
    recommendedResourceIds: [],
    recommendedJobs: []
  },
  {
    id: 'career-3',
    title: 'Java Developer',
    slug: 'java-developer',
    field: 'Technology',
    subfield: 'Enterprise Software',
    description: 'Build enterprise-scale applications and systems using Java. Java developers work heavily with the Spring framework, microservices, and robust backend systems.',
    shortDescription: 'Build enterprise-grade systems with Java and Spring.',
    avgSalaryIndia: 'Entry: ₹5–8 LPA | Mid: ₹9–18 LPA | Sr: ₹19–35+ LPA',
    avgSalaryGlobal: 'Entry: $60K–$85K | Mid: $90K–$130K | Sr: $140K–$170K+',
    demandTrend: 'stable',
    relatedCareers: ['career-2'],
    tags: ['coding', 'java', 'spring', 'springboot', 'backend', 'enterprise', 'oop'],
    aliases: ['java engineer', 'spring boot developer', 'enterprise developer', 'software developer'],
    icon: 'Code',
    roadmapShUrl: 'https://roadmap.sh/java',
    stages: [
      { id: 'j1', title: 'Java Basics & OOP', description: 'Learn Java syntax and object-oriented programming.', duration: '2 months', skills: ['Java', 'OOP', 'Data Structures'], resources: [], milestones: ['Build a console banking app'], order: 1 },
      { id: 'j2', title: 'Build Tools & Git', description: 'Learn Maven/Gradle and version control.', duration: '1 month', skills: ['Maven', 'Git'], resources: [], milestones: ['Manage a project with Maven'], order: 2 },
      { id: 'j3', title: 'Databases & JDBC', description: 'Connect Java to relational databases.', duration: '1 month', skills: ['SQL', 'JDBC', 'Hibernate'], resources: [], milestones: ['Build a CRUD app with a DB'], order: 3 },
      { id: 'j4', title: 'Spring Boot', description: 'Build modern APIs using the Spring framework.', duration: '2 months', skills: ['Spring Boot', 'REST APIs'], resources: [], milestones: ['Build a full Spring API'], order: 4 },
      { id: 'j5', title: 'Portfolio & Job Readiness', description: 'Prepare for applications and interviews.', duration: '1 month', skills: ['Resume Writing', 'Interview Prep'], resources: [], milestones: ['Deploy a Spring Boot Microservice', 'Publish Portfolio Website'], order: 5 },
    ],
    recommendedResourceIds: [],
    recommendedJobs: []
  },
  {
    id: 'career-4',
    title: 'Full Stack Developer',
    slug: 'full-stack-developer',
    field: 'Technology',
    subfield: 'Software Development',
    description: 'Master both the frontend and backend of web applications. Full stack developers build complete end-to-end systems from UI to database.',
    shortDescription: 'Build end-to-end web applications.',
    avgSalaryIndia: 'Entry: ₹6–10 LPA | Mid: ₹11–22 LPA | Sr: ₹23–40+ LPA',
    avgSalaryGlobal: 'Entry: $70K–$95K | Mid: $100K–$140K | Sr: $150K–$190K+',
    demandTrend: 'rising',
    relatedCareers: ['career-1', 'career-2'],
    tags: ['coding', 'web', 'frontend', 'backend', 'react', 'javascript', 'node', 'sql'],
    aliases: ['mern developer', 'mean developer', 'software architect', 'fullstack engineer', 'freelancer', 'remote developer', 'blockchain developer', 'web3 developer', 'solidity developer', 'smart contract engineer', 'solutions engineer', 'product engineer', 'growth engineer', 'startup founder'],
    icon: 'Monitor',
    roadmapShUrl: 'https://roadmap.sh/full-stack',
    stages: [
      { id: 'fs1', title: 'Frontend Basics', description: 'HTML, CSS, and basic JavaScript.', duration: '2 months', skills: ['HTML', 'CSS', 'JavaScript'], resources: [], milestones: ['Build an interactive site'], order: 1 },
      { id: 'fs2', title: 'React & UI', description: 'Build modern frontends with React.', duration: '2 months', skills: ['React'], resources: [], milestones: ['Build a dynamic SPA'], order: 2 },
      { id: 'fs3', title: 'Backend APIs', description: 'Build Node.js and Express servers.', duration: '2 months', skills: ['Node.js', 'Express'], resources: [], milestones: ['Build a REST API'], order: 3 },
      { id: 'fs4', title: 'Databases', description: 'Integrate SQL or NoSQL databases.', duration: '1 month', skills: ['PostgreSQL', 'MongoDB'], resources: [], milestones: ['Build a full-stack CRUD app'], order: 4 },
      { id: 'fs5', title: 'Portfolio & Job Readiness', description: 'Prepare for applications and interviews.', duration: '1 month', skills: ['Resume Writing', 'Interview Prep'], resources: [], milestones: ['Deploy 3 Full-Stack Projects', 'Publish Portfolio Website'], order: 5 },
    ],
    recommendedResourceIds: [],
    recommendedJobs: []
  },
  {
    id: 'career-5',
    title: 'Data Scientist',
    slug: 'data-scientist',
    field: 'Data Science',
    subfield: 'Analytics & ML',
    description: 'Extract insights from data using statistics, machine learning, and domain expertise. Data scientists solve complex business problems by analyzing patterns in large datasets.',
    shortDescription: 'Turn data into actionable insights and predictions.',
    avgSalaryIndia: 'Entry: ₹6–9 LPA | Mid: ₹10–20 LPA | Sr: ₹21–35+ LPA',
    avgSalaryGlobal: 'Entry: $65K–$90K | Mid: $95K–$135K | Sr: $140K–$180K+',
    demandTrend: 'rising',
    relatedCareers: ['career-6'],
    tags: ['data', 'machine learning', 'statistics', 'python', 'analytics', 'sql'],
    aliases: ['data engineer', 'machine learning researcher', 'statistician'],
    icon: 'BarChart3',
    roadmapShUrl: 'https://roadmap.sh/ai-data-scientist',
    stages: [
      { id: 'ds1', title: 'Python Fundamentals', description: 'Learn programming basics for data.', duration: '2 months', skills: ['Python'], resources: [], milestones: ['Build a CLI data tool'], order: 1 },
      { id: 'ds2', title: 'SQL & Databases', description: 'Learn to extract and manipulate data.', duration: '1 month', skills: ['SQL'], resources: [], milestones: ['Write complex JOIN queries'], order: 2 },
      { id: 'ds3', title: 'Math & Stats', description: 'Build a strong foundation in statistics.', duration: '2 months', skills: ['Statistics', 'Linear Algebra', 'Probability'], resources: [], milestones: ['Complete statistical analysis project'], order: 3 },
      { id: 'ds4', title: 'Data Wrangling', description: 'Learn to collect, clean, and transform data.', duration: '2 months', skills: ['Pandas', 'NumPy'], resources: [], milestones: ['Analyze a real dataset'], order: 4 },
      { id: 'ds5', title: 'Portfolio & Job Readiness', description: 'Prepare for applications and interviews.', duration: '1 month', skills: ['Resume Writing', 'Interview Prep'], resources: [], milestones: ['Publish 3 GitHub Data Projects', 'Publish Portfolio Website'], order: 5 },
    ],
    recommendedResourceIds: [],
    recommendedJobs: []
  },
  {
    id: 'career-6',
    title: 'AI Engineer',
    slug: 'ai-engineer',
    field: 'Technology',
    subfield: 'Artificial Intelligence',
    description: 'Build and deploy machine learning models and AI systems at scale. Work on everything from recommendation engines to autonomous systems and large language models.',
    shortDescription: 'Build intelligent systems that learn and adapt.',
    avgSalaryIndia: 'Entry: ₹7–11 LPA | Mid: ₹12–25 LPA | Sr: ₹26–50+ LPA',
    avgSalaryGlobal: 'Entry: $80K–$110K | Mid: $120K–$180K | Sr: $190K–$250K+',
    demandTrend: 'rising',
    relatedCareers: ['career-5'],
    tags: ['ai', 'machine learning', 'deep learning', 'python', 'neural networks'],
    aliases: ['ai researcher', 'prompt engineer', 'machine learning engineer', 'llm engineer', 'nlp engineer'],
    icon: 'Brain',
    roadmapShUrl: 'https://roadmap.sh/ai-engineer',
    stages: [
      { id: 'ai1', title: 'Python & Math Foundations', description: 'Master Python, linear algebra, calculus, and probability.', duration: '3 months', skills: ['Python', 'Linear Algebra', 'Calculus'], resources: [], milestones: ['Implement mathematical algorithms in Python'], order: 1 },
      { id: 'ai2', title: 'Machine Learning & Evaluation', description: 'Learn core ML algorithms, model evaluation metrics, and frameworks.', duration: '3 months', skills: ['Scikit-learn', 'Model Evaluation'], resources: [], milestones: ['Win a Kaggle competition'], order: 2 },
      { id: 'ai3', title: 'Deep Learning & NLP', description: 'Master neural networks, computer vision, and NLP foundations.', duration: '4 months', skills: ['PyTorch', 'NLP', 'Computer Vision'], resources: [], milestones: ['Train a Neural Network from scratch'], order: 3 },
      { id: 'ai4', title: 'Modern LLMs & RAG', description: 'Learn Retrieval-Augmented Generation (RAG), Vector Databases (Chroma/Pinecone), and LLM orchestration frameworks (LangChain/LlamaIndex).', duration: '2 months', skills: ['RAG', 'Vector Databases', 'AI Agents'], resources: [], milestones: ['Build a RAG chatbot using a local vector database'], order: 4 },
      { id: 'ai5', title: 'Model Deployment & MLOps', description: 'Learn model deployment, API wrapper construction, monitoring, and MLOps tools.', duration: '2 months', skills: ['FastAPI', 'Docker', 'MLOps'], resources: [], milestones: ['Deploy model via REST API and automate monitoring container'], order: 5 },
    ],
    recommendedResourceIds: [],
    recommendedJobs: []
  },
  {
    id: 'career-7',
    title: 'DevOps Engineer',
    slug: 'devops-engineer',
    field: 'Technology',
    subfield: 'DevOps & Cloud',
    description: 'Bridge the gap between development and operations. Automate infrastructure, deploy scalable architectures, and ensure high availability.',
    shortDescription: 'Automate, deploy, and scale cloud infrastructure.',
    avgSalaryIndia: 'Entry: ₹6–9 LPA | Mid: ₹10–20 LPA | Sr: ₹21–35+ LPA',
    avgSalaryGlobal: 'Entry: $70K–$95K | Mid: $100K–$140K | Sr: $150K–$190K+',
    demandTrend: 'rising',
    relatedCareers: ['career-2'],
    tags: ['devops', 'cloud', 'aws', 'linux', 'docker', 'kubernetes', 'ci/cd', 'terraform'],
    aliases: ['sre engineer', 'site reliability engineer', 'platform engineer', 'cloud engineer', 'aws engineer', 'infrastructure engineer'],
    icon: 'Cloud',
    roadmapShUrl: 'https://roadmap.sh/devops',
    stages: [
      { id: 'd1', title: 'Linux & Networking', description: 'Master the command line and core networking concepts.', duration: '2 months', skills: ['Linux', 'Bash', 'TCP/IP', 'DNS'], resources: [], milestones: ['Set up a secure Linux server'], order: 1 },
      { id: 'd2', title: 'Containers', description: 'Learn to package applications.', duration: '1 month', skills: ['Docker'], resources: [], milestones: ['Deploy a containerized microservice'], order: 2 },
      { id: 'd3', title: 'Cloud & CI/CD', description: 'Master AWS and automated deployments.', duration: '2 months', skills: ['AWS', 'GitHub Actions'], resources: [], milestones: ['Build a fully automated CI/CD pipeline'], order: 3 },
      { id: 'd4', title: 'Infrastructure as Code', description: 'Automate infrastructure provisioning.', duration: '2 months', skills: ['Terraform', 'Kubernetes'], resources: [], milestones: ['Deploy an EKS cluster with Terraform'], order: 4 },
      { id: 'd5', title: 'Portfolio & Job Readiness', description: 'Prepare for applications and interviews.', duration: '1 month', skills: ['Resume Writing', 'Interview Prep'], resources: [], milestones: ['Publish 3 DevOps Projects', 'Publish Portfolio Website'], order: 5 },
    ],
    recommendedResourceIds: [],
    recommendedJobs: []
  },
  {
    id: 'career-8',
    title: 'Mobile Developer',
    slug: 'mobile-developer',
    field: 'Technology',
    subfield: 'Software Development',
    description: 'Build native and cross-platform applications for iOS and Android devices.',
    shortDescription: 'Build the apps people use every day.',
    avgSalaryIndia: 'Entry: ₹5–8 LPA | Mid: ₹9–15 LPA | Sr: ₹16–25+ LPA',
    avgSalaryGlobal: 'Entry: $60K–$85K | Mid: $90K–$120K | Sr: $130K–$160K+',
    demandTrend: 'rising',
    relatedCareers: ['career-1'],
    tags: ['mobile', 'android', 'ios', 'flutter', 'dart', 'react native'],
    aliases: ['android developer', 'ios developer', 'flutter developer', 'react native developer', 'app developer'],
    icon: 'Monitor',
    roadmapShUrl: 'https://roadmap.sh/android',
    stages: [
      { id: 'm1', title: 'Programming Fundamentals', description: 'Learn Dart or Kotlin.', duration: '2 months', skills: ['Dart', 'Kotlin'], resources: [], milestones: ['Build a CLI application'], order: 1 },
      { id: 'm2', title: 'UI Frameworks', description: 'Learn to build beautiful mobile interfaces.', duration: '2 months', skills: ['Flutter', 'State Management'], resources: [], milestones: ['Build a Weather App'], order: 2 },
      { id: 'm3', title: 'Backend Integration', description: 'Connect apps to APIs and databases.', duration: '2 months', skills: ['REST APIs', 'Firebase'], resources: [], milestones: ['Build a full-stack chat app'], order: 3 },
      { id: 'm4', title: 'Portfolio & Job Readiness', description: 'Prepare for applications and interviews.', duration: '1 month', skills: ['Resume Writing', 'Interview Prep'], resources: [], milestones: ['Publish App to Play Store', 'Publish Portfolio Website'], order: 4 },
    ],
    recommendedResourceIds: [],
    recommendedJobs: []
  },
  {
    id: 'career-9',
    title: 'UX Designer',
    slug: 'ux-designer',
    field: 'Design',
    subfield: 'User Experience',
    description: 'Create intuitive, accessible, and delightful digital experiences. UX designers research user needs, prototype solutions, and work closely with engineering teams.',
    shortDescription: 'Design digital products people love to use.',
    avgSalaryIndia: 'Entry: ₹4–7 LPA | Mid: ₹8–15 LPA | Sr: ₹16–25+ LPA',
    avgSalaryGlobal: 'Entry: $50K–$75K | Mid: $80K–$120K | Sr: $130K–$160K+',
    demandTrend: 'rising',
    relatedCareers: ['career-1'],
    tags: ['design', 'user research', 'figma', 'prototyping', 'ui'],
    aliases: ['ui designer', 'product designer', 'ux researcher', 'interaction designer'],
    icon: 'Palette',
    roadmapShUrl: 'https://roadmap.sh/ux-design',
    stages: [
      { id: 'ux1', title: 'Design Thinking', description: 'Learn human-centered design principles.', duration: '1 month', skills: ['Design Thinking', 'User Research'], resources: [], milestones: ['Conduct 5 user interviews'], order: 1 },
      { id: 'ux2', title: 'Tools & Wireframing', description: 'Master design tools and visual hierarchy.', duration: '2 months', skills: ['Figma', 'Wireframing'], resources: [], milestones: ['Build a design system'], order: 2 },
      { id: 'ux3', title: 'Prototyping & Testing', description: 'Create interactive prototypes and test them.', duration: '2 months', skills: ['Prototyping', 'Usability Testing'], resources: [], milestones: ['Run a usability test'], order: 3 },
      { id: 'ux4', title: 'Portfolio & Job Readiness', description: 'Build a compelling portfolio and prepare for interviews.', duration: '1 month', skills: ['Case Studies', 'Presentation'], resources: [], milestones: ['Complete 3 case studies', 'Publish Portfolio Website'], order: 4 },
    ],
    recommendedResourceIds: [],
    recommendedJobs: []
  },
  {
    id: 'career-10',
    title: 'Cybersecurity Analyst',
    slug: 'cybersecurity-analyst',
    field: 'Technology',
    subfield: 'Information Security',
    description: 'Protect organizations from cyber threats by monitoring systems, investigating breaches, and implementing security measures.',
    shortDescription: 'Defend systems and data from cyber threats.',
    avgSalaryIndia: 'Entry: ₹4–7 LPA | Mid: ₹8–15 LPA | Sr: ₹16–25+ LPA',
    avgSalaryGlobal: 'Entry: $55K–$80K | Mid: $85K–$125K | Sr: $130K–$170K+',
    demandTrend: 'rising',
    relatedCareers: ['career-7'],
    tags: ['security', 'hacking', 'SOC', 'penetration testing', 'cybersecurity'],
    aliases: ['ethical hacker', 'bug bounty hunter', 'penetration tester', 'security engineer', 'infosec', 'soc analyst', 'blockchain engineer'],
    icon: 'Shield',
    roadmapShUrl: 'https://roadmap.sh/cyber-security',
    stages: [
      { id: 'cy1', title: 'Networking & OS', description: 'Learn TCP/IP, Linux, and Windows Internals.', duration: '2 months', skills: ['Networking', 'Linux'], resources: [], milestones: ['Set up a secure homelab'], order: 1 },
      { id: 'cy2', title: 'Security Basics', description: 'Learn threats and defense mechanisms.', duration: '2 months', skills: ['Security+', 'Cryptography'], resources: [], milestones: ['Complete Security+ curriculum'], order: 2 },
      { id: 'cy3', title: 'Offensive Security', description: 'Understand how attackers think.', duration: '2 months', skills: ['Penetration Testing', 'Web Security'], resources: [], milestones: ['Hack 10 TryHackMe boxes'], order: 3 },
      { id: 'cy4', title: 'Defensive Security', description: 'Learn monitoring and incident response.', duration: '2 months', skills: ['SIEM', 'Incident Response'], resources: [], milestones: ['Write a mock incident report'], order: 4 },
      { id: 'cy5', title: 'Portfolio & Job Readiness', description: 'Prepare for applications and interviews.', duration: '1 month', skills: ['Resume Writing', 'Interview Prep'], resources: [], milestones: ['Publish 3 Security Writeups', 'Publish Portfolio Website'], order: 5 },
    ],
    recommendedResourceIds: [],
    recommendedJobs: []
  },
  {
    id: 'career-11',
    title: 'QA Tester',
    slug: 'qa-tester',
    field: 'Technology',
    subfield: 'Quality Assurance',
    description: 'Ensure software quality by designing and executing tests. QA Engineers write automated test scripts, find bugs, and work closely with developers.',
    shortDescription: 'Lower technical barrier than most engineering paths.',
    avgSalaryIndia: 'Entry: ₹3–6 LPA | Mid: ₹7–12 LPA | Sr: ₹13–20+ LPA',
    avgSalaryGlobal: 'Entry: $45K–$70K | Mid: $75K–$100K | Sr: $105K–$130K+',
    demandTrend: 'rising',
    relatedCareers: ['career-1'],
    tags: ['testing', 'qa', 'automation', 'selenium', 'cypress', 'jest'],
    aliases: ['software tester', 'automation tester', 'manual tester', 'sdet', 'qa engineer', 'test engineer'],
    icon: 'Shield',
    roadmapShUrl: 'https://roadmap.sh/qa',
    stages: [
      { id: 'qa1', title: 'Manual Testing Basics', description: 'Learn testing theory and bug reporting.', duration: '1 month', skills: ['Manual Testing', 'Jira'], resources: [], milestones: ['Write a test plan for a site'], order: 1 },
      { id: 'qa2', title: 'Programming for QA', description: 'Learn JavaScript or Python for automation.', duration: '2 months', skills: ['JavaScript', 'Python'], resources: [], milestones: ['Build basic scripts'], order: 2 },
      { id: 'qa3', title: 'UI & API Automation', description: 'Write automated tests.', duration: '2 months', skills: ['Cypress', 'Selenium', 'Postman'], resources: [], milestones: ['Automate an API test suite'], order: 3 },
      { id: 'qa4', title: 'Portfolio & Job Readiness', description: 'Prepare for applications and interviews.', duration: '1 month', skills: ['Resume Writing', 'Interview Prep'], resources: [], milestones: ['Publish a GitHub QA Framework', 'Publish Portfolio Website'], order: 4 },
    ],
    recommendedResourceIds: [],
    recommendedJobs: []
  },
  {
    id: 'career-12',
    title: 'Data Analyst',
    slug: 'data-analyst',
    field: 'Data Science',
    subfield: 'Analytics & Reporting',
    description: 'Transform raw data into actionable business insights. Data Analysts work heavily with Excel, SQL, and visualization tools like Power BI or Tableau to help businesses make decisions.',
    shortDescription: 'Turn numbers into business decisions.',
    avgSalaryIndia: 'Entry: ₹3–6 LPA | Mid: ₹7–10 LPA | Sr: ₹11–15+ LPA',
    avgSalaryGlobal: 'Entry: $45K–$65K | Mid: $70K–$85K | Sr: $90K–$105K+',
    demandTrend: 'rising',
    relatedCareers: ['career-5'],
    tags: ['data', 'analytics', 'sql', 'excel', 'tableau', 'power bi'],
    aliases: ['business analyst', 'bi analyst', 'reporting analyst', 'data visualizer'],
    icon: 'BarChart3',
    roadmapShUrl: 'https://roadmap.sh/data-analyst',
    stages: [
      { id: 'da1', title: 'Spreadsheets & Fundamentals', description: 'Master Excel/Google Sheets for data manipulation.', duration: '1 month', skills: ['Excel', 'Pivot Tables'], resources: [], milestones: ['Build a sales dashboard in Excel'], order: 1 },
      { id: 'da2', title: 'SQL for Analysis', description: 'Learn to query relational databases.', duration: '2 months', skills: ['SQL', 'PostgreSQL'], resources: [], milestones: ['Write complex JOIN and aggregate queries'], order: 2 },
      { id: 'da3', title: 'Data Visualization', description: 'Build interactive dashboards.', duration: '1 month', skills: ['Tableau', 'Power BI'], resources: [], milestones: ['Publish a public Tableau dashboard'], order: 3 },
      { id: 'da4', title: 'Portfolio & Job Readiness', description: 'Prepare for applications and interviews.', duration: '1 month', skills: ['Resume Writing', 'Interview Prep'], resources: [], milestones: ['Publish 3 GitHub Data Projects', 'Publish Portfolio Website'], order: 4 },
    ],
    recommendedResourceIds: [],
    recommendedJobs: []
  },
  {
    id: 'career-13',
    title: 'Game Developer',
    slug: 'game-developer',
    field: 'Technology',
    subfield: 'Game Development',
    description: 'Design and build interactive games for PC, console, or mobile. Game developers use engines like Unity or Unreal and languages like C# and C++.',
    shortDescription: 'Create interactive digital worlds and experiences.',
    avgSalaryIndia: 'Entry: ₹4–7 LPA | Mid: ₹8–13 LPA | Sr: ₹14–20+ LPA',
    avgSalaryGlobal: 'Entry: $45K–$70K | Mid: $75K–$100K | Sr: $105K–$130K+',
    demandTrend: 'stable',
    relatedCareers: ['career-2'],
    tags: ['game dev', 'unity', 'unreal', 'c#', 'c++', '3d'],
    aliases: ['unity developer', 'unreal developer', 'game programmer', 'gameplay engineer'],
    icon: 'Gamepad2',
    roadmapShUrl: 'https://roadmap.sh/game-developer',
    stages: [
      { id: 'gd1', title: 'Programming Fundamentals', description: 'Learn C# or C++ logic and OOP.', duration: '2 months', skills: ['C#', 'C++'], resources: [], milestones: ['Build a text-based adventure game'], order: 1 },
      { id: 'gd2', title: 'Game Engines', description: 'Master Unity or Unreal Engine.', duration: '2 months', skills: ['Unity', 'Unreal'], resources: [], milestones: ['Build a basic 2D platformer'], order: 2 },
      { id: 'gd3', title: 'Advanced Mechanics', description: 'Learn physics, AI, and graphics.', duration: '2 months', skills: ['Game Physics', '3D Math'], resources: [], milestones: ['Build a 3D FPS prototype'], order: 3 },
      { id: 'gd4', title: 'Portfolio & Job Readiness', description: 'Prepare for applications and interviews.', duration: '1 month', skills: ['Resume Writing', 'Interview Prep'], resources: [], milestones: ['Publish Game to Itch.io', 'Publish Portfolio Website'], order: 4 },
    ],
    recommendedResourceIds: [],
    recommendedJobs: []
  },
  {
    id: 'career-14',
    title: 'Technical Writer',
    slug: 'technical-writer',
    field: 'Technology',
    subfield: 'Documentation',
    description: 'Translate complex technical concepts into clear, user-friendly documentation. Technical writers create API docs, tutorials, and manuals for developers and users.',
    shortDescription: 'Write the documentation that developers rely on.',
    avgSalaryIndia: 'Entry: ₹3–6 LPA | Mid: ₹7–11 LPA | Sr: ₹12–18+ LPA',
    avgSalaryGlobal: 'Entry: $45K–$65K | Mid: $70K–$90K | Sr: $95K–$115K+',
    demandTrend: 'stable',
    relatedCareers: ['career-1'],
    tags: ['writing', 'documentation', 'markdown', 'api docs', 'communication'],
    aliases: ['developer advocate', 'documentation engineer', 'tech writer'],
    icon: 'BookOpen',
    roadmapShUrl: 'https://roadmap.sh/technical-writer',
    stages: [
      { id: 'tw1', title: 'Writing Fundamentals', description: 'Learn clear technical communication.', duration: '1 month', skills: ['Grammar', 'Markdown'], resources: [], milestones: ['Write a tutorial for a basic app'], order: 1 },
      { id: 'tw2', title: 'Technical Context', description: 'Understand APIs, Git, and web basics.', duration: '2 months', skills: ['Git', 'APIs', 'HTML/CSS'], resources: [], milestones: ['Document a public REST API'], order: 2 },
      { id: 'tw3', title: 'Doc Tools', description: 'Learn static site generators and doc frameworks.', duration: '1 month', skills: ['Docusaurus', 'Sphinx'], resources: [], milestones: ['Deploy a documentation site'], order: 3 },
      { id: 'tw4', title: 'Portfolio & Job Readiness', description: 'Prepare for applications and interviews.', duration: '1 month', skills: ['Resume Writing', 'Interview Prep'], resources: [], milestones: ['Publish 3 Writing Samples', 'Publish Portfolio Website'], order: 4 },
    ],
    recommendedResourceIds: [],
    recommendedJobs: []
  },
  {
    id: 'career-15',
    title: 'Cloud Engineer',
    slug: 'cloud-engineer',
    field: 'Technology',
    subfield: 'Cloud Architecture',
    description: 'Design, deploy, and manage scalable and highly available applications in cloud environments like AWS, Azure, or GCP.',
    shortDescription: 'Build and manage cloud-based application infrastructures.',
    avgSalaryIndia: 'Entry: ₹5–8 LPA | Mid: ₹9–17 LPA | Sr: ₹18–32+ LPA',
    avgSalaryGlobal: 'Entry: $65K–$90K | Mid: $95K–$130K | Sr: $140K–$180K+',
    demandTrend: 'rising',
    relatedCareers: ['career-7'],
    tags: ['cloud', 'aws', 'devops', 'azure', 'gcp', 'terraform', 'linux'],
    aliases: ['cloud architect', 'aws engineer', 'azure engineer', 'gcp engineer', 'cloud administrator'],
    icon: 'Cloud',
    roadmapShUrl: 'https://roadmap.sh/cloud-engineer',
    stages: [
      { id: 'cl1', title: 'Linux & Core Networking', description: 'Master operating systems and network communications.', duration: '2 months', skills: ['Linux', 'Bash', 'TCP/IP', 'DNS'], resources: [], milestones: ['Configure a secure virtual private cloud'], order: 1 },
      { id: 'cl2', title: 'Cloud Platform Basics (AWS/Azure)', description: 'Learn major compute, storage, and networking services.', duration: '2 months', skills: ['AWS', 'EC2', 'S3', 'IAM'], resources: [], milestones: ['Deploy a high-availability web stack'], order: 2 },
      { id: 'cl3', title: 'Infrastructure as Code (IaC)', description: 'Define infrastructure using code.', duration: '2 months', skills: ['Terraform', 'CloudFormation'], resources: [], milestones: ['Provision AWS resources using Terraform'], order: 3 },
      { id: 'cl4', title: 'Containers & Kubernetes', description: 'Learn microservices packaging and orchestration.', duration: '2 months', skills: ['Docker', 'Kubernetes'], resources: [], milestones: ['Deploy a containerized app to Kubernetes'], order: 4 },
      { id: 'cl5', title: 'Portfolio & Job Readiness', description: 'Prepare cloud certifications and portfolios.', duration: '1 month', skills: ['Resume Writing', 'Interview Prep'], resources: [], milestones: ['Complete AWS Solutions Architect Certificate prep', 'Publish Cloud Portfolio Website'], order: 5 }
    ],
    recommendedResourceIds: [],
    recommendedJobs: []
  }
];
