import type { Resource } from '@/types';

export const resources: Resource[] = [
  // --- PYTHON ---
  { id: 'p1', title: 'Python for Everybody', url: 'https://www.freecodecamp.org/learn/scientific-computing-with-python/', source: 'freeCodeCamp', format: 'COURSE', field: 'Technology', topics: ['Python', 'Backend', 'Data Science'], level: 'beginner', language: 'en', isFree: true, qualityScore: 98, votes: 5000, addedBy: 'team', verified: true, description: 'The absolute best starting point for Python.', duration: 'Self-paced', whyRecommended: 'The gold standard introductory course. Teaches programming logic without getting bogged down in syntax.' },
  { id: 'p2', title: 'Python Official Documentation', url: 'https://docs.python.org/3/', source: 'Official Docs', format: 'DOCUMENTATION', field: 'Technology', topics: ['Python'], level: 'beginner', language: 'en', isFree: true, qualityScore: 95, votes: 2000, addedBy: 'team', verified: true, description: 'The official Python docs. Essential reading for syntax and standard library.', duration: 'Reference', whyRecommended: 'Official language reference. Crucial for understanding pythonic conventions and built-in modules.' },
  { id: 'p3', title: 'Exercism Python Track', url: 'https://exercism.org/tracks/python', source: 'Other', format: 'PRACTICE', field: 'Technology', topics: ['Python', 'Practice'], level: 'beginner', language: 'en', isFree: true, qualityScore: 99, votes: 3000, addedBy: 'team', verified: true, description: 'Interactive Python coding exercises with mentor feedback.', duration: 'Self-paced', whyRecommended: 'Hands-on practice. Helps solidify syntax and features human code reviews for every submit.' },
  { id: 'p4', title: 'Build a Discord Bot in Python', url: 'https://www.freecodecamp.org/news/create-a-discord-bot-with-python/', source: 'freeCodeCamp', format: 'PROJECT', field: 'Technology', topics: ['Python', 'Projects'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 92, votes: 1500, addedBy: 'team', verified: true, description: 'Build a working Discord bot using Python and host it.', duration: '5 hours', whyRecommended: 'Practical utility project. Teaches asynchronous APIs and deployment.' },

  // --- JAVA ---
  { id: 'j1', title: 'Java Programming Masterclass', url: 'https://mooc.fi/en/', source: 'Other', format: 'COURSE', field: 'Technology', topics: ['Java', 'Backend'], level: 'beginner', language: 'en', isFree: true, qualityScore: 97, votes: 4000, addedBy: 'team', verified: true, description: 'University of Helsinki\'s legendary free Java MOOC.', duration: 'Self-paced', whyRecommended: 'Legendary University MOOC. Outpaces paid bootcamps in rigorous testing and OOP design principles.' },
  { id: 'j2', title: 'Java Official Docs', url: 'https://docs.oracle.com/en/java/', source: 'Official Docs', format: 'DOCUMENTATION', field: 'Technology', topics: ['Java'], level: 'beginner', language: 'en', isFree: true, qualityScore: 90, votes: 1000, addedBy: 'team', verified: true, description: 'Official Java documentation by Oracle.', duration: 'Reference' },
  { id: 'j3', title: 'Exercism Java Track', url: 'https://exercism.org/tracks/java', source: 'Other', format: 'PRACTICE', field: 'Technology', topics: ['Java', 'Practice'], level: 'beginner', language: 'en', isFree: true, qualityScore: 95, votes: 2500, addedBy: 'team', verified: true, description: 'Interactive Java exercises.', duration: 'Self-paced' },
  { id: 'j4', title: 'Spring Boot Project Tutorial', url: 'https://spring.io/guides/gs/rest-service/', source: 'Official Docs', format: 'PROJECT', field: 'Technology', topics: ['Java', 'Projects', 'Backend'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 94, votes: 1200, addedBy: 'team', verified: true, description: 'Build a RESTful Web Service with Spring Boot.', duration: '4 hours' },

  // --- JAVASCRIPT & FRONTEND ---
  { id: 'js1', title: 'freeCodeCamp JavaScript Certification', url: 'https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/', source: 'freeCodeCamp', format: 'COURSE', field: 'Technology', topics: ['JavaScript', 'Frontend', 'Backend'], level: 'beginner', language: 'en', isFree: true, qualityScore: 99, votes: 6000, addedBy: 'team', verified: true, description: 'Comprehensive JS curriculum.', duration: 'Self-paced', whyRecommended: 'Best structured curriculum for algorithms and data structures. Hand-coded testing.' },
  { id: 'js2', title: 'MDN Web Docs - JavaScript', url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript', source: 'Official Docs', format: 'DOCUMENTATION', field: 'Technology', topics: ['JavaScript', 'Frontend'], level: 'beginner', language: 'en', isFree: true, qualityScore: 100, votes: 8000, addedBy: 'team', verified: true, description: 'The gold standard documentation for web developers.', duration: 'Reference', whyRecommended: 'The definitive documentation. Most trusted reference used by professional developers.' },
  { id: 'js3', title: 'Exercism JavaScript Track', url: 'https://exercism.org/tracks/javascript', source: 'Other', format: 'PRACTICE', field: 'Technology', topics: ['JavaScript', 'Practice'], level: 'beginner', language: 'en', isFree: true, qualityScore: 96, votes: 3500, addedBy: 'team', verified: true, description: 'Interactive JS exercises.', duration: 'Self-paced', whyRecommended: 'Great feedback loops. Teaches programming patterns with strict automated testing.' },
  { id: 'js4', title: 'Frontend Mentor', url: 'https://www.frontendmentor.io/', source: 'Other', format: 'PROJECT', field: 'Technology', topics: ['JavaScript', 'Frontend', 'Projects'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 98, votes: 4500, addedBy: 'team', verified: true, description: 'Build real-world HTML, CSS, and JS projects.', duration: 'Self-paced', whyRecommended: 'Bridges the gap between basic tutorials and building custom projects.' },

  // --- REACT ---
  { id: 'r1', title: 'The Beginner\'s Guide to React', url: 'https://egghead.io/courses/the-beginner-s-guide-to-react', source: 'Other', format: 'COURSE', field: 'Technology', topics: ['React', 'Frontend'], level: 'beginner', language: 'en', isFree: true, qualityScore: 95, votes: 3000, addedBy: 'team', verified: true, description: 'Excellent free React course by Kent C. Dodds.', duration: '3 hours' },
  { id: 'r2', title: 'React.dev Official Docs', url: 'https://react.dev/learn', source: 'Official Docs', format: 'DOCUMENTATION', field: 'Technology', topics: ['React', 'Frontend'], level: 'beginner', language: 'en', isFree: true, qualityScore: 99, votes: 7000, addedBy: 'team', verified: true, description: 'The official React documentation.', duration: 'Reference' },
  { id: 'r3', title: 'React Tutorial: Tic-Tac-Toe', url: 'https://react.dev/learn/tutorial-tic-tac-toe', source: 'Official Docs', format: 'PRACTICE', field: 'Technology', topics: ['React', 'Practice'], level: 'beginner', language: 'en', isFree: true, qualityScore: 94, votes: 2000, addedBy: 'team', verified: true, description: 'Interactive React tutorial building a game.', duration: '2 hours' },
  { id: 'r4', title: 'Build and Deploy a React App', url: 'https://www.freecodecamp.org/news/how-to-build-a-react-project-with-vite/', source: 'freeCodeCamp', format: 'PROJECT', field: 'Technology', topics: ['React', 'Projects'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 93, votes: 1800, addedBy: 'team', verified: true, description: 'End-to-end tutorial on building and deploying React.', duration: '4 hours' },

  // --- NODE.JS & BACKEND ---
  { id: 'n1', title: 'Node.js Full Course', url: 'https://www.freecodecamp.org/learn/back-end-development-and-apis/', source: 'freeCodeCamp', format: 'COURSE', field: 'Technology', topics: ['Node', 'Backend', 'JavaScript'], level: 'beginner', language: 'en', isFree: true, qualityScore: 96, votes: 4000, addedBy: 'team', verified: true, description: 'Learn Node.js, Express, and MongoDB.', duration: 'Self-paced' },
  { id: 'n2', title: 'Node.js Official Docs', url: 'https://nodejs.org/en/docs/', source: 'Official Docs', format: 'DOCUMENTATION', field: 'Technology', topics: ['Node', 'Backend'], level: 'beginner', language: 'en', isFree: true, qualityScore: 92, votes: 2000, addedBy: 'team', verified: true, description: 'The official Node.js documentation.', duration: 'Reference' },
  { id: 'n3', title: 'Nodeschool.io', url: 'https://nodeschool.io/', source: 'Other', format: 'PRACTICE', field: 'Technology', topics: ['Node', 'Practice'], level: 'beginner', language: 'en', isFree: true, qualityScore: 93, votes: 1500, addedBy: 'team', verified: true, description: 'Interactive command-line workshops for Node.js.', duration: 'Self-paced' },
  { id: 'n4', title: 'Build a CRUD API with Node', url: 'https://www.theodinproject.com/lessons/nodejs-inventory-application', source: 'Other', format: 'PROJECT', field: 'Technology', topics: ['Node', 'Backend', 'Projects'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 95, votes: 2500, addedBy: 'team', verified: true, description: 'The Odin Project Node.js project.', duration: '10 hours' },

  // --- SQL ---
  { id: 's1', title: 'Stanford Databases Course', url: 'https://online.stanford.edu/courses/soe-ydatabases-databases', source: 'Stanford', format: 'COURSE', field: 'Technology', topics: ['SQL', 'Databases', 'Backend'], level: 'beginner', language: 'en', isFree: true, qualityScore: 97, votes: 3000, addedBy: 'team', verified: true, description: 'Highly rated free Stanford course on databases.', duration: 'Self-paced' },
  { id: 's2', title: 'PostgreSQL Official Docs', url: 'https://www.postgresql.org/docs/', source: 'Official Docs', format: 'DOCUMENTATION', field: 'Technology', topics: ['SQL', 'Databases'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 95, votes: 2000, addedBy: 'team', verified: true, description: 'Official Postgres documentation.', duration: 'Reference' },
  { id: 's3', title: 'SQLBolt', url: 'https://sqlbolt.com/', source: 'Other', format: 'PRACTICE', field: 'Technology', topics: ['SQL', 'Practice'], level: 'beginner', language: 'en', isFree: true, qualityScore: 99, votes: 5000, addedBy: 'team', verified: true, description: 'The best interactive site to learn SQL queries.', duration: '4 hours' },
  { id: 's4', title: 'Database Design Project', url: 'https://www.freecodecamp.org/learn/relational-database/', source: 'freeCodeCamp', format: 'PROJECT', field: 'Technology', topics: ['SQL', 'Projects'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 94, votes: 2200, addedBy: 'team', verified: true, description: 'Build interactive databases in the browser.', duration: 'Self-paced' },

  // --- GIT & GITHUB ---
  { id: 'g1', title: 'Git & GitHub Crash Course', url: 'https://www.youtube.com/watch?v=RGOj5yH7evk', source: 'freeCodeCamp', format: 'COURSE', field: 'Technology', topics: ['Git', 'GitHub'], level: 'beginner', language: 'en', isFree: true, qualityScore: 96, votes: 4000, addedBy: 'team', verified: true, description: 'Complete crash course on version control.', duration: '1 hour' },
  { id: 'g2', title: 'Git Official Docs', url: 'https://git-scm.com/doc', source: 'Official Docs', format: 'DOCUMENTATION', field: 'Technology', topics: ['Git'], level: 'beginner', language: 'en', isFree: true, qualityScore: 95, votes: 2000, addedBy: 'team', verified: true, description: 'Pro Git book and official documentation.', duration: 'Reference' },
  { id: 'g3', title: 'Learn Git Branching', url: 'https://learngitbranching.js.org/', source: 'Other', format: 'PRACTICE', field: 'Technology', topics: ['Git', 'Practice'], level: 'beginner', language: 'en', isFree: true, qualityScore: 100, votes: 8000, addedBy: 'team', verified: true, description: 'The most visual and interactive way to learn Git.', duration: '3 hours' },
  { id: 'g4', title: 'Open Source Contribution Guide', url: 'https://github.com/firstcontributions/first-contributions', source: 'GitHub', format: 'PROJECT', field: 'Technology', topics: ['GitHub', 'Projects'], level: 'beginner', language: 'en', isFree: true, qualityScore: 98, votes: 6000, addedBy: 'team', verified: true, description: 'Make your first open source contribution on GitHub.', duration: '1 hour' },

  // --- LINUX ---
  { id: 'l1', title: 'Introduction to Linux', url: 'https://training.linuxfoundation.org/training/introduction-to-linux/', source: 'Linux Foundation', format: 'COURSE', field: 'Technology', topics: ['Linux', 'DevOps'], level: 'beginner', language: 'en', isFree: true, qualityScore: 95, votes: 2000, addedBy: 'team', verified: true, description: 'Official intro course from the Linux Foundation.', duration: 'Self-paced' },
  { id: 'l2', title: 'Linux Man Pages', url: 'https://man7.org/linux/man-pages/', source: 'Official Docs', format: 'DOCUMENTATION', field: 'Technology', topics: ['Linux'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 90, votes: 1000, addedBy: 'team', verified: true, description: 'The official Linux manual pages.', duration: 'Reference' },
  { id: 'l3', title: 'OverTheWire Bandit', url: 'https://overthewire.org/wargames/bandit/', source: 'Other', format: 'PRACTICE', field: 'Technology', topics: ['Linux', 'Cybersecurity', 'Practice'], level: 'beginner', language: 'en', isFree: true, qualityScore: 98, votes: 4000, addedBy: 'team', verified: true, description: 'Interactive wargame teaching Linux command line basics.', duration: 'Self-paced' },
  { id: 'l4', title: 'Build a Bash Script', url: 'https://www.freecodecamp.org/news/bash-scripting-tutorial-linux-shell-script-and-command-line-for-beginners/', source: 'freeCodeCamp', format: 'PROJECT', field: 'Technology', topics: ['Linux', 'Projects'], level: 'beginner', language: 'en', isFree: true, qualityScore: 92, votes: 1500, addedBy: 'team', verified: true, description: 'Write automation scripts in bash.', duration: '2 hours' },

  // --- DOCKER & KUBERNETES & CLOUD & AWS ---
  { id: 'dk1', title: 'Docker Tutorial for Beginners', url: 'https://www.youtube.com/watch?v=pTFZFxd4hOI', source: 'freeCodeCamp', format: 'COURSE', field: 'Technology', topics: ['Docker', 'DevOps', 'Kubernetes', 'Cloud', 'AWS'], level: 'beginner', language: 'en', isFree: true, qualityScore: 96, votes: 3500, addedBy: 'team', verified: true, description: 'Learn Docker containerization basics.', duration: '2 hours' },
  { id: 'dk2', title: 'Docker Official Docs', url: 'https://docs.docker.com/', source: 'Official Docs', format: 'DOCUMENTATION', field: 'Technology', topics: ['Docker', 'Kubernetes', 'Cloud', 'AWS'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 95, votes: 2000, addedBy: 'team', verified: true, description: 'Official Docker documentation.', duration: 'Reference' },
  { id: 'dk3', title: 'Play with Docker', url: 'https://labs.play-with-docker.com/', source: 'Other', format: 'PRACTICE', field: 'Technology', topics: ['Docker', 'Kubernetes', 'Practice', 'Cloud', 'AWS'], level: 'beginner', language: 'en', isFree: true, qualityScore: 97, votes: 2500, addedBy: 'team', verified: true, description: 'Interactive Docker playground in the browser.', duration: 'Self-paced' },
  { id: 'dk4', title: 'Deploy to AWS Project', url: 'https://aws.amazon.com/getting-started/hands-on/build-react-app-amplify-graphql/', source: 'AWS', format: 'PROJECT', field: 'Technology', topics: ['AWS', 'Docker', 'Kubernetes', 'Cloud', 'Projects'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 94, votes: 1800, addedBy: 'team', verified: true, description: 'Deploy a full-stack app on AWS.', duration: '4 hours' },

  // --- AI & DATA SCIENCE & MACHINE LEARNING ---
  { id: 'ai1', title: 'fast.ai Practical Deep Learning', url: 'https://course.fast.ai/', source: 'fast.ai', format: 'COURSE', field: 'Data Science', topics: ['AI', 'Data Science', 'Machine Learning'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 99, votes: 5000, addedBy: 'team', verified: true, description: 'The best top-down deep learning course available.', duration: '7 weeks' },
  { id: 'ai2', title: 'PyTorch Official Docs', url: 'https://pytorch.org/docs/stable/index.html', source: 'Official Docs', format: 'DOCUMENTATION', field: 'Data Science', topics: ['AI', 'Data Science', 'Machine Learning'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 95, votes: 3000, addedBy: 'team', verified: true, description: 'Official documentation for PyTorch.', duration: 'Reference' },
  { id: 'ai3', title: 'Kaggle Learn', url: 'https://www.kaggle.com/learn', source: 'Kaggle', format: 'PRACTICE', field: 'Data Science', topics: ['AI', 'Data Science', 'Machine Learning', 'Data Analyst', 'Practice'], level: 'beginner', language: 'en', isFree: true, qualityScore: 97, votes: 4000, addedBy: 'team', verified: true, description: 'Interactive ML and Data Science exercises.', duration: 'Self-paced' },
  { id: 'ai4', title: 'Build a Machine Learning API', url: 'https://fastapi.tiangolo.com/tutorial/', source: 'Official Docs', format: 'PROJECT', field: 'Data Science', topics: ['AI', 'Data Science', 'Machine Learning', 'Projects'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 96, votes: 2000, addedBy: 'team', verified: true, description: 'Use FastAPI to serve an ML model.', duration: '5 hours' },

  // --- CYBERSECURITY ---
  { id: 'cy1', title: 'Google Cybersecurity Certificate', url: 'https://www.youtube.com/watch?v=2KZZtS9M2C8', source: 'YouTube', format: 'COURSE', field: 'Technology', topics: ['Cybersecurity'], level: 'beginner', language: 'en', isFree: true, qualityScore: 93, votes: 1500, addedBy: 'team', verified: true, description: 'Free YouTube equivalent of the core concepts.', duration: '8 hours' },
  { id: 'cy2', title: 'OWASP Top 10 Docs', url: 'https://owasp.org/www-project-top-ten/', source: 'Official Docs', format: 'DOCUMENTATION', field: 'Technology', topics: ['Cybersecurity'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 98, votes: 3000, addedBy: 'team', verified: true, description: 'The official standard for web application security.', duration: 'Reference' },
  { id: 'cy3', title: 'TryHackMe Basics', url: 'https://tryhackme.com/', source: 'Other', format: 'PRACTICE', field: 'Technology', topics: ['Cybersecurity', 'Practice'], level: 'beginner', language: 'en', isFree: true, qualityScore: 97, votes: 4000, addedBy: 'team', verified: true, description: 'Interactive cybersecurity training labs.', duration: 'Self-paced' },
  { id: 'cy4', title: 'Security Audit Project', url: 'https://github.com/OWASP/juice-shop', source: 'GitHub', format: 'PROJECT', field: 'Technology', topics: ['Cybersecurity', 'Projects'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 95, votes: 2000, addedBy: 'team', verified: true, description: 'Hack the OWASP Juice Shop vulnerable app.', duration: '10 hours' },

  // --- FLUTTER & ANDROID ---
  { id: 'fa1', title: 'Flutter & Dart Complete Course', url: 'https://www.youtube.com/watch?v=VPvVD8t02U8', source: 'freeCodeCamp', format: 'COURSE', field: 'Technology', topics: ['Flutter', 'Android'], level: 'beginner', language: 'en', isFree: true, qualityScore: 95, votes: 2500, addedBy: 'team', verified: true, description: 'Build cross-platform apps with Flutter.', duration: '37 hours' },
  { id: 'fa2', title: 'Flutter Official Docs', url: 'https://docs.flutter.dev/', source: 'Official Docs', format: 'DOCUMENTATION', field: 'Technology', topics: ['Flutter', 'Android'], level: 'beginner', language: 'en', isFree: true, qualityScore: 97, votes: 2000, addedBy: 'team', verified: true, description: 'The official Flutter docs.', duration: 'Reference' },
  { id: 'fa3', title: 'DartPad', url: 'https://dartpad.dev/', source: 'Other', format: 'PRACTICE', field: 'Technology', topics: ['Flutter', 'Android', 'Practice'], level: 'beginner', language: 'en', isFree: true, qualityScore: 96, votes: 1500, addedBy: 'team', verified: true, description: 'Interactive Dart execution environment.', duration: 'Self-paced' },
  { id: 'fa4', title: 'Build a Weather App', url: 'https://docs.flutter.dev/cookbook', source: 'Official Docs', format: 'PROJECT', field: 'Technology', topics: ['Flutter', 'Android', 'Projects'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 94, votes: 1200, addedBy: 'team', verified: true, description: 'Build real-world mobile apps from the cookbook.', duration: 'Self-paced' },
  
  // --- GITHUB REPOS ---
  { id: 'gh_books', title: 'Free Programming Books', url: 'https://github.com/EbookFoundation/free-programming-books', source: 'GitHub', format: 'DOCUMENTATION', field: 'Technology', topics: ['Python', 'Java', 'JavaScript', 'SQL', 'Git', 'Linux'], level: 'beginner', language: 'en', isFree: true, qualityScore: 100, votes: 9000, addedBy: 'team', verified: true, description: 'The largest repository of curated free programming books and courses in the world.', duration: 'Reference', whyRecommended: 'Definitive world-class repository containing thousands of open-source programming books.' },
  { id: 'gh_ossu', title: 'OSSU Computer Science', url: 'https://github.com/ossu/computer-science', source: 'GitHub', format: 'COURSE', field: 'Technology', topics: ['Python', 'Java', 'JavaScript', 'SQL', 'Git', 'Linux', 'Practice'], level: 'beginner', language: 'en', isFree: true, qualityScore: 99, votes: 8000, addedBy: 'team', verified: true, description: 'Path to a free self-taught education in Computer Science using online materials.', duration: 'Self-paced', whyRecommended: 'Complete, structured CS curriculum modeled after MIT/Stanford syllabus requirements.' },
  { id: 'gh_books_alt', title: 'EbookFoundation Translations & Resources', url: 'https://github.com/aluismoya/EbookFoundation-free-programming-books', source: 'GitHub', format: 'DOCUMENTATION', field: 'Technology', topics: ['Python', 'JavaScript', 'SQL'], level: 'beginner', language: 'en', isFree: true, qualityScore: 95, votes: 1500, addedBy: 'team', verified: true, description: 'Spanish and multilingual programming books index.', duration: 'Reference' },
  { id: 'gh_ai_scratch', title: 'AI Engineering From Scratch', url: 'https://github.com/rohitg00/ai-engineering-from-scratch', source: 'GitHub', format: 'PROJECT', field: 'Data Science', topics: ['AI', 'Data Science', 'Machine Learning', 'Python', 'Projects'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 98, votes: 2500, addedBy: 'team', verified: true, description: 'Interactive AI & Deep Learning implementations built from absolute scratch.', duration: 'Self-paced', whyRecommended: 'Learn by building. Teaches neural networks, models, and embeddings without high-level library abstractions.' },
  { id: 'gh_project_ideas', title: 'Project Ideas & Resources', url: 'https://github.com/The-Cool-Coders/Project-Ideas-And-Resources', source: 'GitHub', format: 'PROJECT', field: 'Technology', topics: ['Projects', 'Practice', 'Python', 'JavaScript', 'Java'], level: 'beginner', language: 'en', isFree: true, qualityScore: 96, votes: 2200, addedBy: 'team', verified: true, description: 'Curated compilation of frontend, backend, and full-stack projects for students.', duration: 'Self-paced', whyRecommended: 'Bento grid of beginner-friendly resume projects with guides.' },
  { id: 'gh_build_own_x', title: 'Build Your Own X', url: 'https://github.com/codecrafters-io/build-your-own-x', source: 'GitHub', format: 'PROJECT', field: 'Technology', topics: ['Projects', 'Python', 'JavaScript', 'Java', 'SQL', 'Git', 'Docker'], level: 'intermediate', language: 'en', isFree: true, qualityScore: 100, votes: 9500, addedBy: 'team', verified: true, description: 'Learn software engineering by building your own Git, Docker, Database, or BitTorrent client from scratch.', duration: 'Self-paced', whyRecommended: 'The gold standard project repository for proving computer science competency to recruiters.' }
];
