import type { Career } from '@/types';

export const careers: Career[] = [
  {
    id: 'career-1',
    title: 'Software Engineer',
    slug: 'software-engineer',
    field: 'Technology',
    subfield: 'Software Development',
    description: 'Design, develop, and maintain software systems. Software engineers build everything from mobile apps to operating systems, working across the full stack of modern technology.',
    shortDescription: 'Build software that powers the modern world.',
    avgSalaryIndia: '₹8–30 LPA',
    avgSalaryGlobal: '$70K–$180K',
    demandTrend: 'rising',
    relatedCareers: ['career-3', 'career-5'],
    tags: ['coding', 'programming', 'web', 'mobile', 'systems'],
    icon: 'Code',
    stages: [
      { id: 's1', title: 'Foundations', description: 'Learn programming basics, data structures, and algorithms.', duration: '3–6 months', skills: ['Python', 'JavaScript', 'Data Structures', 'Algorithms'], resources: [], milestones: ['Build a calculator app', 'Solve 50 LeetCode problems'], order: 1 },
      { id: 's2', title: 'Core Skills', description: 'Master web development, databases, and version control.', duration: '4–6 months', skills: ['HTML/CSS', 'React', 'Node.js', 'SQL', 'Git'], resources: [], milestones: ['Build a full-stack CRUD app', 'Deploy to cloud'], order: 2 },
      { id: 's3', title: 'Specialization', description: 'Choose a focus: frontend, backend, mobile, or DevOps.', duration: '3–6 months', skills: ['System Design', 'Testing', 'CI/CD', 'Cloud Services'], resources: [], milestones: ['Contribute to open source', 'Build a portfolio project'], order: 3 },
      { id: 's4', title: 'Career Entry', description: 'Prepare for interviews and land your first role.', duration: '2–3 months', skills: ['DSA Practice', 'System Design', 'Behavioral Interviews'], resources: [], milestones: ['Complete mock interviews', 'Get first offer'], order: 4 },
    ],
  },
  {
    id: 'career-2',
    title: 'Data Scientist',
    slug: 'data-scientist',
    field: 'Data Science',
    subfield: 'Analytics & ML',
    description: 'Extract insights from data using statistics, machine learning, and domain expertise. Data scientists solve complex business problems by analyzing patterns in large datasets.',
    shortDescription: 'Turn data into actionable insights and predictions.',
    avgSalaryIndia: '₹10–35 LPA',
    avgSalaryGlobal: '$80K–$170K',
    demandTrend: 'rising',
    relatedCareers: ['career-1', 'career-5'],
    tags: ['data', 'machine learning', 'statistics', 'python', 'analytics'],
    icon: 'BarChart3',
    stages: [
      { id: 's1', title: 'Math & Stats', description: 'Build a strong foundation in statistics, linear algebra, and probability.', duration: '2–4 months', skills: ['Statistics', 'Linear Algebra', 'Probability', 'Python'], resources: [], milestones: ['Complete Khan Academy Stats', 'MIT OCW Linear Algebra'], order: 1 },
      { id: 's2', title: 'Data Wrangling', description: 'Learn to collect, clean, and transform data.', duration: '2–3 months', skills: ['Pandas', 'NumPy', 'SQL', 'Data Visualization'], resources: [], milestones: ['Analyze a real dataset', 'Build 3 visualizations'], order: 2 },
      { id: 's3', title: 'Machine Learning', description: 'Master supervised and unsupervised learning algorithms.', duration: '3–5 months', skills: ['Scikit-learn', 'TensorFlow', 'Feature Engineering', 'Model Evaluation'], resources: [], milestones: ['Complete fast.ai course', 'Win a Kaggle competition'], order: 3 },
      { id: 's4', title: 'Applied DS', description: 'Work on real projects and prepare for industry roles.', duration: '2–4 months', skills: ['NLP', 'Deep Learning', 'MLOps', 'Communication'], resources: [], milestones: ['Publish a project on GitHub', 'Present findings'], order: 4 },
    ],
  },
  {
    id: 'career-3',
    title: 'UX Designer',
    slug: 'ux-designer',
    field: 'Design',
    subfield: 'User Experience',
    description: 'Create intuitive, accessible, and delightful digital experiences. UX designers research user needs, prototype solutions, and work closely with engineering teams.',
    shortDescription: 'Design digital products people love to use.',
    avgSalaryIndia: '₹6–25 LPA',
    avgSalaryGlobal: '$65K–$150K',
    demandTrend: 'rising',
    relatedCareers: ['career-1', 'career-8'],
    tags: ['design', 'user research', 'figma', 'prototyping', 'ui'],
    icon: 'Palette',
    stages: [
      { id: 's1', title: 'Design Thinking', description: 'Learn the fundamentals of human-centered design and design thinking.', duration: '1–2 months', skills: ['Design Thinking', 'Empathy Mapping', 'User Research'], resources: [], milestones: ['Complete Google UX Design Course'], order: 1 },
      { id: 's2', title: 'Tools & Craft', description: 'Master design tools and visual design principles.', duration: '2–4 months', skills: ['Figma', 'Typography', 'Color Theory', 'Wireframing'], resources: [], milestones: ['Design 3 app concepts', 'Build a design system'], order: 2 },
      { id: 's3', title: 'Research & Testing', description: 'Learn user research methods and usability testing.', duration: '2–3 months', skills: ['Usability Testing', 'A/B Testing', 'Analytics', 'Accessibility'], resources: [], milestones: ['Conduct 5 user interviews', 'Run a usability test'], order: 3 },
      { id: 's4', title: 'Portfolio', description: 'Build a compelling portfolio and prepare for interviews.', duration: '1–2 months', skills: ['Case Studies', 'Presentation', 'Portfolio Design'], resources: [], milestones: ['Complete 3 case studies', 'Get design critique'], order: 4 },
    ],
  },
  {
    id: 'career-4',
    title: 'Financial Analyst',
    slug: 'financial-analyst',
    field: 'Finance',
    subfield: 'Corporate Finance',
    description: 'Analyze financial data, build models, and provide recommendations to guide business decisions. Work across investment banking, corporate finance, or wealth management.',
    shortDescription: 'Guide business decisions through financial analysis.',
    avgSalaryIndia: '₹5–20 LPA',
    avgSalaryGlobal: '$55K–$120K',
    demandTrend: 'stable',
    relatedCareers: ['career-2', 'career-9'],
    tags: ['finance', 'excel', 'modeling', 'valuation', 'accounting'],
    icon: 'TrendingUp',
    stages: [
      { id: 's1', title: 'Accounting Basics', description: 'Understand financial statements, accounting principles, and business fundamentals.', duration: '2–3 months', skills: ['Financial Accounting', 'Excel', 'Business Math'], resources: [], milestones: ['Complete Khan Academy Finance'], order: 1 },
      { id: 's2', title: 'Financial Modeling', description: 'Learn to build financial models and perform valuations.', duration: '3–4 months', skills: ['DCF Modeling', 'Valuation', 'Excel Advanced', 'Financial Analysis'], resources: [], milestones: ['Build 3 financial models'], order: 2 },
      { id: 's3', title: 'Specialization', description: 'Choose a track: investment banking, equity research, or corporate finance.', duration: '3–5 months', skills: ['Industry Analysis', 'M&A', 'Risk Management'], resources: [], milestones: ['CFA Level 1 prep', 'Stock analysis project'], order: 3 },
      { id: 's4', title: 'Career Entry', description: 'Network, prepare for interviews, and land your first role.', duration: '2–3 months', skills: ['Case Studies', 'Networking', 'Technical Interviews'], resources: [], milestones: ['Complete 10 case studies', 'Informational interviews'], order: 4 },
    ],
  },
  {
    id: 'career-5',
    title: 'AI/ML Engineer',
    slug: 'ai-ml-engineer',
    field: 'Technology',
    subfield: 'Artificial Intelligence',
    description: 'Build and deploy machine learning models and AI systems at scale. Work on everything from recommendation engines to autonomous systems and large language models.',
    shortDescription: 'Build intelligent systems that learn and adapt.',
    avgSalaryIndia: '₹12–50 LPA',
    avgSalaryGlobal: '$100K–$250K',
    demandTrend: 'rising',
    relatedCareers: ['career-1', 'career-2'],
    tags: ['ai', 'machine learning', 'deep learning', 'python', 'neural networks'],
    icon: 'Brain',
    stages: [
      { id: 's1', title: 'Prerequisites', description: 'Master Python, linear algebra, calculus, and probability.', duration: '3–4 months', skills: ['Python', 'Linear Algebra', 'Calculus', 'Probability'], resources: [], milestones: ['Complete MIT 18.06', 'Python proficiency'], order: 1 },
      { id: 's2', title: 'ML Foundations', description: 'Learn core ML algorithms and frameworks.', duration: '3–5 months', skills: ['Scikit-learn', 'Supervised Learning', 'Unsupervised Learning', 'Model Evaluation'], resources: [], milestones: ['Andrew Ng ML Course', 'Kaggle competitions'], order: 2 },
      { id: 's3', title: 'Deep Learning', description: 'Master neural networks, CNNs, RNNs, and transformers.', duration: '3–5 months', skills: ['PyTorch', 'TensorFlow', 'NLP', 'Computer Vision', 'Transformers'], resources: [], milestones: ['fast.ai courses', 'Build an LLM project'], order: 3 },
      { id: 's4', title: 'Production ML', description: 'Learn to deploy and maintain ML systems in production.', duration: '2–4 months', skills: ['MLOps', 'Docker', 'Cloud ML', 'Model Monitoring'], resources: [], milestones: ['Deploy an ML API', 'End-to-end project'], order: 4 },
    ],
  },
  {
    id: 'career-6',
    title: 'Doctor (MBBS)',
    slug: 'doctor-mbbs',
    field: 'Medicine',
    subfield: 'General Medicine',
    description: 'Diagnose and treat illnesses, promote health, and save lives. A career in medicine requires dedication but offers profound impact on individuals and communities.',
    shortDescription: 'Heal people and make a direct impact on lives.',
    avgSalaryIndia: '₹8–25 LPA',
    avgSalaryGlobal: '$60K–$300K',
    demandTrend: 'stable',
    relatedCareers: [],
    tags: ['medicine', 'neet', 'biology', 'healthcare', 'patient care'],
    icon: 'Heart',
    stages: [
      { id: 's1', title: 'NEET Preparation', description: 'Master Physics, Chemistry, and Biology for NEET-UG.', duration: '1–2 years', skills: ['Physics', 'Chemistry', 'Biology', 'NCERT Mastery'], resources: [], milestones: ['Complete NCERT cover-to-cover', 'Score 600+ in mocks'], order: 1 },
      { id: 's2', title: 'MBBS (Pre-clinical)', description: 'Study anatomy, physiology, and biochemistry in medical school.', duration: '2.5 years', skills: ['Anatomy', 'Physiology', 'Biochemistry'], resources: [], milestones: ['Clear university exams'], order: 2 },
      { id: 's3', title: 'MBBS (Clinical)', description: 'Clinical rotations and practical patient care.', duration: '2.5 years', skills: ['Clinical Skills', 'Patient Care', 'Diagnostics'], resources: [], milestones: ['Complete clinical rotations'], order: 3 },
      { id: 's4', title: 'Internship & Beyond', description: 'Complete internship and prepare for PG entrance (NEET-PG).', duration: '1 year', skills: ['Clinical Practice', 'NEET-PG Prep'], resources: [], milestones: ['Complete internship', 'Choose specialization'], order: 4 },
    ],
  },
  {
    id: 'career-7',
    title: 'Civil Services (IAS/IPS)',
    slug: 'civil-services',
    field: 'Civil Services',
    subfield: 'UPSC',
    description: 'Serve the nation as an administrator, diplomat, or police leader. Civil servants shape public policy, implement government programs, and serve millions of citizens.',
    shortDescription: 'Shape public policy and serve the nation.',
    avgSalaryIndia: '₹10–18 LPA + perks',
    avgSalaryGlobal: 'N/A (India-specific)',
    demandTrend: 'stable',
    relatedCareers: [],
    tags: ['upsc', 'ias', 'ips', 'government', 'public policy', 'administration'],
    icon: 'Landmark',
    stages: [
      { id: 's1', title: 'Foundation', description: 'Build knowledge base with NCERT books and newspapers.', duration: '3–6 months', skills: ['NCERT Mastery', 'Current Affairs', 'Essay Writing', 'General Knowledge'], resources: [], milestones: ['Read all NCERT 6-12', 'Daily newspaper habit'], order: 1 },
      { id: 's2', title: 'Prelims Prep', description: 'Prepare for UPSC Prelims (GS + CSAT).', duration: '6–8 months', skills: ['Indian Polity', 'History', 'Geography', 'Economy', 'Science'], resources: [], milestones: ['Clear prelims cutoff in mocks', 'Optional subject chosen'], order: 2 },
      { id: 's3', title: 'Mains Prep', description: 'Deep-dive into GS papers, essay, and optional subject.', duration: '4–6 months', skills: ['Answer Writing', 'Ethics', 'Optional Subject', 'Essay'], resources: [], milestones: ['Write 100+ practice answers', 'Score 50%+ in test series'], order: 3 },
      { id: 's4', title: 'Interview', description: 'Prepare for the UPSC personality test.', duration: '2–3 months', skills: ['Current Affairs', 'Communication', 'DAF Preparation'], resources: [], milestones: ['Mock interviews', 'DAF analysis'], order: 4 },
    ],
  },
  {
    id: 'career-8',
    title: 'Product Manager',
    slug: 'product-manager',
    field: 'Technology',
    subfield: 'Product Management',
    description: 'Define product strategy, prioritize features, and drive execution. Product managers sit at the intersection of business, technology, and design.',
    shortDescription: 'Define what to build and why it matters.',
    avgSalaryIndia: '₹15–45 LPA',
    avgSalaryGlobal: '$90K–$200K',
    demandTrend: 'rising',
    relatedCareers: ['career-3', 'career-1'],
    tags: ['product', 'strategy', 'analytics', 'user research', 'agile'],
    icon: 'Target',
    stages: [
      { id: 's1', title: 'Foundations', description: 'Learn product thinking, frameworks, and basic analytics.', duration: '2–3 months', skills: ['Product Thinking', 'Analytics', 'SQL', 'Market Research'], resources: [], milestones: ['Read "Inspired" by Marty Cagan'], order: 1 },
      { id: 's2', title: 'Core Skills', description: 'Master user research, prioritization, and roadmapping.', duration: '3–4 months', skills: ['User Research', 'PRD Writing', 'Roadmapping', 'A/B Testing'], resources: [], milestones: ['Write 5 PRDs', 'Conduct user interviews'], order: 2 },
      { id: 's3', title: 'Execution', description: 'Learn agile, stakeholder management, and cross-functional leadership.', duration: '2–3 months', skills: ['Agile/Scrum', 'Stakeholder Mgmt', 'Data-Driven Decisions'], resources: [], milestones: ['Ship a side project', 'Lead a product sprint'], order: 3 },
      { id: 's4', title: 'Career Entry', description: 'Build portfolio, network, and prepare for PM interviews.', duration: '2–3 months', skills: ['Case Studies', 'Product Sense', 'Technical Communication'], resources: [], milestones: ['Complete PM interview prep', 'Build product teardowns'], order: 4 },
    ],
  },
  {
    id: 'career-9',
    title: 'Entrepreneur',
    slug: 'entrepreneur',
    field: 'Entrepreneurship',
    subfield: 'Startups',
    description: 'Build and scale your own business. Entrepreneurship is about identifying problems, creating solutions, and building sustainable ventures.',
    shortDescription: 'Build something from zero to impact.',
    avgSalaryIndia: 'Varies widely',
    avgSalaryGlobal: 'Varies widely',
    demandTrend: 'rising',
    relatedCareers: ['career-8', 'career-4'],
    tags: ['startup', 'business', 'innovation', 'leadership', 'fundraising'],
    icon: 'Rocket',
    stages: [
      { id: 's1', title: 'Ideation', description: 'Find problems worth solving and validate ideas.', duration: '1–3 months', skills: ['Problem Discovery', 'Market Research', 'Customer Interviews'], resources: [], milestones: ['Complete YC Startup School', '50 customer interviews'], order: 1 },
      { id: 's2', title: 'MVP', description: 'Build a minimum viable product and get first users.', duration: '2–4 months', skills: ['No-code/Low-code', 'Basic Development', 'Landing Pages'], resources: [], milestones: ['Launch MVP', 'Get 10 paying users'], order: 2 },
      { id: 's3', title: 'Growth', description: 'Find product-market fit and scale acquisition.', duration: '3–6 months', skills: ['Growth Marketing', 'Metrics', 'Fundraising', 'Hiring'], resources: [], milestones: ['Achieve PMF signals', 'First revenue milestone'], order: 3 },
      { id: 's4', title: 'Scale', description: 'Build a team, raise funding, and scale operations.', duration: 'Ongoing', skills: ['Leadership', 'Operations', 'Finance', 'Culture'], resources: [], milestones: ['First hire', 'Sustainable unit economics'], order: 4 },
    ],
  },
  {
    id: 'career-10',
    title: 'Lawyer',
    slug: 'lawyer',
    field: 'Law',
    subfield: 'Legal Practice',
    description: 'Advocate for justice, draft legal documents, and advise clients. Lawyers work across corporate law, litigation, human rights, and public policy.',
    shortDescription: 'Advocate for justice and uphold the law.',
    avgSalaryIndia: '₹5–30 LPA',
    avgSalaryGlobal: '$60K–$200K',
    demandTrend: 'stable',
    relatedCareers: ['career-7'],
    tags: ['law', 'legal', 'advocacy', 'clat', 'litigation', 'corporate law'],
    icon: 'Scale',
    stages: [
      { id: 's1', title: 'Entrance Prep', description: 'Prepare for CLAT/AILET/LSAT for top law schools.', duration: '6–12 months', skills: ['Legal Reasoning', 'English', 'General Knowledge', 'Logical Reasoning'], resources: [], milestones: ['Score 120+ in CLAT mocks'], order: 1 },
      { id: 's2', title: 'Law School', description: 'Complete your LLB/BA-LLB degree with strong academics.', duration: '3–5 years', skills: ['Constitutional Law', 'Contract Law', 'Criminal Law', 'Legal Research'], resources: [], milestones: ['Moot court participation', 'Top 20% of class'], order: 2 },
      { id: 's3', title: 'Internships', description: 'Intern at law firms, courts, and NGOs to gain practical experience.', duration: 'During law school', skills: ['Drafting', 'Client Interaction', 'Court Procedures'], resources: [], milestones: ['5+ diverse internships'], order: 3 },
      { id: 's4', title: 'Bar & Practice', description: 'Clear AIBE and begin practice or join a firm.', duration: '6–12 months', skills: ['Bar Exam Prep', 'Networking', 'Specialization Choice'], resources: [], milestones: ['Clear AIBE', 'First case/assignment'], order: 4 },
    ],
  },
  {
    id: 'career-11',
    title: 'Cybersecurity Analyst',
    slug: 'cybersecurity-analyst',
    field: 'Technology',
    subfield: 'Information Security',
    description: 'Protect organizations from cyber threats by monitoring systems, investigating breaches, and implementing security measures. Cybersecurity is one of the fastest-growing fields globally.',
    shortDescription: 'Defend systems and data from cyber threats.',
    avgSalaryIndia: '₹6–25 LPA',
    avgSalaryGlobal: '$70K–$160K',
    demandTrend: 'rising',
    relatedCareers: ['career-1', 'career-5'],
    tags: ['security', 'hacking', 'networking', 'SOC', 'penetration testing'],
    icon: 'Monitor',
    stages: [
      { id: 's1', title: 'Networking Basics', description: 'Learn TCP/IP, DNS, firewalls, and how networks function.', duration: '2–3 months', skills: ['Networking', 'TCP/IP', 'Linux', 'Command Line'], resources: [], milestones: ['CompTIA Network+ study', 'Set up a home lab'], order: 1 },
      { id: 's2', title: 'Security Foundations', description: 'Learn security concepts, threats, and defense strategies.', duration: '3–4 months', skills: ['Security+', 'Threat Analysis', 'Encryption', 'SIEM'], resources: [], milestones: ['CompTIA Security+ prep', 'Complete TryHackMe beginner path'], order: 2 },
      { id: 's3', title: 'Hands-On Skills', description: 'Practice ethical hacking, vulnerability assessment, and incident response.', duration: '3–5 months', skills: ['Penetration Testing', 'Wireshark', 'Burp Suite', 'Incident Response'], resources: [], milestones: ['Complete 50 CTF challenges', 'HackTheBox rank'], order: 3 },
      { id: 's4', title: 'Certification & Career', description: 'Get certified and apply for security analyst roles.', duration: '2–3 months', skills: ['CEH', 'OSCP Prep', 'Report Writing'], resources: [], milestones: ['Earn Security+ or CEH', 'Build security portfolio'], order: 4 },
    ],
  },
  {
    id: 'career-12',
    title: 'Digital Marketer',
    slug: 'digital-marketer',
    field: 'Marketing',
    subfield: 'Digital Marketing',
    description: 'Plan and execute online marketing campaigns across SEO, social media, email, and paid advertising. Help businesses grow their online presence and reach target audiences.',
    shortDescription: 'Grow businesses through online marketing.',
    avgSalaryIndia: '₹4–18 LPA',
    avgSalaryGlobal: '$45K–$110K',
    demandTrend: 'rising',
    relatedCareers: ['career-9', 'career-8'],
    tags: ['marketing', 'seo', 'social media', 'content', 'ads', 'google ads'],
    icon: 'Megaphone',
    stages: [
      { id: 's1', title: 'Fundamentals', description: 'Learn marketing principles, consumer behavior, and digital channels.', duration: '1–2 months', skills: ['Marketing Basics', 'Content Writing', 'Social Media'], resources: [], milestones: ['Google Digital Marketing Certificate'], order: 1 },
      { id: 's2', title: 'SEO & Content', description: 'Master search engine optimization and content strategy.', duration: '2–3 months', skills: ['SEO', 'Keyword Research', 'Content Marketing', 'Google Analytics'], resources: [], milestones: ['Rank a blog post on page 1', 'Google Analytics certified'], order: 2 },
      { id: 's3', title: 'Paid & Social', description: 'Learn paid advertising, social media marketing, and email campaigns.', duration: '2–3 months', skills: ['Google Ads', 'Facebook Ads', 'Email Marketing', 'Copywriting'], resources: [], milestones: ['Run a campaign under ₹5000', 'Grow a social account to 1K'], order: 3 },
      { id: 's4', title: 'Analytics & Career', description: 'Master marketing analytics and build your portfolio.', duration: '1–2 months', skills: ['Data Analysis', 'A/B Testing', 'Marketing Automation'], resources: [], milestones: ['Portfolio of 3 campaigns', 'Freelance project'], order: 4 },
    ],
  },
  {
    id: 'career-13',
    title: 'Chartered Accountant',
    slug: 'chartered-accountant',
    field: 'Finance',
    subfield: 'Accounting',
    description: 'Manage financial records, conduct audits, provide tax advisory, and ensure regulatory compliance. CAs are among the most respected professionals in India.',
    shortDescription: 'Master finance, audit, and taxation.',
    avgSalaryIndia: '₹7–30 LPA',
    avgSalaryGlobal: '$50K–$120K',
    demandTrend: 'stable',
    relatedCareers: ['career-4'],
    tags: ['accounting', 'ca', 'audit', 'taxation', 'finance', 'icai'],
    icon: 'Landmark',
    stages: [
      { id: 's1', title: 'CA Foundation', description: 'Clear the CA Foundation exam after Class 12.', duration: '4–8 months', skills: ['Accounting', 'Business Law', 'Mathematics', 'Economics'], resources: [], milestones: ['Clear CA Foundation exam'], order: 1 },
      { id: 's2', title: 'CA Intermediate', description: 'Clear both groups of CA Inter while starting articleship.', duration: '8–18 months', skills: ['Advanced Accounting', 'Taxation', 'Audit', 'Cost Accounting'], resources: [], milestones: ['Clear CA Inter (both groups)'], order: 2 },
      { id: 's3', title: 'Articleship', description: 'Complete 3 years of practical training under a CA.', duration: '3 years', skills: ['Practical Auditing', 'Tax Filing', 'Financial Reporting'], resources: [], milestones: ['Complete articleship'], order: 3 },
      { id: 's4', title: 'CA Final', description: 'Clear CA Final and become a Chartered Accountant.', duration: '6–12 months', skills: ['Financial Reporting', 'Strategic Management', 'Advanced Audit'], resources: [], milestones: ['Clear CA Final', 'ICAI membership'], order: 4 },
    ],
  },
  {
    id: 'career-14',
    title: 'Mechanical Engineer',
    slug: 'mechanical-engineer',
    field: 'Engineering',
    subfield: 'Mechanical Engineering',
    description: 'Design, analyze, and manufacture mechanical systems. From automobiles to aerospace, mechanical engineers solve problems across every industry.',
    shortDescription: 'Design and build machines that move the world.',
    avgSalaryIndia: '₹4–20 LPA',
    avgSalaryGlobal: '$55K–$130K',
    demandTrend: 'stable',
    relatedCareers: [],
    tags: ['engineering', 'jee', 'design', 'manufacturing', 'cad', 'thermodynamics'],
    icon: 'Wrench',
    stages: [
      { id: 's1', title: 'JEE Preparation', description: 'Master Physics, Chemistry, and Maths for JEE Main/Advanced.', duration: '1–2 years', skills: ['Physics', 'Chemistry', 'Mathematics', 'Problem Solving'], resources: [], milestones: ['Score 200+ in JEE Main mocks', 'NCERT mastery'], order: 1 },
      { id: 's2', title: 'Core Engineering', description: 'Study mechanics, thermodynamics, and material science in college.', duration: '2 years', skills: ['Thermodynamics', 'Mechanics', 'Material Science', 'CAD'], resources: [], milestones: ['SolidWorks/AutoCAD proficiency', 'Strong CGPA'], order: 2 },
      { id: 's3', title: 'Specialization', description: 'Choose focus: automotive, aerospace, robotics, or thermal systems.', duration: '2 years', skills: ['FEA', 'CFD', 'Robotics', 'Manufacturing'], resources: [], milestones: ['Design project', 'Internship at top company'], order: 3 },
      { id: 's4', title: 'Career Entry', description: 'Prepare for GATE or campus placements.', duration: '6–12 months', skills: ['GATE Prep', 'Technical Interviews', 'Project Portfolio'], resources: [], milestones: ['Clear GATE or get placed', 'First engineering role'], order: 4 },
    ],
  },
  {
    id: 'career-15',
    title: 'Content Creator',
    slug: 'content-creator',
    field: 'Media',
    subfield: 'Content Creation',
    description: 'Create engaging content across YouTube, Instagram, blogs, podcasts, or newsletters. Build an audience, monetize your expertise, and become a thought leader.',
    shortDescription: 'Build an audience through compelling content.',
    avgSalaryIndia: '₹2–50 LPA',
    avgSalaryGlobal: '$30K–$500K+',
    demandTrend: 'rising',
    relatedCareers: ['career-12', 'career-9'],
    tags: ['youtube', 'content', 'writing', 'video', 'social media', 'creator'],
    icon: 'Monitor',
    stages: [
      { id: 's1', title: 'Find Your Niche', description: 'Identify your expertise, target audience, and content format.', duration: '1–2 months', skills: ['Niche Research', 'Content Strategy', 'Platform Selection'], resources: [], milestones: ['Define your niche and audience', 'Study 10 top creators'], order: 1 },
      { id: 's2', title: 'Create & Publish', description: 'Start creating and publishing consistently.', duration: '3–6 months', skills: ['Video Editing', 'Writing', 'Photography', 'Storytelling'], resources: [], milestones: ['Publish 30 pieces of content', 'Reach first 100 followers'], order: 2 },
      { id: 's3', title: 'Grow Your Audience', description: 'Learn growth strategies, SEO, and community building.', duration: '3–6 months', skills: ['SEO', 'Analytics', 'Community Building', 'Collaboration'], resources: [], milestones: ['Reach 1,000 followers', 'Consistent engagement'], order: 3 },
      { id: 's4', title: 'Monetize', description: 'Turn your audience into a sustainable income stream.', duration: 'Ongoing', skills: ['Sponsorships', 'Affiliate Marketing', 'Products', 'Brand Deals'], resources: [], milestones: ['First brand deal', 'First ₹10K month'], order: 4 },
    ],
  },
  {
    id: 'career-16',
    title: 'DevOps Engineer',
    slug: 'devops-engineer',
    field: 'Technology',
    subfield: 'DevOps & Cloud',
    description: 'Bridge the gap between development and operations. Automate deployments, manage infrastructure, and ensure reliable, scalable systems.',
    shortDescription: 'Automate, deploy, and scale infrastructure.',
    avgSalaryIndia: '₹8–30 LPA',
    avgSalaryGlobal: '$80K–$170K',
    demandTrend: 'rising',
    relatedCareers: ['career-1', 'career-11'],
    tags: ['devops', 'cloud', 'docker', 'kubernetes', 'ci/cd', 'aws'],
    icon: 'Code',
    stages: [
      { id: 's1', title: 'Linux & Networking', description: 'Master Linux administration and networking fundamentals.', duration: '2–3 months', skills: ['Linux', 'Bash', 'Networking', 'DNS'], resources: [], milestones: ['Linux administration proficiency', 'Set up servers'], order: 1 },
      { id: 's2', title: 'Containers & CI/CD', description: 'Learn Docker, CI/CD pipelines, and automation.', duration: '2–4 months', skills: ['Docker', 'GitHub Actions', 'Jenkins', 'Git'], resources: [], milestones: ['Dockerize an app', 'Build a CI/CD pipeline'], order: 2 },
      { id: 's3', title: 'Cloud & Orchestration', description: 'Master cloud platforms and Kubernetes.', duration: '3–5 months', skills: ['AWS/GCP', 'Kubernetes', 'Terraform', 'Ansible'], resources: [], milestones: ['AWS Cloud Practitioner cert', 'Deploy a K8s cluster'], order: 3 },
      { id: 's4', title: 'SRE & Monitoring', description: 'Learn observability, SRE practices, and production systems.', duration: '2–3 months', skills: ['Prometheus', 'Grafana', 'SRE Practices', 'Incident Management'], resources: [], milestones: ['Set up monitoring stack', 'On-call simulation'], order: 4 },
    ],
  },
  {
    id: 'career-17',
    title: 'Psychologist',
    slug: 'psychologist',
    field: 'Medicine',
    subfield: 'Mental Health',
    description: 'Study human behavior and mental processes. Help individuals overcome challenges through therapy, counseling, and research-based interventions.',
    shortDescription: 'Understand minds and help people thrive.',
    avgSalaryIndia: '₹4–15 LPA',
    avgSalaryGlobal: '$50K–$120K',
    demandTrend: 'rising',
    relatedCareers: ['career-6'],
    tags: ['psychology', 'mental health', 'counseling', 'therapy', 'research'],
    icon: 'Heart',
    stages: [
      { id: 's1', title: 'BA/BSc Psychology', description: 'Complete undergraduate degree in Psychology.', duration: '3 years', skills: ['General Psychology', 'Statistics', 'Research Methods', 'Abnormal Psychology'], resources: [], milestones: ['Complete BA/BSc Psychology', 'Research project'], order: 1 },
      { id: 's2', title: 'MA/MSc Psychology', description: 'Specialize in clinical, counseling, or organizational psychology.', duration: '2 years', skills: ['Clinical Psychology', 'Psychometrics', 'Counseling Techniques', 'CBT'], resources: [], milestones: ['Complete Master\'s', 'Supervised clinical hours'], order: 2 },
      { id: 's3', title: 'Certification', description: 'Get RCI registration or relevant certification.', duration: '6–12 months', skills: ['RCI Registration', 'Ethics', 'Case Formulation'], resources: [], milestones: ['RCI certification', 'Supervised practice'], order: 3 },
      { id: 's4', title: 'Practice', description: 'Start clinical practice or join a hospital/clinic.', duration: 'Ongoing', skills: ['Therapy', 'Diagnosis', 'Treatment Planning'], resources: [], milestones: ['First independent client', 'Build practice'], order: 4 },
    ],
  },
  {
    id: 'career-18',
    title: 'Journalist',
    slug: 'journalist',
    field: 'Media',
    subfield: 'Journalism',
    description: 'Investigate stories, report news, and inform the public. Modern journalism spans print, digital, broadcast, and independent media.',
    shortDescription: 'Tell stories that inform and inspire.',
    avgSalaryIndia: '₹3–15 LPA',
    avgSalaryGlobal: '$35K–$90K',
    demandTrend: 'stable',
    relatedCareers: ['career-15'],
    tags: ['journalism', 'writing', 'media', 'reporting', 'communication'],
    icon: 'BookOpen',
    stages: [
      { id: 's1', title: 'Education', description: 'Study journalism, mass communication, or English literature.', duration: '3 years', skills: ['News Writing', 'Media Ethics', 'Research', 'English'], resources: [], milestones: ['BA in Journalism/Mass Comm', 'College newspaper'], order: 1 },
      { id: 's2', title: 'Beat Reporting', description: 'Learn beat reporting, interviewing, and fact-checking.', duration: '6–12 months', skills: ['Interviewing', 'Fact-Checking', 'AP Style', 'Digital Tools'], resources: [], milestones: ['Publish 20+ articles', 'Internship at publication'], order: 2 },
      { id: 's3', title: 'Digital Skills', description: 'Master multimedia journalism, SEO, and social reporting.', duration: '3–6 months', skills: ['Video Journalism', 'Podcasting', 'SEO', 'Data Journalism'], resources: [], milestones: ['Multimedia portfolio', 'Data-driven story'], order: 3 },
      { id: 's4', title: 'Career Growth', description: 'Build a byline portfolio and establish your reputation.', duration: 'Ongoing', skills: ['Investigative Reporting', 'Editing', 'Personal Brand'], resources: [], milestones: ['Regular byline at publication', 'Specialization established'], order: 4 },
    ],
  },
  {
    id: 'career-19',
    title: 'Architect',
    slug: 'architect',
    field: 'Design',
    subfield: 'Architecture',
    description: 'Design buildings, spaces, and urban environments. Architects blend creativity with engineering to create functional, sustainable, and beautiful structures.',
    shortDescription: 'Design buildings and shape the built world.',
    avgSalaryIndia: '₹5–20 LPA',
    avgSalaryGlobal: '$50K–$130K',
    demandTrend: 'stable',
    relatedCareers: ['career-3'],
    tags: ['architecture', 'design', 'construction', 'nata', 'urban planning'],
    icon: 'Palette',
    stages: [
      { id: 's1', title: 'NATA/JEE Prep', description: 'Prepare for NATA or JEE Paper 2 for architecture entrance.', duration: '6–12 months', skills: ['Drawing', 'Spatial Reasoning', 'Mathematics', 'Design Aptitude'], resources: [], milestones: ['Clear NATA/JEE', 'Portfolio of sketches'], order: 1 },
      { id: 's2', title: 'B.Arch Studies', description: 'Complete the 5-year Bachelor of Architecture degree.', duration: '5 years', skills: ['Design Studio', 'Structural Systems', 'Building Services', 'History of Architecture'], resources: [], milestones: ['Design thesis', 'Construction site visits'], order: 2 },
      { id: 's3', title: 'Internship', description: 'Intern at architecture firms to gain practical experience.', duration: 'During B.Arch', skills: ['AutoCAD', 'Revit', 'SketchUp', 'Client Interaction'], resources: [], milestones: ['6+ months internship', 'Real project contribution'], order: 3 },
      { id: 's4', title: 'License & Practice', description: 'Register with Council of Architecture and begin practice.', duration: '6–12 months', skills: ['COA Registration', 'Project Management', 'Business Development'], resources: [], milestones: ['COA registration', 'First independent project'], order: 4 },
    ],
  },
  {
    id: 'career-20',
    title: 'Pharmacist',
    slug: 'pharmacist',
    field: 'Medicine',
    subfield: 'Pharmacy',
    description: 'Ensure safe and effective use of medications. Pharmacists work in hospitals, retail pharmacies, pharmaceutical companies, and research laboratories.',
    shortDescription: 'Ensure safe medication use and patient care.',
    avgSalaryIndia: '₹3–12 LPA',
    avgSalaryGlobal: '$80K–$140K',
    demandTrend: 'stable',
    relatedCareers: ['career-6'],
    tags: ['pharmacy', 'medicine', 'drugs', 'healthcare', 'research'],
    icon: 'Atom',
    stages: [
      { id: 's1', title: 'B.Pharm Entrance', description: 'Prepare for pharmacy entrance exams (GPAT, state-level).', duration: '6–12 months', skills: ['Chemistry', 'Biology', 'Physics', 'Mathematics'], resources: [], milestones: ['Clear entrance exam', 'Admit to B.Pharm'], order: 1 },
      { id: 's2', title: 'B.Pharm Studies', description: 'Complete 4-year Bachelor of Pharmacy degree.', duration: '4 years', skills: ['Pharmacology', 'Pharmaceutics', 'Medicinal Chemistry', 'Pharmacognosy'], resources: [], milestones: ['Complete B.Pharm', 'Hospital pharmacy training'], order: 2 },
      { id: 's3', title: 'Specialization', description: 'Choose M.Pharm or pharma industry path.', duration: '2 years', skills: ['Drug Development', 'Quality Control', 'Regulatory Affairs'], resources: [], milestones: ['M.Pharm or industry placement'], order: 3 },
      { id: 's4', title: 'Registration & Practice', description: 'Register with pharmacy council and begin professional practice.', duration: '3–6 months', skills: ['Registration', 'Patient Counseling', 'Drug Interaction'], resources: [], milestones: ['Pharmacy council registration', 'First professional role'], order: 4 },
    ],
  },
];
