
import {
  BookOpenCheck,
  BrainCircuit,
  Building,
  Server,
  University,
  Youtube,
  Globe,
  Award,
  type LucideIcon,
  Lightbulb,
  Code,
  Sparkles,
  Terminal,
  Facebook,
  Database,
  ShoppingBag,
  Trophy,
  School,
  Linkedin,
  PlayCircle,
  Cloud,
  ShieldCheck,
  Briefcase,
  Users,
  PenTool,
  Book,
  Newspaper,
  FileText,
  Github,
  Mail,
  Home,
} from "lucide-react";
import type { Provider } from "@/lib/types";

type ProviderIconProps = {
  provider: Provider | string;
  className?: string;
};

const iconMap: Record<Provider | string, LucideIcon> = {
  Coursera: BookOpenCheck,
  Google: BrainCircuit,
  Microsoft: Globe,
  IBM: Server,
  edX: Award,
  Harvard: University,
  "Harvard University": University,
  MIT: University,
  YouTube: Youtube,
  "Class Central": Building,
  Udemy: Lightbulb,
  freeCodeCamp: Code,
  Skillshare: Sparkles,
  Stanford: University,
  "Stanford University": University,
  Yale: University,
  "The Linux Foundation": Terminal,
  "University of Michigan": University,
  Meta: Facebook,
  "The Data Incubator": Database,
  "University of Oxford": University,
  Amazon: ShoppingBag,
  "Amazon Web Services": Cloud,
  OpenAI: BrainCircuit,
  Kaggle: Trophy,
  CalArts: University,
  MoMA: Building,
  "Princeton University": University,
  DataCamp: Database,
  "University of California, San Diego": University,
  "Macquarie University": University,
  "University of Edinburgh": University,
  "University of Chicago": University,
  Udacity: Code,
  "LinkedIn Learning": Linkedin,
  Codecademy: Terminal,
  FutureLearn: Lightbulb,
  "Khan Academy": School,
  Pluralsight: PlayCircle,
  "A Cloud Guru": Cloud,
  "DeepLearning.AI": BrainCircuit,
  "Johns Hopkins University": University,
  "Duke University": University,
  "University of Pennsylvania": University,
  "University of Illinois": University,
  "Google Cloud": Cloud,
  "Cybersecurity and Infrastructure Security Agency": ShieldCheck,
  "The Pragmatic Programmer": Briefcase,
  "Scrum.org": Users,
  "Atlassian": Users,
  "Michigan State University": University,
  "University of California, Santa Cruz": University,
  "Fannie and John Hertz Foundation": Award,
  "Thiel Foundation": Sparkles,
  "Adobe": Sparkles,
  Holloway: Book,
  "Y Combinator": Briefcase,
  "First Round": Newspaper,
  "Paul Graham": PenTool,
  Stratechery: Newspaper,
  Reforge: Book,
  "Lenny's Newsletter": Mail,
  "Resume Worded": FileText,
  Teamblind: Users,
  "Levels.fyi": Database,
  "The Pragmatic Engineer": PenTool,
  "Andreessen Horowitz": Home,
  "Dan Luu": PenTool,
  "Donne Martin": Github,
  "Yangshun Tay": PenTool,
};

export const ProviderIcon = ({ provider, className }: ProviderIconProps) => {
  const IconComponent = iconMap[provider as Provider] || Building;
  return <IconComponent className={className} />;
};
